"""Regression tests for #2261 on the reduction-objective upload route.

``POST /v1/year-configuration/{year}/upload`` had the identical hole to
``POST /v1/files/temp-upload`` — ``File(...)``/``Form(...)`` params force
FastAPI to read the whole body before any dependency resolves — and it was
the worse of the two: no size cap at all.

Both are covered by the same ``AuthFirstRoute`` applied to their routers.
Helpers are shared with the temp-upload tests rather than duplicated.
"""

from unittest.mock import MagicMock

import pytest
from fastapi.testclient import TestClient

from app.api.auth_first_route import AuthFirstRoute
from app.api.deps import get_current_user
from app.api.v1 import year_configuration as year_config_module
from app.main import app
from app.models.user import User
from tests.unit.v1.test_temp_upload_auth_ordering import (
    build_multipart_body,
    call_asgi,
    find_route,
    valid_access_token,
)

UPLOAD_PATH = "/api/v1/year-configuration/2025/upload"


@pytest.fixture
def authorised_editor(monkeypatch):
    """Authenticate, and let the permission check pass.

    ``is_permitted`` reaches OPA, so it is patched on the endpoint module
    where the name is bound — these tests are about the *ordering* of auth
    against body parsing, not the permission decision itself.
    """
    fake = MagicMock(spec=User)
    fake.id = 1
    app.dependency_overrides[get_current_user] = lambda: fake

    async def _allow(*_args, **_kwargs) -> bool:
        return True

    monkeypatch.setattr(year_config_module, "is_permitted", _allow)
    yield TestClient(app, cookies={"auth_token": valid_access_token()})
    app.dependency_overrides.clear()


def test_unauthenticated_upload_never_reads_body():
    """No auth cookie -> 401, and ``receive`` is never invoked."""
    body, boundary = build_multipart_body(field="file")
    receive_calls, status_code = call_asgi(UPLOAD_PATH, body, boundary)

    assert receive_calls == 0, (
        "auth must reject the request before the body is ever read from the wire"
    )
    assert status_code == 401


def test_reduction_objective_upload_uses_auth_first_route():
    """Structural canary: without ``route_class`` the pre-auth body parsing
    comes straight back and every happy-path test here still passes.
    """
    route = find_route(app.routes, "/year-configuration/{year}/upload")
    assert route is not None, "reduction-objective upload route not found"
    assert isinstance(route, AuthFirstRoute)


def test_openapi_documents_the_multipart_body():
    """The schema is generated by FastAPI again, not hand-written — this
    pins that the endpoint still advertises both parts to the frontend
    client generator.
    """
    schema = app.openapi()["paths"]["/v1/year-configuration/{year}/upload"]["post"]
    assert "multipart/form-data" in schema["requestBody"]["content"]


def test_oversized_file_is_rejected_after_auth(authorised_editor):
    """This route previously had no size limit at all. Authenticated abuse is
    now bounded by the same per-file cap every other upload path uses.
    """
    original_max_size = year_config_module.file_checker.max_size
    year_config_module.file_checker.max_size = 5  # bytes, for a cheap payload
    try:
        resp = authorised_editor.post(
            UPLOAD_PATH,
            files={"file": ("data.csv", b"col1,col2\n1,2\n", "text/csv")},
            data={"category": "footprint"},
        )
        assert resp.status_code == 400, resp.text
        assert "exceeds max size" in resp.text
    finally:
        year_config_module.file_checker.max_size = original_max_size


def test_upload_rejects_unknown_category(authorised_editor):
    """``FileCategory`` is a ``Literal``; keeping the ``Form(...)`` signature
    means FastAPI validates it for us instead of the endpoint hand-rolling it.
    """
    resp = authorised_editor.post(
        UPLOAD_PATH,
        files={"file": ("data.csv", b"col1,col2\n1,2\n", "text/csv")},
        data={"category": "bogus"},
    )
    assert resp.status_code == 422, resp.text
