version: 2
updates:
# --- only dev to avoid pull request on main branch ---
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 5
    assignees:
      - "co2-calculator"
    labels:
      - "dependencies"
      - "dev"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 5
    assignees:
      - "co2-calculator"
    labels:
      - "dependencies"
      - "dev"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 5
    assignees:
      - "co2-calculator"
    labels:
      - "dependencies"
      - "dev"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]