// AUTO-GENERATED by backend `make gen-module-constants` — do not edit.
// Source: backend/app/models/data_entry.py (DataEntryTypeEnum).
export const DATA_ENTRY_TYPE_IDS = {
  member: 1,
  student: 2,
  scientific: 10,
  it: 11,
  other: 12,
  plane: 20,
  train: 21,
  building: 30,
  energy_combustion: 31,
  building_embodied_energy: 32,
  external_clouds: 40,
  external_ai: 41,
  process_emissions: 50,
  scientific_equipment: 60,
  it_equipment: 61,
  consumable_accessories: 62,
  biological_chemical_gaseous_product: 63,
  services: 64,
  vehicles: 65,
  other_purchases: 66,
  purchases_centralized: 67,
  research_facilities: 70,
  animal_facilities: 71,
  planner_headcount: 80,
  planner_purchase: 81,
  planner_purchase_budget: 82,
} as const;

// AUTO-GENERATED by backend `make gen-module-constants` — do not edit.
// Source: backend/app/utils/currencies.py (SUPPORTED_CURRENCIES).
export const CURRENCY_CODES = [
  'aud',
  'cad',
  'chf',
  'cny',
  'eur',
  'gbp',
  'jpy',
  'sek',
  'usd',
] as const;

// AUTO-GENERATED by backend `make gen-module-constants` — do not edit.
// Source: backend/app/modules/buildings/data_entries.py (VALID_ROOM_TYPES).
export const ROOM_TYPES = [
  'laboratories',
  'office',
  'archives',
  'libraries',
  'auditoriums',
  'miscellaneous',
] as const;

// AUTO-GENERATED by backend `make gen-module-constants` — do not edit.
// Source: backend/app/modules/professional_travel/emissions.py (PLANE_CABIN_MAP).
export const PLANE_CABIN_CLASSES = ['business', 'economy'] as const;

// AUTO-GENERATED by backend `make gen-module-constants` — do not edit.
// Source: backend/app/modules/professional_travel/emissions.py (TRAIN_CLASS_MAP).
export const TRAIN_CABIN_CLASSES = ['first', 'second'] as const;

// AUTO-GENERATED by backend `make gen-module-constants` — do not edit.
// Source: backend/app/modules/headcount/data_entries.py (SIUS_CODE_VALUES, excludes the OTHER_SIUS_CODE display-only sentinel).
export const SIUS_CODES = [
  '51',
  '52',
  '53',
  '54',
  '56',
  '57',
  '58',
  '59',
] as const;
