"""add submodule column to headcount

Revision ID: 00808d9948d7
Revises: ebbffa858d93
Create Date: 2025-12-17 10:59:52.453867

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00808d9948d7"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "ebbffa858d93"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "headcounts",
        sa.Column("submodule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.create_index(
        op.f("ix_headcounts_submodule"), "headcounts", ["submodule"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_headcounts_submodule"), table_name="headcounts")
    op.drop_column("headcounts", "submodule")
    # ### end Alembic commands ###
