"""new headcount schema

Revision ID: ebbffa858d93
Revises: 4ce29f492b5b
Create Date: 2025-12-16 12:44:53.603603

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebbffa858d93"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "4ce29f492b5b"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "headcounts",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column(
            "unit_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "unit_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("cf", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "cf_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "cf_user_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False
        ),
        sa.Column(
            "function", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "sciper", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column("ept", sa.Float(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_headcounts_created_by"), "headcounts", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_headcounts_sciper"), "headcounts", ["sciper"], unique=False
    )
    op.create_index(
        op.f("ix_headcounts_unit_id"), "headcounts", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_headcounts_updated_by"), "headcounts", ["updated_by"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_headcounts_updated_by"), table_name="headcounts")
    op.drop_index(op.f("ix_headcounts_unit_id"), table_name="headcounts")
    op.drop_index(op.f("ix_headcounts_sciper"), table_name="headcounts")
    op.drop_index(op.f("ix_headcounts_created_by"), table_name="headcounts")
    op.drop_table("headcounts")
    # ### end Alembic commands ###
