"""add cf_user_id to optional for headcount

Revision ID: 796bf83ead7a
Revises: 1cfa7d5e2c93
Create Date: 2025-12-17 12:33:20.868214

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "796bf83ead7a"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "1cfa7d5e2c93"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "headcounts", "cf_user_id", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "headcounts", "cf_user_id", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    # ### end Alembic commands ###
