"""add function

Revision ID: 04a352ec0235
Revises: 1c1009d31349
Create Date: 2025-12-19 15:48:56.382563

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04a352ec0235"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "1c1009d31349"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "headcounts",
        sa.Column(
            "function_role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("headcounts", "function_role")
    # ### end Alembic commands ###
