"""headcount replace ept by fte

Revision ID: 1c1009d31349
Revises: 796bf83ead7a
Create Date: 2025-12-18 11:36:06.358269

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c1009d31349"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "796bf83ead7a"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add the new column as nullable first
    op.add_column("headcounts", sa.Column("fte", sa.Float(), nullable=True))

    # Step 2: Copy data from ept to fte
    op.execute("UPDATE headcounts SET fte = ept")

    # Step 3: Make fte NOT NULL (if you need it to be required)
    op.alter_column("headcounts", "fte", nullable=False)

    # Step 4: Drop the old column
    op.drop_column("headcounts", "ept")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("headcounts", sa.Column("ept", sa.Float(), nullable=True))
    op.execute("UPDATE headcounts SET ept = fte")
    op.alter_column("headcounts", "ept", nullable=False)
    op.drop_column("headcounts", "fte")
    # ### end Alembic commands ###
