"""add_principal_user_name_and_email_to_units

Revision ID: d17d3ff75096
Revises: a1b2c3d4e5f6
Create Date: 2025-12-09 17:46:01.525697

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d17d3ff75096"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "equipment", "submodule", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_power_factors_category"), table_name="power_factors")
    op.create_index(
        op.f("ix_power_factors_submodule"), "power_factors", ["submodule"], unique=False
    )
    op.add_column(
        "units",
        sa.Column(
            "principal_user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "principal_user_email", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "principal_user_email")
    op.drop_column("units", "principal_user_name")
    op.drop_index(op.f("ix_power_factors_submodule"), table_name="power_factors")
    op.create_index(
        op.f("ix_power_factors_category"), "power_factors", ["submodule"], unique=False
    )
    op.alter_column("equipment", "submodule", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
