"""initial schema

Revision ID: 86752ebb8a77
Revises:
Create Date: 2025-10-31 14:20:30.308981

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "86752ebb8a77"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "roles",
            existing_type=sa.JSON(),
            nullable=False,
            comment="User roles for the user",
            existing_comment="User roles for RBAC",
        )
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column(
            "is_superuser", existing_type=sa.BOOLEAN(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("is_superuser", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.alter_column(
            "roles",
            existing_type=sa.JSON(),
            nullable=True,
            comment="User roles for RBAC",
            existing_comment="User roles for the user",
        )
    # ### end Alembic commands ###
