"""make headcount column optional default null to be able to have student in it

Revision ID: 1cfa7d5e2c93
Revises: 00808d9948d7
Create Date: 2025-12-17 12:31:16.572537

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1cfa7d5e2c93"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "00808d9948d7"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "headcounts",
        "display_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
    )
    op.alter_column(
        "headcounts", "status", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column(
        "headcounts", "function", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "headcounts", "sciper", existing_type=sa.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "headcounts", "sciper", existing_type=sa.VARCHAR(length=20), nullable=False
    )
    op.alter_column(
        "headcounts", "function", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "headcounts", "status", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column(
        "headcounts",
        "display_name",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    # ### end Alembic commands ###
