"""remove power factor column inside equipment

Revision ID: 8825f08d1f7f
Revises: 04a352ec0235
Create Date: 2025-12-22 13:22:18.020044

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8825f08d1f7f"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "04a352ec0235"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("equipment", "active_power_w")
    op.drop_column("equipment", "standby_power_w")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "equipment",
        sa.Column(
            "standby_power_w",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "equipment",
        sa.Column(
            "active_power_w",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
