"""

Revision ID: 4ce29f492b5b
Revises: 4241e81a24a7
Create Date: 2025-12-15 11:28:10.472855

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ce29f492b5b"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "4241e81a24a7"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units",
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "provider")
    # ### end Alembic commands ###
