"""add_display_name_for_user

Revision ID: c8fafadc86ed
Revises: d17d3ff75096
Create Date: 2025-12-10 11:27:26.590376

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8fafadc86ed"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "d17d3ff75096"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("units_principal_user_id_fkey"), "units", type_="foreignkey"
    )
    op.add_column(
        "users",
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_index(op.f("ix_users_sciper"), table_name="users")
    op.drop_column("users", "sciper")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("sciper", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_index(op.f("ix_users_sciper"), "users", ["sciper"], unique=True)
    op.drop_column("users", "display_name")
    op.create_foreign_key(
        op.f("units_principal_user_id_fkey"),
        "units",
        "users",
        ["principal_user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
