"""add_emission_factors_and_equipment_tables

Revision ID: 4bead03d8536
Revises: ee82301536e1
Create Date: 2025-12-02 12:39:35.645446

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bead03d8536"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "ee82301536e1"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emission_factors",
        sa.Column("factor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("factor_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emission_factors_created_by"),
        "emission_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_factor_name"),
        "emission_factors",
        ["factor_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_id"), "emission_factors", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_region"), "emission_factors", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_version"),
        "emission_factors",
        ["version"],
        unique=False,
    )
    op.create_table(
        "power_factors",
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sub_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "equipment_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("sub_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active_power_w", sa.Float(), nullable=False),
        sa.Column("standby_power_w", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("power_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_power_factors_category"), "power_factors", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_created_by"),
        "power_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_power_factors_equipment_class"),
        "power_factors",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(op.f("ix_power_factors_id"), "power_factors", ["id"], unique=False)
    op.create_index(
        op.f("ix_power_factors_sub_category"),
        "power_factors",
        ["sub_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_power_factors_sub_class"), "power_factors", ["sub_class"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_version"), "power_factors", ["version"], unique=False
    )
    op.create_table(
        "equipment",
        sa.Column("cost_center", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "cost_center_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "equipment_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("sub_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("service_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active_usage_pct", sa.Float(), nullable=True),
        sa.Column("passive_usage_pct", sa.Float(), nullable=True),
        sa.Column("active_power_w", sa.Float(), nullable=True),
        sa.Column("standby_power_w", sa.Float(), nullable=True),
        sa.Column("power_factor_id", sa.Integer(), nullable=True),
        sa.Column("unit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("equipment_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_equipment_category"), "equipment", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_cost_center"), "equipment", ["cost_center"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_created_by"), "equipment", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_equipment_class"),
        "equipment",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_index(op.f("ix_equipment_name"), "equipment", ["name"], unique=False)
    op.create_index(
        op.f("ix_equipment_power_factor_id"),
        "equipment",
        ["power_factor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_equipment_status"), "equipment", ["status"], unique=False)
    op.create_index(
        op.f("ix_equipment_unit_id"), "equipment", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_updated_by"), "equipment", ["updated_by"], unique=False
    )
    op.create_table(
        "equipment_emissions",
        sa.Column("equipment_id", sa.Integer(), nullable=False),
        sa.Column("annual_kwh", sa.Float(), nullable=False),
        sa.Column("kg_co2eq", sa.Float(), nullable=False),
        sa.Column("emission_factor_id", sa.Integer(), nullable=False),
        sa.Column("power_factor_id", sa.Integer(), nullable=True),
        sa.Column(
            "formula_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("computed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("calculation_inputs", sa.JSON(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["emission_factor_id"],
            ["emission_factors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_equipment_emissions_computed_at"),
        "equipment_emissions",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        "equipment_emissions",
        ["emission_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_equipment_id"),
        "equipment_emissions",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_id"), "equipment_emissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_emissions_is_current"),
        "equipment_emissions",
        ["is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_power_factor_id"),
        "equipment_emissions",
        ["power_factor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_equipment_emissions_power_factor_id"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_is_current"), table_name="equipment_emissions"
    )
    op.drop_index(op.f("ix_equipment_emissions_id"), table_name="equipment_emissions")
    op.drop_index(
        op.f("ix_equipment_emissions_equipment_id"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        table_name="equipment_emissions",
    )
    op.drop_index(
        op.f("ix_equipment_emissions_computed_at"), table_name="equipment_emissions"
    )
    op.drop_table("equipment_emissions")
    op.drop_index(op.f("ix_equipment_updated_by"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_unit_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_status"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_power_factor_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_name"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_equipment_class"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_created_by"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_cost_center"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_category"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_power_factors_version"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_category"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_id"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_equipment_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_created_by"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_category"), table_name="power_factors")
    op.drop_table("power_factors")
    op.drop_index(op.f("ix_emission_factors_version"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_region"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_id"), table_name="emission_factors")
    op.drop_index(
        op.f("ix_emission_factors_factor_name"), table_name="emission_factors"
    )
    op.drop_index(op.f("ix_emission_factors_created_by"), table_name="emission_factors")
    op.drop_table("emission_factors")
    # ### end Alembic commands ###
