"""add_roles_raw

Revision ID: 1b1c61ba2434
Revises: 85ec568657c7
Create Date: 2025-12-10 16:09:35.113719

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1b1c61ba2434"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "85ec568657c7"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("roles_raw", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles_raw")
    # ### end Alembic commands ###
