"""add_cf_field_to_unit

Revision ID: 85ec568657c7
Revises: c8fafadc86ed
Create Date: 2025-12-10 11:43:05.008277

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85ec568657c7"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "c8fafadc86ed"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units", sa.Column("cf", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "cf")
    # ### end Alembic commands ###
