# codeql[py/unused-global-variable]
"""drop is_conversion column from factors

Revision ID: 0367f025e8d8
Revises: e396374f077a
Create Date: 2026-03-16 13:33:28.944918

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "0367f025e8d8"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "e396374f077a"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_factors_is_conversion"), table_name="factors")
    op.drop_column("factors", "is_conversion")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "factors",
        sa.Column("is_conversion", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.create_index(
        op.f("ix_factors_is_conversion"), "factors", ["is_conversion"], unique=False
    )
    # ### end Alembic commands ###
