# codeql[py/unused-global-variable]
"""Add scrop and drop category for data_entry_emissions

Revision ID: 77d68705722a
Revises: 91ea7e3ff1ee
Create Date: 2026-02-27 14:13:44.969961

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "77d68705722a"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "b1e2f3a4d5c6"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_crm_report_type_status",
        "carbon_report_modules",
        ["carbon_report_id", "module_type_id", "status"],
        unique=False,
    )
    op.add_column(
        "data_entry_emissions", sa.Column("scope", sa.Integer(), nullable=True)
    )
    op.drop_column("data_entry_emissions", "subcategory")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_entry_emissions",
        sa.Column("subcategory", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("data_entry_emissions", "scope")
    op.drop_index("idx_crm_report_type_status", table_name="carbon_report_modules")
    # ### end Alembic commands ###
