# codeql[py/unused-global-variable]
"""timestamptz for four naive columns

Revision ID: e88e9dc9e75e
Revises: 128d2947054c
Create Date: 2026-09-25 14:05:39.899718

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e88e9dc9e75e"  # noqa: F841
down_revision: str | Sequence[str] | None = "128d2947054c"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # The timestamp -> timestamptz cast reads stored values in the session
    # TimeZone; pin UTC so no row shifts, and (PG 12+) so no table rewrite.
    op.execute("SET LOCAL TIME ZONE 'UTC'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_documents",
        "changed_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "audit_documents",
        "synced_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_login",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "year_configuration",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # The timestamp -> timestamptz cast reads stored values in the session
    # TimeZone; pin UTC so no row shifts, and (PG 12+) so no table rewrite.
    op.execute("SET LOCAL TIME ZONE 'UTC'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "year_configuration",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "last_login",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_documents",
        "synced_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=True,
    )
    op.alter_column(
        "audit_documents",
        "changed_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
