# codeql[py/unused-global-variable]
"""what did I miss

Revision ID: c0384764d161
Revises: d90884a395e1
Create Date: 2026-06-02 13:43:12.815371

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]



# revision identifiers, used by Alembic.
revision: str = 'c0384764d161' # noqa: F841
down_revision: Union[str, Sequence[str], None] = 'd90884a395e1' # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None # noqa: F841
depends_on: Union[str, Sequence[str], None] = None # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_aggregation_active'), table_name='data_ingestion_jobs', postgresql_where="(((job_type)::text = 'aggregation'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])))")
    op.drop_index(op.f('uq_emission_recalc_active'), table_name='data_ingestion_jobs', postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL))")
    op.drop_index(op.f('uq_factor_identity'), table_name='factors', postgresql_where='(year IS NOT NULL)')
    op.drop_index(op.f('uq_factor_identity_no_year'), table_name='factors', postgresql_where='(year IS NULL)')
    op.drop_index(op.f('ix_locations_keywords'), table_name='locations', postgresql_ops={'keywords': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_pipelines_module_year'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_status'), table_name='pipelines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pipelines_status'), 'pipelines', ['status'], unique=False)
    op.create_index(op.f('ix_pipelines_module_year'), 'pipelines', ['module_type_id', 'year'], unique=False)
    op.create_index(op.f('ix_locations_keywords'), 'locations', ['keywords'], unique=False, postgresql_ops={'keywords': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('uq_factor_identity_no_year'), 'factors', ['data_entry_type_id', 'emission_type_id', sa.literal_column('(classification::text)')], unique=True, postgresql_where='(year IS NULL)')
    op.create_index(op.f('uq_factor_identity'), 'factors', ['data_entry_type_id', 'year', 'emission_type_id', sa.literal_column('(classification::text)')], unique=True, postgresql_where='(year IS NOT NULL)')
    op.create_index(op.f('uq_emission_recalc_active'), 'data_ingestion_jobs', ['module_type_id', 'data_entry_type_id', 'year'], unique=True, postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL))")
    op.create_index(op.f('uq_aggregation_active'), 'data_ingestion_jobs', ['module_type_id', 'year'], unique=True, postgresql_where="(((job_type)::text = 'aggregation'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])))")
    # ### end Alembic commands ###
