"""remove default role for unit_user table

Revision ID: 5737a979a0e6
Revises: merged_travel_001
Create Date: 2026-01-16 15:12:04.272290

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5737a979a0e6"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "merged_travel_001"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_inventory_unit_id_year"), "inventory", type_="unique")
    op.alter_column(
        "professional_travel_emissions",
        "calculation_inputs",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_id"),
        "professional_travel_emissions",
        ["id"],
        unique=False,
    )
    op.alter_column(
        "professional_travels",
        "origin_location_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "professional_travels",
        "destination_location_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_index(
        op.f("ix_professional_travels_traveler_id"), table_name="professional_travels"
    )
    op.drop_index(
        op.f("ix_professional_travels_unit_id_year"), table_name="professional_travels"
    )

    ### revmore server default
    op.alter_column(
        "unit_users",
        "role",
        server_default=None,
        existing_type=sa.String(),  # or sqlmodel.sql.sqltypes.AutoString() if needed
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    """Restore server_default to role column in unit_users table."""
    op.alter_column(
        "unit_users",
        "role",
        server_default="co2.user.std",
        # or "calco2.user.standard" if you updated the default
        existing_type=sa.String(),
        existing_nullable=False,
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_professional_travels_unit_id_year"),
        "professional_travels",
        ["unit_id", "year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_traveler_id"),
        "professional_travels",
        ["traveler_id"],
        unique=False,
    )
    op.alter_column(
        "professional_travels",
        "destination_location_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        "professional_travels",
        "origin_location_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_id"),
        table_name="professional_travel_emissions",
    )
    op.alter_column(
        "professional_travel_emissions",
        "calculation_inputs",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
        existing_server_default=sa.text("'{}'::json"),
    )
    op.create_unique_constraint(
        op.f("uq_inventory_unit_id_year"),
        "inventory",
        ["unit_id", "year"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
