# codeql[py/unused-global-variable]
"""initial migration

Revision ID: c825ea9cacc7
Revises:
Create Date: 2026-01-22 13:50:03.818215

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

# revision identifiers, used by Alembic.
revision: str = "c825ea9cacc7"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = None  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emission_factors",
        sa.Column("factor_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("region", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("factor_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emission_factors_created_by"),
        "emission_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_factor_name"),
        "emission_factors",
        ["factor_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_id"), "emission_factors", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_region"), "emission_factors", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_version"),
        "emission_factors",
        ["version"],
        unique=False,
    )
    op.create_table(
        "emission_types",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_emission_types_code"), "emission_types", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_emission_types_id"), "emission_types", ["id"], unique=False
    )
    op.create_table(
        "headcounts",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column(
            "unit_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("cf", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "cf_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "cf_user_id", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "display_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "status", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column(
            "function", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("sciper", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("fte", sa.Float(), nullable=False),
        sa.Column("submodule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column(
            "provider_source",
            sa.Enum("api", "csv", "manual", name="ingestion_method_enum"),
            nullable=False,
        ),
        sa.Column(
            "function_role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_headcounts_created_by"), "headcounts", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_headcounts_sciper"), "headcounts", ["sciper"], unique=False
    )
    op.create_index(
        op.f("ix_headcounts_submodule"), "headcounts", ["submodule"], unique=False
    )
    op.create_index(
        op.f("ix_headcounts_unit_id"), "headcounts", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_headcounts_updated_by"), "headcounts", ["updated_by"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "transport_mode",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "iata_code", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column(
            "countrycode", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_locations_countrycode"), "locations", ["countrycode"], unique=False
    )
    op.create_index(
        op.f("ix_locations_created_by"), "locations", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_locations_iata_code"), "locations", ["iata_code"], unique=False
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=False)
    op.create_index(
        op.f("ix_locations_transport_mode"),
        "locations",
        ["transport_mode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_updated_by"), "locations", ["updated_by"], unique=False
    )
    op.create_table(
        "module_types",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_module_types_id"), "module_types", ["id"], unique=False)
    op.create_index(op.f("ix_module_types_name"), "module_types", ["name"], unique=True)
    op.create_table(
        "plane_impact_factors",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "factor_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "category", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("impact_score", sa.Float(), nullable=False),
        sa.Column("rfi_adjustment", sa.Float(), nullable=False),
        sa.Column("min_distance", sa.Float(), nullable=True),
        sa.Column("max_distance", sa.Float(), nullable=True),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plane_impact_factors_category"),
        "plane_impact_factors",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plane_impact_factors_created_by"),
        "plane_impact_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plane_impact_factors_factor_type"),
        "plane_impact_factors",
        ["factor_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plane_impact_factors_updated_by"),
        "plane_impact_factors",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "power_factors",
        sa.Column("submodule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sub_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "equipment_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("sub_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("active_power_w", sa.Float(), nullable=False),
        sa.Column("standby_power_w", sa.Float(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("power_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_power_factors_created_by"),
        "power_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_power_factors_equipment_class"),
        "power_factors",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(op.f("ix_power_factors_id"), "power_factors", ["id"], unique=False)
    op.create_index(
        op.f("ix_power_factors_sub_category"),
        "power_factors",
        ["sub_category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_power_factors_sub_class"), "power_factors", ["sub_class"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_submodule"), "power_factors", ["submodule"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_version"), "power_factors", ["version"], unique=False
    )
    op.create_table(
        "train_impact_factors",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "countrycode", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False
        ),
        sa.Column("impact_score", sa.Float(), nullable=False),
        sa.Column("valid_from", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("valid_to", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("source", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_train_impact_factors_countrycode"),
        "train_impact_factors",
        ["countrycode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_train_impact_factors_created_by"),
        "train_impact_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_train_impact_factors_updated_by"),
        "train_impact_factors",
        ["updated_by"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("roles_raw", sa.JSON(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("function", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_provider_code"), "users", ["provider_code"], unique=True
    )
    op.create_table(
        "data_entry_types",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("module_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_entry_types_id"), "data_entry_types", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_data_entry_types_module_type_id"),
        "data_entry_types",
        ["module_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_types_name"), "data_entry_types", ["name"], unique=False
    )
    op.create_table(
        "data_ingestion_jobs",
        sa.Column(
            "entity_type",
            sa.Enum(
                "ALL_USERS",
                "ALL_UNITS",
                "MODULE_PER_YEAR",
                "MODULE_UNIT_SPECIFIC",
                name="entity_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("module_type_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "target_type",
            sa.Enum("DATA_ENTRIES", "FACTORS", name="target_type_enum"),
            nullable=True,
        ),
        sa.Column(
            "ingestion_method",
            sa.Enum("api", "csv", "manual", name="ingestion_method_enum"),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                name="ingestion_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("status_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "equipment",
        sa.Column("cost_center", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "cost_center_description", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("submodule", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "equipment_class", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("sub_class", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("service_date", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active_usage_pct", sa.Float(), nullable=True),
        sa.Column("passive_usage_pct", sa.Float(), nullable=True),
        sa.Column("power_factor_id", sa.Integer(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("equipment_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("created_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("updated_by", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_equipment_category"), "equipment", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_cost_center"), "equipment", ["cost_center"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_created_by"), "equipment", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_equipment_class"),
        "equipment",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_index(op.f("ix_equipment_name"), "equipment", ["name"], unique=False)
    op.create_index(
        op.f("ix_equipment_power_factor_id"),
        "equipment",
        ["power_factor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_equipment_status"), "equipment", ["status"], unique=False)
    op.create_index(
        op.f("ix_equipment_submodule"), "equipment", ["submodule"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_unit_id"), "equipment", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_updated_by"), "equipment", ["updated_by"], unique=False
    )
    op.create_table(
        "professional_travels",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "traveler_name",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
        sa.Column("origin_location_id", sa.Integer(), nullable=False),
        sa.Column("destination_location_id", sa.Integer(), nullable=False),
        sa.Column("departure_date", sa.Date(), nullable=True),
        sa.Column("is_round_trip", sa.Boolean(), nullable=False),
        sa.Column(
            "transport_mode",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=False,
        ),
        sa.Column("class", sa.String(length=50), nullable=True),
        sa.Column("number_of_trips", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("traveler_id", sa.Integer(), nullable=True),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column(
            "provider_source",
            sa.Enum("api", "csv", "manual", name="ingestion_method_enum"),
            nullable=False,
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_professional_travels_created_by"),
        "professional_travels",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_destination_location_id"),
        "professional_travels",
        ["destination_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_origin_location_id"),
        "professional_travels",
        ["origin_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_unit_id"),
        "professional_travels",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_updated_by"),
        "professional_travels",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_year"),
        "professional_travels",
        ["year"],
        unique=False,
    )
    op.create_table(
        "units",
        sa.Column("provider_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "principal_user_provider_code",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("cost_centers", sa.JSON(), nullable=True),
        sa.Column("affiliations", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["principal_user_provider_code"],
            ["users.provider_code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_id"), "units", ["id"], unique=False)
    op.create_index(op.f("ix_units_name"), "units", ["name"], unique=False)
    op.create_index(
        op.f("ix_units_principal_user_provider_code"),
        "units",
        ["principal_user_provider_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_units_provider_code"), "units", ["provider_code"], unique=True
    )
    op.create_table(
        "carbon_reports",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carbon_reports_unit_id"), "carbon_reports", ["unit_id"], unique=False
    )
    op.create_table(
        "equipment_emissions",
        sa.Column("equipment_id", sa.Integer(), nullable=False),
        sa.Column("annual_kwh", sa.Float(), nullable=False),
        sa.Column("kg_co2eq", sa.Float(), nullable=False),
        sa.Column("emission_factor_id", sa.Integer(), nullable=False),
        sa.Column("power_factor_id", sa.Integer(), nullable=True),
        sa.Column(
            "formula_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("computed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("calculation_inputs", sa.JSON(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["emission_factor_id"],
            ["emission_factors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_equipment_emissions_computed_at"),
        "equipment_emissions",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        "equipment_emissions",
        ["emission_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_equipment_id"),
        "equipment_emissions",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_id"), "equipment_emissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_emissions_is_current"),
        "equipment_emissions",
        ["is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_power_factor_id"),
        "equipment_emissions",
        ["power_factor_id"],
        unique=False,
    )
    op.create_table(
        "factors",
        sa.Column("emission_type_id", sa.Integer(), nullable=False),
        sa.Column("is_conversion", sa.Boolean(), nullable=False),
        sa.Column("data_entry_type_id", sa.Integer(), nullable=True),
        sa.Column("classification", sa.JSON(), nullable=True),
        sa.Column("values", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_entry_type_id"],
            ["data_entry_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["emission_type_id"],
            ["emission_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_factors_data_entry_type_id"),
        "factors",
        ["data_entry_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factors_emission_type_id"),
        "factors",
        ["emission_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_factors_id"), "factors", ["id"], unique=False)
    op.create_index(
        op.f("ix_factors_is_conversion"), "factors", ["is_conversion"], unique=False
    )
    op.create_table(
        "professional_travel_emissions",
        sa.Column("professional_travel_id", sa.Integer(), nullable=False),
        sa.Column("distance_km", sa.Float(), nullable=False),
        sa.Column("kg_co2eq", sa.Float(), nullable=False),
        sa.Column("plane_impact_factor_id", sa.Integer(), nullable=True),
        sa.Column("train_impact_factor_id", sa.Integer(), nullable=True),
        sa.Column(
            "formula_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("computed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("calculation_inputs", sa.JSON(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plane_impact_factor_id"],
            ["plane_impact_factors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["professional_travel_id"],
            ["professional_travels.id"],
        ),
        sa.ForeignKeyConstraint(
            ["train_impact_factor_id"],
            ["train_impact_factors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_computed_at"),
        "professional_travel_emissions",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_id"),
        "professional_travel_emissions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_is_current"),
        "professional_travel_emissions",
        ["is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_plane_impact_factor_id"),
        "professional_travel_emissions",
        ["plane_impact_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_professional_travel_id"),
        "professional_travel_emissions",
        ["professional_travel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_train_impact_factor_id"),
        "professional_travel_emissions",
        ["train_impact_factor_id"],
        unique=False,
    )
    op.create_table(
        "unit_users",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CO2_USER_STD",
                "CO2_USER_PRINCIPAL",
                "CO2_BACKOFFICE_METIER",
                "CO2_SUPERADMIN",
                name="role_name_enum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("unit_id", "user_id"),
    )
    op.create_index(op.f("ix_unit_users_role"), "unit_users", ["role"], unique=False)
    op.create_table(
        "carbon_report_modules",
        sa.Column("module_type_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("carbon_report_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carbon_report_id"],
            ["carbon_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carbon_report_modules_carbon_report_id"),
        "carbon_report_modules",
        ["carbon_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_report_modules_module_type_id"),
        "carbon_report_modules",
        ["module_type_id"],
        unique=False,
    )
    op.create_table(
        "data_entries",
        sa.Column("data_entry_type_id", sa.Integer(), nullable=True),
        sa.Column("carbon_report_module_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carbon_report_module_id"],
            ["carbon_report_modules.id"],
        ),
        sa.ForeignKeyConstraint(
            ["data_entry_type_id"],
            ["data_entry_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_entries_carbon_report_module_id"),
        "data_entries",
        ["carbon_report_module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entries_data_entry_type_id"),
        "data_entries",
        ["data_entry_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_data_entries_id"), "data_entries", ["id"], unique=False)
    op.create_table(
        "data_entry_emissions",
        sa.Column("data_entry_id", sa.Integer(), nullable=False),
        sa.Column("emission_type_id", sa.Integer(), nullable=False),
        sa.Column("primary_factor_id", sa.Integer(), nullable=True),
        sa.Column("subcategory", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("kg_co2eq", sa.Float(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("formula_version", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("computed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_entry_id"],
            ["data_entries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["emission_type_id"],
            ["emission_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["primary_factor_id"],
            ["factors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_entry_emissions_computed_at"),
        "data_entry_emissions",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_emissions_data_entry_id"),
        "data_entry_emissions",
        ["data_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_emissions_emission_type_id"),
        "data_entry_emissions",
        ["emission_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_emissions_id"), "data_entry_emissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_data_entry_emissions_primary_factor_id"),
        "data_entry_emissions",
        ["primary_factor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_entry_emissions_primary_factor_id"),
        table_name="data_entry_emissions",
    )
    op.drop_index(op.f("ix_data_entry_emissions_id"), table_name="data_entry_emissions")
    op.drop_index(
        op.f("ix_data_entry_emissions_emission_type_id"),
        table_name="data_entry_emissions",
    )
    op.drop_index(
        op.f("ix_data_entry_emissions_data_entry_id"), table_name="data_entry_emissions"
    )
    op.drop_index(
        op.f("ix_data_entry_emissions_computed_at"), table_name="data_entry_emissions"
    )
    op.drop_table("data_entry_emissions")
    op.drop_index(op.f("ix_data_entries_id"), table_name="data_entries")
    op.drop_index(op.f("ix_data_entries_data_entry_type_id"), table_name="data_entries")
    op.drop_index(
        op.f("ix_data_entries_carbon_report_module_id"), table_name="data_entries"
    )
    op.drop_table("data_entries")
    op.drop_index(
        op.f("ix_carbon_report_modules_module_type_id"),
        table_name="carbon_report_modules",
    )
    op.drop_index(
        op.f("ix_carbon_report_modules_carbon_report_id"),
        table_name="carbon_report_modules",
    )
    op.drop_table("carbon_report_modules")
    op.drop_index(op.f("ix_unit_users_role"), table_name="unit_users")
    op.drop_table("unit_users")
    op.drop_index(
        op.f("ix_professional_travel_emissions_train_impact_factor_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_professional_travel_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_plane_impact_factor_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_is_current"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_computed_at"),
        table_name="professional_travel_emissions",
    )
    op.drop_table("professional_travel_emissions")
    op.drop_index(op.f("ix_factors_is_conversion"), table_name="factors")
    op.drop_index(op.f("ix_factors_id"), table_name="factors")
    op.drop_index(op.f("ix_factors_emission_type_id"), table_name="factors")
    op.drop_index(op.f("ix_factors_data_entry_type_id"), table_name="factors")
    op.drop_table("factors")
    op.drop_index(
        op.f("ix_equipment_emissions_power_factor_id"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_is_current"), table_name="equipment_emissions"
    )
    op.drop_index(op.f("ix_equipment_emissions_id"), table_name="equipment_emissions")
    op.drop_index(
        op.f("ix_equipment_emissions_equipment_id"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        table_name="equipment_emissions",
    )
    op.drop_index(
        op.f("ix_equipment_emissions_computed_at"), table_name="equipment_emissions"
    )
    op.drop_table("equipment_emissions")
    op.drop_index(op.f("ix_carbon_reports_unit_id"), table_name="carbon_reports")
    op.drop_table("carbon_reports")
    op.drop_index(op.f("ix_units_provider_code"), table_name="units")
    op.drop_index(op.f("ix_units_principal_user_provider_code"), table_name="units")
    op.drop_index(op.f("ix_units_name"), table_name="units")
    op.drop_index(op.f("ix_units_id"), table_name="units")
    op.drop_table("units")
    op.drop_index(
        op.f("ix_professional_travels_year"), table_name="professional_travels"
    )
    op.drop_index(
        op.f("ix_professional_travels_updated_by"), table_name="professional_travels"
    )
    op.drop_index(
        op.f("ix_professional_travels_unit_id"), table_name="professional_travels"
    )
    op.drop_index(
        op.f("ix_professional_travels_origin_location_id"),
        table_name="professional_travels",
    )
    op.drop_index(
        op.f("ix_professional_travels_destination_location_id"),
        table_name="professional_travels",
    )
    op.drop_index(
        op.f("ix_professional_travels_created_by"), table_name="professional_travels"
    )
    op.drop_table("professional_travels")
    op.drop_index(op.f("ix_equipment_updated_by"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_unit_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_submodule"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_status"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_power_factor_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_name"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_equipment_class"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_created_by"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_cost_center"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_category"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_table("data_ingestion_jobs")
    op.drop_index(op.f("ix_data_entry_types_name"), table_name="data_entry_types")
    op.drop_index(
        op.f("ix_data_entry_types_module_type_id"), table_name="data_entry_types"
    )
    op.drop_index(op.f("ix_data_entry_types_id"), table_name="data_entry_types")
    op.drop_table("data_entry_types")
    op.drop_index(op.f("ix_users_provider_code"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_train_impact_factors_updated_by"), table_name="train_impact_factors"
    )
    op.drop_index(
        op.f("ix_train_impact_factors_created_by"), table_name="train_impact_factors"
    )
    op.drop_index(
        op.f("ix_train_impact_factors_countrycode"), table_name="train_impact_factors"
    )
    op.drop_table("train_impact_factors")
    op.drop_index(op.f("ix_power_factors_version"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_submodule"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_category"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_id"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_equipment_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_created_by"), table_name="power_factors")
    op.drop_table("power_factors")
    op.drop_index(
        op.f("ix_plane_impact_factors_updated_by"), table_name="plane_impact_factors"
    )
    op.drop_index(
        op.f("ix_plane_impact_factors_factor_type"), table_name="plane_impact_factors"
    )
    op.drop_index(
        op.f("ix_plane_impact_factors_created_by"), table_name="plane_impact_factors"
    )
    op.drop_index(
        op.f("ix_plane_impact_factors_category"), table_name="plane_impact_factors"
    )
    op.drop_table("plane_impact_factors")
    op.drop_index(op.f("ix_module_types_name"), table_name="module_types")
    op.drop_index(op.f("ix_module_types_id"), table_name="module_types")
    op.drop_table("module_types")
    op.drop_index(op.f("ix_locations_updated_by"), table_name="locations")
    op.drop_index(op.f("ix_locations_transport_mode"), table_name="locations")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_index(op.f("ix_locations_iata_code"), table_name="locations")
    op.drop_index(op.f("ix_locations_created_by"), table_name="locations")
    op.drop_index(op.f("ix_locations_countrycode"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_headcounts_updated_by"), table_name="headcounts")
    op.drop_index(op.f("ix_headcounts_unit_id"), table_name="headcounts")
    op.drop_index(op.f("ix_headcounts_submodule"), table_name="headcounts")
    op.drop_index(op.f("ix_headcounts_sciper"), table_name="headcounts")
    op.drop_index(op.f("ix_headcounts_created_by"), table_name="headcounts")
    op.drop_table("headcounts")
    op.drop_index(op.f("ix_emission_types_id"), table_name="emission_types")
    op.drop_index(op.f("ix_emission_types_code"), table_name="emission_types")
    op.drop_table("emission_types")
    op.drop_index(op.f("ix_emission_factors_version"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_region"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_id"), table_name="emission_factors")
    op.drop_index(
        op.f("ix_emission_factors_factor_name"), table_name="emission_factors"
    )
    op.drop_index(op.f("ix_emission_factors_created_by"), table_name="emission_factors")
    op.drop_table("emission_factors")
    # ### end Alembic commands ###
