# codeql[py/unused-global-variable]
"""narrow emission recalc dedup index to unscoped children

Revision ID: 3f254df7a368
Revises: 095d98bc390c
Create Date: 2026-08-30 14:15:01.841982

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "3f254df7a368"  # noqa: F841
down_revision: str | Sequence[str] | None = "095d98bc390c"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_emission_recalc_active"),
        table_name="data_ingestion_jobs",
        postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL))",
    )
    op.create_index(
        "uq_emission_recalc_active_unscoped",
        "data_ingestion_jobs",
        ["module_type_id", "data_entry_type_id", "year"],
        unique=True,
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL AND meta -> 'config' -> 'carbon_report_module_ids' IS NULL"
        ),
    )
    # ### end Alembic commands ###

    # Raw SQL rather than op.create_index: the scoped half keys on an
    # *expression* (a json->jsonb cast, because ``meta`` is ``json`` and
    # json has no btree equality operator), which autogenerate does not
    # emit.  Kept byte-identical to the model's Index(...) declaration.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_emission_recalc_active_scoped
        ON data_ingestion_jobs (
            module_type_id, data_entry_type_id, year,
            ((meta -> 'config' -> 'carbon_report_module_ids')::jsonb)
        )
        WHERE job_type = 'emission_recalc'
          AND state IN (
              'NOT_STARTED'::ingestion_state_enum,
              'QUEUED'::ingestion_state_enum,
              'RUNNING'::ingestion_state_enum
          )
          AND module_type_id IS NOT NULL
          AND data_entry_type_id IS NOT NULL
          AND year IS NOT NULL
          AND meta -> 'config' -> 'carbon_report_module_ids' IS NOT NULL
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS uq_emission_recalc_active_scoped")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_emission_recalc_active_unscoped",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL AND meta -> 'config' -> 'carbon_report_module_ids' IS NULL"
        ),
    )
    op.create_index(
        op.f("uq_emission_recalc_active"),
        "data_ingestion_jobs",
        ["module_type_id", "data_entry_type_id", "year"],
        unique=True,
        postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL))",
    )
    # ### end Alembic commands ###
