# codeql[py/unused-global-variable]
"""Add new audit table

Revision ID: 082fb33fe0bf
Revises: e56b52f2d555
Create Date: 2026-02-12 13:37:41.506832

"""

from typing import Sequence, Union

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "082fb33fe0bf"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "e56b52f2d555"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
