# codeql[py/unused-global-variable]
"""new schema for unit

Revision ID: 98f3d3379ecf
Revises: 68212d566ed9
Create Date: 2026-02-25 14:28:19.103908

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "98f3d3379ecf"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "68212d566ed9"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units",
        sa.Column(
            "institutional_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "parent_institutional_code",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "path_institutional_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "path_institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "principal_user_institutional_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_units_cost_center"), table_name="units")
    op.drop_index(op.f("ix_units_parent_id"), table_name="units")
    op.drop_index(op.f("ix_units_path_provider_code"), table_name="units")
    op.drop_index(op.f("ix_units_principal_user_provider_code"), table_name="units")
    op.drop_index(op.f("ix_units_provider_code"), table_name="units")
    op.create_index(
        op.f("ix_units_institutional_code"),
        "units",
        ["institutional_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_units_institutional_id"), "units", ["institutional_id"], unique=True
    )
    op.create_index(
        op.f("ix_units_parent_institutional_code"),
        "units",
        ["parent_institutional_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_units_path_institutional_code"),
        "units",
        ["path_institutional_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_units_principal_user_institutional_id"),
        "units",
        ["principal_user_institutional_id"],
        unique=False,
    )
    op.drop_column("units", "parent_id")
    op.drop_column("units", "path_cost_center")
    op.drop_column("units", "principal_user_provider_code")
    op.drop_column("units", "path_provider_code")
    op.drop_column("units", "cost_center")
    op.drop_column("units", "provider_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units",
        sa.Column("provider_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "units",
        sa.Column("cost_center", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "units",
        sa.Column(
            "path_provider_code", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "principal_user_provider_code",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "units",
        sa.Column("path_cost_center", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "units",
        sa.Column("parent_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_units_principal_user_institutional_id"), table_name="units")
    op.drop_index(op.f("ix_units_path_institutional_code"), table_name="units")
    op.drop_index(op.f("ix_units_parent_institutional_code"), table_name="units")
    op.drop_index(op.f("ix_units_institutional_id"), table_name="units")
    op.drop_index(op.f("ix_units_institutional_code"), table_name="units")
    op.create_index(
        op.f("ix_units_provider_code"), "units", ["provider_code"], unique=True
    )
    op.create_index(
        op.f("ix_units_principal_user_provider_code"),
        "units",
        ["principal_user_provider_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_units_path_provider_code"),
        "units",
        ["path_provider_code"],
        unique=False,
    )
    op.create_index(op.f("ix_units_parent_id"), "units", ["parent_id"], unique=False)
    op.create_index(op.f("ix_units_cost_center"), "units", ["cost_center"], unique=True)
    op.drop_column("units", "principal_user_institutional_id")
    op.drop_column("units", "path_institutional_id")
    op.drop_column("units", "path_institutional_code")
    op.drop_column("units", "parent_institutional_code")
    op.drop_column("units", "institutional_id")
    op.drop_column("units", "institutional_code")
    # ### end Alembic commands ###
