# codeql[py/unused-global-variable]
"""remove emission_type_table

Revision ID: b65a2c4e120f
Revises: f1916906dd42
Create Date: 2026-01-28 14:35:49.583782

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "b65a2c4e120f"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "f1916906dd42"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("data_entry_emissions_emission_type_id_fkey"),
        "data_entry_emissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("factors_emission_type_id_fkey"), "factors", type_="foreignkey"
    )
    op.drop_index(op.f("ix_emission_types_code"), table_name="emission_types")
    op.drop_index(op.f("ix_emission_types_id"), table_name="emission_types")
    op.drop_table("emission_types")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("factors_emission_type_id_fkey"),
        "factors",
        "emission_types",
        ["emission_type_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("data_entry_emissions_emission_type_id_fkey"),
        "data_entry_emissions",
        "emission_types",
        ["emission_type_id"],
        ["id"],
    )
    op.create_table(
        "emission_types",
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("emission_types_pkey")),
    )
    op.create_index(
        op.f("ix_emission_types_id"), "emission_types", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emission_types_code"), "emission_types", ["code"], unique=True
    )
    # ### end Alembic commands ###
