# codeql[py/unused-global-variable]
"""add distance_km and weight_kg to data_entry_emissions

Revision ID: 0bf6b8778dd9
Revises: 4226efc73854
Create Date: 2026-04-24 13:28:43.442879

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "0bf6b8778dd9"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "4226efc73854"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_entry_emissions",
        sa.Column("distance_km", sa.Float(), nullable=True),
    )
    op.add_column(
        "data_entry_emissions",
        sa.Column("weight_kg", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_entry_emissions", "weight_kg")
    op.drop_column("data_entry_emissions", "distance_km")
    # ### end Alembic commands ###
