# codeql[py/unused-global-variable]
"""remove purchase description

Revision ID: 30c096280772
Revises: a7b2f8c1d3e6
Create Date: 2026-05-13 15:15:06.594682

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "30c096280772"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "a7b2f8c1d3e6"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


_agg_where = (
    "(((job_type)::text = 'aggregation'::text) AND (state = ANY ("
    "ARRAY['NOT_STARTED'::ingestion_state_enum, "
    "'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])))"
)
_recalc_where = (
    "(((job_type)::text = 'emission_recalc'::text) AND (state = ANY ("
    "ARRAY['NOT_STARTED'::ingestion_state_enum, "
    "'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) "
    "AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) "
    "AND (year IS NOT NULL))"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_aggregation_active"),
        table_name="data_ingestion_jobs",
        postgresql_where=_agg_where,
    )
    op.drop_index(
        op.f("uq_emission_recalc_active"),
        table_name="data_ingestion_jobs",
        postgresql_where=_recalc_where,
    )
    op.drop_index(
        op.f("uq_factor_identity"),
        table_name="factors",
        postgresql_where="(year IS NOT NULL)",
    )
    op.drop_index(
        op.f("uq_factor_identity_no_year"),
        table_name="factors",
        postgresql_where="(year IS NULL)",
    )
    op.drop_index(
        op.f("ix_locations_keywords"),
        table_name="locations",
        postgresql_ops={"keywords": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_locations_keywords"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_ops={"keywords": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        op.f("uq_factor_identity_no_year"),
        "factors",
        [
            "data_entry_type_id",
            "emission_type_id",
            sa.literal_column("(classification::text)"),
        ],
        unique=True,
        postgresql_where="(year IS NULL)",
    )
    op.create_index(
        op.f("uq_factor_identity"),
        "factors",
        [
            "data_entry_type_id",
            "year",
            "emission_type_id",
            sa.literal_column("(classification::text)"),
        ],
        unique=True,
        postgresql_where="(year IS NOT NULL)",
    )
    op.create_index(
        op.f("uq_emission_recalc_active"),
        "data_ingestion_jobs",
        ["module_type_id", "data_entry_type_id", "year"],
        unique=True,
        postgresql_where=_recalc_where,
    )
    op.create_index(
        op.f("uq_aggregation_active"),
        "data_ingestion_jobs",
        ["module_type_id", "year"],
        unique=True,
        postgresql_where=_agg_where,
    )
    # ### end Alembic commands ###
