# codeql[py/unused-global-variable]
"""add year column and indexes to factors

Revision ID: e396374f077a
Revises: 635bf41ace00
Create Date: 2026-03-16 13:12:27.302531

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "e396374f077a"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "635bf41ace00"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("data_entries_unique_member_uid_per_module_idx"),
        table_name="data_entries",
        postgresql_where=(
            "((data_entry_type_id = 1) AND "
            "((data ->> 'user_institutional_id'::text) IS NOT NULL))"
        ),
    )
    op.add_column("factors", sa.Column("year", sa.Integer(), nullable=True))
    op.create_index(
        "ix_factors_data_entry_type_year",
        "factors",
        ["data_entry_type_id", "year"],
        unique=False,
    )
    op.create_index("ix_factors_year", "factors", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_factors_year", table_name="factors")
    op.drop_index("ix_factors_data_entry_type_year", table_name="factors")
    op.drop_column("factors", "year")
    op.create_index(
        op.f("data_entries_unique_member_uid_per_module_idx"),
        "data_entries",
        [
            "carbon_report_module_id",
            sa.literal_column("(data ->> 'user_institutional_id'::text)"),
        ],
        unique=True,
        postgresql_where=(
            "((data_entry_type_id = 1) AND "
            "((data ->> 'user_institutional_id'::text) IS NOT NULL))"
        ),
    )
    # ### end Alembic commands ###
