# codeql[py/unused-global-variable]
"""drop fk for parent_id

Revision ID: 7e0dc4acb886
Revises: aaaea3d89dc4
Create Date: 2026-02-25 11:22:22.752859

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "7e0dc4acb886"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "aaaea3d89dc4"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("units_parent_id_fkey"), "units", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("units_parent_id_fkey"), "units", "units", ["parent_id"], ["id"]
    )
    # ### end Alembic commands ###
