# codeql[py/unused-global-variable]
"""rename provider code to new institutional_id

Revision ID: 635bf41ace00
Revises: f1a2b3c4d5e6
Create Date: 2026-03-11 13:02:24.799215

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "635bf41ace00"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "ab12cd34ef56"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    op.drop_index(op.f("ix_users_provider_code"), table_name="users")
    op.create_index(
        op.f("ix_users_institutional_id"), "users", ["institutional_id"], unique=True
    )
    op.drop_column("users", "provider_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("provider_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_users_institutional_id"), table_name="users")
    op.create_index(
        op.f("ix_users_provider_code"), "users", ["provider_code"], unique=True
    )
    op.drop_column("users", "institutional_id")
    # ### end Alembic commands ###
