# codeql[py/unused-global-variable]
"""add new index for carbon_report_module

Revision ID: ca66012820ff
Revises: 65234a80a387
Create Date: 2026-02-20 16:31:36.323400

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "ca66012820ff"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "65234a80a387"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_crm_report_type_status",
        "carbon_report_modules",
        ["carbon_report_id", "module_type_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_crm_report_type_status", table_name="carbon_report_modules")
    # ### end Alembic commands ###
