# codeql[py/unused-global-variable]
"""use SyncStatusEnum properly

Revision ID: af2c356f7307
Revises: ead72853a03c
Create Date: 2026-02-18 14:20:23.035821

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "af2c356f7307"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "ead72853a03c"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "audit_documents",
        "sync_error",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_audit_documents_sync_status"), table_name="audit_documents")
    op.drop_index(op.f("ix_audit_documents_synced_at"), table_name="audit_documents")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_audit_documents_synced_at"),
        "audit_documents",
        ["synced_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_documents_sync_status"),
        "audit_documents",
        ["sync_status"],
        unique=False,
    )
    op.alter_column(
        "audit_documents",
        "sync_error",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
