# codeql[py/unused-global-variable]
"""drop unused table

Revision ID: 455dff14eee3
Revises: add_icu_collations
Create Date: 2026-01-26 12:58:44.493117

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "455dff14eee3"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "add_icu_collations"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # Drop foreign key constraints referencing power_factors
    op.drop_constraint(
        "equipment_power_factor_id_fkey", "equipment", type_="foreignkey"
    )
    op.drop_constraint(
        "equipment_emissions_power_factor_id_fkey",
        "equipment_emissions",
        type_="foreignkey",
    )
    # .equipment_emissions_equipment_id_fkey drop
    op.drop_constraint(
        "equipment_emissions_equipment_id_fkey",
        "equipment_emissions",
        type_="foreignkey",
    )
    # drop modules_variant_type_id_fkey
    op.drop_constraint("modules_variant_type_id_fkey", "modules", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_power_factors_created_by"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_equipment_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_id"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_category"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_submodule"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_version"), table_name="power_factors")
    op.drop_table("power_factors")
    op.drop_index(op.f("ix_equipment_category"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_cost_center"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_created_by"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_equipment_class"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_name"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_power_factor_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_status"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_submodule"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_unit_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_updated_by"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_variant_types_id"), table_name="variant_types")
    op.drop_index(op.f("ix_variant_types_module_type_id"), table_name="variant_types")
    op.drop_index(op.f("ix_variant_types_name"), table_name="variant_types")
    op.drop_table("variant_types")
    op.drop_index(
        op.f("ix_equipment_emissions_computed_at"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        table_name="equipment_emissions",
    )
    op.drop_index(
        op.f("ix_equipment_emissions_equipment_id"), table_name="equipment_emissions"
    )
    op.drop_index(op.f("ix_equipment_emissions_id"), table_name="equipment_emissions")
    op.drop_index(
        op.f("ix_equipment_emissions_is_current"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_power_factor_id"), table_name="equipment_emissions"
    )
    op.drop_table("equipment_emissions")
    op.drop_index(op.f("ix_emission_factors_created_by"), table_name="emission_factors")
    op.drop_index(
        op.f("ix_emission_factors_factor_name"), table_name="emission_factors"
    )
    op.drop_index(op.f("ix_emission_factors_id"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_region"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_version"), table_name="emission_factors")
    op.drop_table("emission_factors")
    op.drop_index(op.f("ix_modules_carbon_report_module_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_module_type_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_variant_type_id"), table_name="modules")
    op.drop_table("modules")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "modules",
        sa.Column("module_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("variant_type_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "carbon_report_module_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["carbon_report_module_id"],
            ["carbon_report_modules.id"],
            name=op.f("modules_carbon_report_module_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
            name=op.f("modules_module_type_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_type_id"],
            ["variant_types.id"],
            name=op.f("modules_variant_type_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("modules_pkey")),
    )
    op.create_index(
        op.f("ix_modules_variant_type_id"), "modules", ["variant_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_modules_module_type_id"), "modules", ["module_type_id"], unique=False
    )
    op.create_index(op.f("ix_modules_id"), "modules", ["id"], unique=False)
    op.create_index(
        op.f("ix_modules_carbon_report_module_id"),
        "modules",
        ["carbon_report_module_id"],
        unique=False,
    )
    op.create_table(
        "emission_factors",
        sa.Column("factor_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "valid_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valid_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "factor_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('emission_factors_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="emission_factors_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_emission_factors_version"),
        "emission_factors",
        ["version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_region"), "emission_factors", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_id"), "emission_factors", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_factor_name"),
        "emission_factors",
        ["factor_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_created_by"),
        "emission_factors",
        ["created_by"],
        unique=False,
    )
    op.create_table(
        "equipment_emissions",
        sa.Column("equipment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "annual_kwh",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "kg_co2eq",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "emission_factor_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("power_factor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("formula_version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "calculation_inputs",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["emission_factor_id"],
            ["emission_factors.id"],
            name=op.f("equipment_emissions_emission_factor_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("equipment_emissions_equipment_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
            name=op.f("equipment_emissions_power_factor_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("equipment_emissions_pkey")),
    )
    op.create_index(
        op.f("ix_equipment_emissions_power_factor_id"),
        "equipment_emissions",
        ["power_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_is_current"),
        "equipment_emissions",
        ["is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_id"), "equipment_emissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_emissions_equipment_id"),
        "equipment_emissions",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        "equipment_emissions",
        ["emission_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_computed_at"),
        "equipment_emissions",
        ["computed_at"],
        unique=False,
    )
    op.create_table(
        "variant_types",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("module_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
            name=op.f("variant_types_module_type_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("variant_types_pkey")),
    )
    op.create_index(
        op.f("ix_variant_types_name"), "variant_types", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_variant_types_module_type_id"),
        "variant_types",
        ["module_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_variant_types_id"), "variant_types", ["id"], unique=False)
    op.create_table(
        "equipment",
        sa.Column("cost_center", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cost_center_description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("submodule", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("equipment_class", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sub_class", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "service_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "active_usage_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "passive_usage_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("power_factor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("unit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "equipment_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
            name=op.f("equipment_power_factor_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("equipment_pkey")),
    )
    op.create_index(
        op.f("ix_equipment_updated_by"), "equipment", ["updated_by"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_unit_id"), "equipment", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_submodule"), "equipment", ["submodule"], unique=False
    )
    op.create_index(op.f("ix_equipment_status"), "equipment", ["status"], unique=False)
    op.create_index(
        op.f("ix_equipment_power_factor_id"),
        "equipment",
        ["power_factor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_equipment_name"), "equipment", ["name"], unique=False)
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_index(
        op.f("ix_equipment_equipment_class"),
        "equipment",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_created_by"), "equipment", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_cost_center"), "equipment", ["cost_center"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_category"), "equipment", ["category"], unique=False
    )
    op.create_table(
        "power_factors",
        sa.Column("submodule", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sub_category", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("equipment_class", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sub_class", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "active_power_w",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "standby_power_w",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "valid_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valid_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "power_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("power_factors_pkey")),
    )
    op.create_index(
        op.f("ix_power_factors_version"), "power_factors", ["version"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_submodule"), "power_factors", ["submodule"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_sub_class"), "power_factors", ["sub_class"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_sub_category"),
        "power_factors",
        ["sub_category"],
        unique=False,
    )
    op.create_index(op.f("ix_power_factors_id"), "power_factors", ["id"], unique=False)
    op.create_index(
        op.f("ix_power_factors_equipment_class"),
        "power_factors",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_power_factors_created_by"),
        "power_factors",
        ["created_by"],
        unique=False,
    )
    # ### end Alembic commands ###
