"""add sync_status fields to audit_documents

Revision ID: 000000000000
Revises: c7d9a1b2e3f4
Create Date: 2026-02-16 17:13:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "000000000000"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "c7d9a1b2e3f4"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type for sync_status
    op.execute(
        "CREATE TYPE sync_status_enum AS ENUM "
        "('PENDING', 'SYNCING', 'SYNCED', 'FAILED')"
    )

    # Add sync_status column
    op.add_column(
        "audit_documents",
        sa.Column(
            "sync_status",
            sa.Enum("PENDING", "SYNCING", "SYNCED", "FAILED", name="sync_status_enum"),
            server_default="PENDING",
            nullable=False,
        ),
    )

    # Add sync_error column
    op.add_column("audit_documents", sa.Column("sync_error", sa.Text(), nullable=True))

    # Add synced_at column
    op.add_column(
        "audit_documents", sa.Column("synced_at", sa.DateTime(), nullable=True)
    )

    # Create indexes for better query performance
    op.create_index(
        "ix_audit_documents_sync_status",
        "audit_documents",
        ["sync_status"],
        unique=False,
    )

    op.create_index(
        "ix_audit_documents_synced_at", "audit_documents", ["synced_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes
    op.drop_index("ix_audit_documents_synced_at", table_name="audit_documents")
    op.drop_index("ix_audit_documents_sync_status", table_name="audit_documents")

    # Drop columns
    op.drop_column("audit_documents", "synced_at")
    op.drop_column("audit_documents", "sync_error")
    op.drop_column("audit_documents", "sync_status")

    # Drop enum type
    op.execute("DROP TYPE sync_status_enum")
    # ### end Alembic commands ###
