"""add unique constraint on inventory

Revision ID: 99bb31e235b5
Revises: 2c84b48e5c19
Create Date: 2026-01-07 10:11:24.220469

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99bb31e235b5"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "2c84b48e5c19"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint on (unit_id, year) to prevent duplicate inventories
    op.create_unique_constraint(
        "uq_inventory_unit_id_year",
        "inventory",
        ["unit_id", "year"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the unique constraint
    op.drop_constraint(
        "uq_inventory_unit_id_year",
        "inventory",
        type_="unique",
    )
    # ### end Alembic commands ###
