"""correct model

Revision ID: 64e4d82217ea
Revises: 82054845b6d4
Create Date: 2026-01-21 15:58:33.104835

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "64e4d82217ea"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "82054845b6d4"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""

    # Ensure 'manual' is present in the enum type (safe for all states)
    op.execute(
        """
        DO $$
        BEGIN
            IF (
                SELECT COUNT(*)
                FROM unnest(enum_range(NULL::ingestion_method_enum))
            ) = 2 THEN
                ALTER TYPE ingestion_method_enum ADD VALUE 'manual';
            END IF;
        END$$;
        """
    )
    # COMMIT so the new enum value is visible to subsequent DDL
    op.execute("COMMIT")

    # Clean up invalid provider values before altering the type
    op.execute(
        """
        UPDATE headcounts
        SET provider = 'DEFAULT'
        WHERE provider NOT IN ('ACCRED', 'DEFAULT', 'TEST')
        """
    )
    op.execute("COMMIT")

    # Now you can safely alter the column type
    op.alter_column(
        "headcounts",
        "provider",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
        nullable=False,
        postgresql_using="provider::user_provider_enum",
    )

    # 2. Add "provider_source" to headcounts with enum default, then remove default
    op.add_column(
        "headcounts",
        sa.Column(
            "provider_source",
            sa.Enum("api", "csv", "manual", name="ingestion_method_enum"),
            nullable=False,
            server_default=sa.text("'manual'::ingestion_method_enum"),
        ),
    )
    op.alter_column("headcounts", "provider_source", server_default=None)

    # 3. Add "provider_source" to professional_travels with enum default,
    # then remove default
    op.add_column(
        "professional_travels",
        sa.Column(
            "provider_source",
            sa.Enum("api", "csv", "manual", name="ingestion_method_enum"),
            nullable=False,
            server_default=sa.text("'manual'::ingestion_method_enum"),
        ),
    )
    op.alter_column("professional_travels", "provider_source", server_default=None)

    # 4. Cast "provider" column (String -> Enum) for headcounts and professional_travels
    op.alter_column(
        "headcounts",
        "provider",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
        nullable=False,
        postgresql_using="provider::user_provider_enum",
    )

    # Clean up invalid provider values in professional_travels before altering the type
    op.execute(
        """
        UPDATE professional_travels
        SET provider = 'DEFAULT'
        WHERE provider NOT IN ('ACCRED', 'DEFAULT', 'TEST')
        """
    )
    op.execute("COMMIT")
    op.alter_column(
        "professional_travels",
        "provider",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
        nullable=False,
        postgresql_using="provider::user_provider_enum",
    )

    # 5. String to Integer conversions for IDs (created_by, updated_by)
    for table in [
        "headcounts",
        "locations",
        "plane_impact_factors",
        "professional_travels",
        "train_impact_factors",
    ]:
        op.alter_column(
            table,
            "created_by",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            postgresql_using="created_by::integer",
        )
        op.alter_column(
            table,
            "updated_by",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            postgresql_using="updated_by::integer",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "units",
        "id",
        existing_type=sa.INTEGER(),
        server_default=sa.Identity(
            always=False,
            start=1,
            increment=1,
            minvalue=1,
            maxvalue=2147483647,
            cycle=False,
            cache=1,
        ),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "train_impact_factors",
        "updated_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "train_impact_factors",
        "created_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "professional_travels",
        "provider",
        existing_type=sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "professional_travels",
        "traveler_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
    )
    op.alter_column(
        "professional_travels",
        "updated_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "professional_travels",
        "created_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("professional_travels", "provider_source")
    op.alter_column(
        "plane_impact_factors",
        "updated_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "plane_impact_factors",
        "created_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "locations",
        "updated_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "locations",
        "created_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "headcounts",
        "provider",
        existing_type=sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
        type_=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.alter_column(
        "headcounts",
        "updated_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "headcounts",
        "created_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.drop_column("headcounts", "provider_source")
    op.alter_column(
        "data_ingestion_jobs",
        "provider",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
        nullable=False,
        # Add this line:
        postgresql_using="provider::user_provider_enum",
    )
    # ### end Alembic commands ###
