# codeql[py/unused-global-variable]
"""change unit structure for tree

Revision ID: 94965a1ded3e
Revises: 2d69661d72fe
Create Date: 2026-02-25 09:52:31.684286

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "94965a1ded3e"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "2d69661d72fe"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_foreign_key(
        None,
        "data_entries",
        "carbon_report_modules",
        ["carbon_report_module_id"],
        ["id"],
    )
    op.create_foreign_key(
        None,
        "data_entry_emissions",
        "data_entries",
        ["data_entry_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "data_entry_emissions",
        "factors",
        ["primary_factor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "units",
        sa.Column("cost_center", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "units",
        sa.Column("label_fr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "units",
        sa.Column("label_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("units", sa.Column("level", sa.Integer(), nullable=False))
    op.add_column("units", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.add_column(
        "units",
        sa.Column(
            "path_provider_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "path_cost_center", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    op.add_column(
        "units",
        sa.Column("path_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("units", sa.Column("unit_type_id", sa.Integer(), nullable=True))
    op.add_column(
        "units",
        sa.Column("unit_type_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("units", sa.Column("is_active", sa.Boolean(), nullable=False))
    op.create_index(op.f("ix_units_cost_center"), "units", ["cost_center"], unique=True)
    op.create_index(op.f("ix_units_level"), "units", ["level"], unique=False)
    op.create_index(op.f("ix_units_parent_id"), "units", ["parent_id"], unique=False)
    op.create_index(
        op.f("ix_units_path_provider_code"),
        "units",
        ["path_provider_code"],
        unique=False,
    )
    op.create_foreign_key(None, "units", "units", ["parent_id"], ["id"])
    op.drop_column("units", "affiliations")
    op.drop_column("units", "cost_centers")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units",
        sa.Column(
            "cost_centers",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "units",
        sa.Column(
            "affiliations",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "units", type_="foreignkey")
    op.drop_index(op.f("ix_units_path_provider_code"), table_name="units")
    op.drop_index(op.f("ix_units_parent_id"), table_name="units")
    op.drop_index(op.f("ix_units_level"), table_name="units")
    op.drop_index(op.f("ix_units_cost_center"), table_name="units")
    op.drop_column("units", "is_active")
    op.drop_column("units", "unit_type_label")
    op.drop_column("units", "unit_type_id")
    op.drop_column("units", "path_name")
    op.drop_column("units", "path_cost_center")
    op.drop_column("units", "path_provider_code")
    op.drop_column("units", "parent_id")
    op.drop_column("units", "level")
    op.drop_column("units", "label_en")
    op.drop_column("units", "label_fr")
    op.drop_column("units", "cost_center")
    op.drop_constraint(None, "data_entry_emissions", type_="foreignkey")
    op.drop_constraint(None, "data_entry_emissions", type_="foreignkey")
    op.drop_constraint(None, "data_entries", type_="foreignkey")

    # ### end Alembic commands ###
