# codeql[py/unused-global-variable]
"""add_is_current_flag

Revision ID: 264ea92016e8
Revises: ace5787ef529
Create Date: 2026-03-23 15:09:14.852859

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "264ea92016e8"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "ace5787ef529"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_ingestion_jobs", sa.Column("is_current", sa.Boolean(), nullable=False)
    )
    op.create_index(
        "ix_data_ingestion_jobs_is_current_unique",
        "data_ingestion_jobs",
        ["module_type_id", "target_type", "year"],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_data_ingestion_jobs_is_current_unique",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text("is_current = true"),
    )
    op.drop_column("data_ingestion_jobs", "is_current")
    # ### end Alembic commands ###
