# codeql[py/unused-global-variable]
"""add simulation carbon reports

Revision ID: 05d68c9a6054
Revises: e528e0d649cd
Create Date: 2026-05-04 09:45:01.440999

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "05d68c9a6054"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "c2d4e6f8a012"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "carbon_projects",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column(
            "carbon_report_type",
            sa.Enum(
                "Calculator",
                "Simulator_Explore",
                "Simulator_Plan",
                name="carbon_report_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_viewable_by_unit_members", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_carbon_projects_end_year"),
        "carbon_projects",
        ["end_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_projects_id"), "carbon_projects", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_carbon_projects_name"), "carbon_projects", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_carbon_projects_start_year"),
        "carbon_projects",
        ["start_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_projects_unit_id"), "carbon_projects", ["unit_id"], unique=False
    )
    op.add_column(
        "carbon_reports", sa.Column("reference_year", sa.Integer(), nullable=True)
    )
    op.add_column(
        "carbon_reports", sa.Column("carbon_project_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        op.f("uq_carbon_reports_unit_year"), "carbon_reports", type_="unique"
    )
    op.create_index(
        op.f("ix_carbon_reports_carbon_project_id"),
        "carbon_reports",
        ["carbon_project_id"],
        unique=False,
    )
    op.create_foreign_key(
        None, "carbon_reports", "carbon_projects", ["carbon_project_id"], ["id"]
    )
    op.create_unique_constraint(
        "uq_carbon_projects_unit_type",
        "carbon_projects",
        ["unit_id", "carbon_report_type"],
    )
    op.create_unique_constraint(
        "uq_carbon_reports_project_year",
        "carbon_reports",
        ["carbon_project_id", "year"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_carbon_reports_project_year", "carbon_reports", type_="unique"
    )
    op.drop_constraint(
        "uq_carbon_projects_unit_type", "carbon_projects", type_="unique"
    )
    op.drop_constraint(None, "carbon_reports", type_="foreignkey")
    op.drop_index(
        op.f("ix_carbon_reports_carbon_project_id"), table_name="carbon_reports"
    )
    op.create_unique_constraint(
        op.f("uq_carbon_reports_unit_year"),
        "carbon_reports",
        ["unit_id", "year"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("carbon_reports", "carbon_project_id")
    op.drop_column("carbon_reports", "reference_year")
    op.drop_index(op.f("ix_carbon_projects_unit_id"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_start_year"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_name"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_id"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_end_year"), table_name="carbon_projects")
    op.drop_table("carbon_projects")
    # ### end Alembic commands ###
