# codeql[py/unused-global-variable]
"""scoped recalc dedup ignores running siblings

Revision ID: 7e026b9941cd
Revises: 3ccb48f25866
Create Date: 2026-09-17 16:54:09.357062

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "7e026b9941cd"  # noqa: F841
down_revision: str | Sequence[str] | None = "3ccb48f25866"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # #2847: RUNNING leaves the scoped index's WHERE, so a unit-specific
    # upload committing behind a running recalc chains a fresh child.
    # (Autogenerate's drop of ix_classification_translations_label_trgm
    # was a false positive and is pruned.)
    op.drop_index(
        op.f("uq_emission_recalc_active_scoped"),
        table_name="data_ingestion_jobs",
        postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL) AND (((meta -> 'config'::text) -> 'carbon_report_module_ids'::text) IS NOT NULL))",
    )
    op.create_index(
        "uq_emission_recalc_active_scoped",
        "data_ingestion_jobs",
        [
            "module_type_id",
            "data_entry_type_id",
            "year",
            sa.literal_column(
                "((meta -> 'config' -> 'carbon_report_module_ids')::jsonb)"
            ),
        ],
        unique=True,
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL AND meta -> 'config' -> 'carbon_report_module_ids' IS NOT NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_emission_recalc_active_scoped",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL AND meta -> 'config' -> 'carbon_report_module_ids' IS NOT NULL"
        ),
    )
    op.create_index(
        op.f("uq_emission_recalc_active_scoped"),
        "data_ingestion_jobs",
        [
            "module_type_id",
            "data_entry_type_id",
            "year",
            sa.literal_column(
                "(((meta -> 'config'::text) -> 'carbon_report_module_ids'::text)::jsonb)"
            ),
        ],
        unique=True,
        postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL) AND (((meta -> 'config'::text) -> 'carbon_report_module_ids'::text) IS NOT NULL))",
    )
    # ### end Alembic commands ###
