# codeql[py/unused-global-variable]
"""search locations

Revision ID: 3f8147b5e516
Revises: e528e0d649cd
Create Date: 2026-05-04 09:52:21.768618

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "3f8147b5e516"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "e528e0d649cd"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add pg_trgm extension if not exists
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        f"CREATE INDEX {op.f('ix_locations_keywords')} ON locations "
        f"USING gin (keywords gin_trgm_ops)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_keywords"), table_name="locations")
    # ### end Alembic commands ###
