# codeql[py/unused-global-variable]
"""update data_ingestion_index

Revision ID: 253e62d79609
Revises: 264ea92016e8
Create Date: 2026-03-24 17:03:06.233151

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "253e62d79609"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "264ea92016e8"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_ingestion_jobs_is_current_unique"),
        table_name="data_ingestion_jobs",
        postgresql_where="(is_current = true)",
    )
    op.create_index(
        "ix_data_ingestion_jobs_is_current_unique",
        "data_ingestion_jobs",
        [
            "module_type_id",
            "data_entry_type_id",
            "target_type",
            "ingestion_method",
            "year",
        ],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_data_ingestion_jobs_is_current_unique",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text("is_current = true"),
    )
    op.create_index(
        op.f("ix_data_ingestion_jobs_is_current_unique"),
        "data_ingestion_jobs",
        ["module_type_id", "target_type", "year"],
        unique=True,
        postgresql_where="(is_current = true)",
    )
    # ### end Alembic commands ###
