# codeql[py/unused-global-variable]
"""add new information for jobs

Revision ID: e528e0d649cd
Revises: 0a1184497886
Create Date: 2026-05-01 10:48:23.480312

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "e528e0d649cd"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "0a1184497886"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_ingestion_jobs",
        sa.Column("locked_by", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "data_ingestion_jobs",
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "data_ingestion_jobs",
        sa.Column(
            "attempts", sa.Integer(), nullable=False, server_default=sa.text("0")
        ),
    )
    op.add_column(
        "data_ingestion_jobs",
        sa.Column(
            "max_attempts", sa.Integer(), nullable=False, server_default=sa.text("3")
        ),
    )
    op.add_column(
        "data_ingestion_jobs",
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "data_ingestion_jobs", sa.Column("pipeline_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "data_ingestion_jobs",
        sa.Column("job_type", sa.String(length=100), nullable=True),
    )
    op.create_index(
        "ix_data_ingestion_jobs_pending",
        "data_ingestion_jobs",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text(
            "state = 'NOT_STARTED'::ingestion_state_enum AND locked_by IS NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_data_ingestion_jobs_pending",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text(
            "state = 'NOT_STARTED'::ingestion_state_enum AND locked_by IS NULL"
        ),
    )
    op.drop_column("data_ingestion_jobs", "job_type")
    op.drop_column("data_ingestion_jobs", "pipeline_id")
    op.drop_column("data_ingestion_jobs", "run_after")
    op.drop_column("data_ingestion_jobs", "max_attempts")
    op.drop_column("data_ingestion_jobs", "attempts")
    op.drop_column("data_ingestion_jobs", "locked_at")
    op.drop_column("data_ingestion_jobs", "locked_by")
    # ### end Alembic commands ###
