# codeql[py/unused-global-variable]
"""add location index not migrated

Revision ID: 5f4b6d37b6f5
Revises: 2cc51f3595ce
Create Date: 2026-02-02 17:08:22.040538

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "5f4b6d37b6f5"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "2cc51f3595ce"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("idx_locations_keywords_de"),
        table_name="locations",
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_keywords_fr"),
        table_name="locations",
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_keywords_it"),
        table_name="locations",
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_municipality_de"),
        table_name="locations",
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_municipality_fr"),
        table_name="locations",
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_municipality_it"),
        table_name="locations",
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.drop_index(op.f("idx_locations_name_de"), table_name="locations")
    op.drop_index(op.f("idx_locations_name_fr"), table_name="locations")
    op.drop_index(op.f("idx_locations_name_it"), table_name="locations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_locations_name_it"), "locations", ["name"], unique=False)
    op.create_index(op.f("idx_locations_name_fr"), "locations", ["name"], unique=False)
    op.create_index(op.f("idx_locations_name_de"), "locations", ["name"], unique=False)
    op.create_index(
        op.f("idx_locations_municipality_it"),
        "locations",
        ["municipality"],
        unique=False,
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_municipality_fr"),
        "locations",
        ["municipality"],
        unique=False,
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_municipality_de"),
        "locations",
        ["municipality"],
        unique=False,
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_keywords_it"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_keywords_fr"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_keywords_de"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_where="(keywords IS NOT NULL)",
    )
    # ### end Alembic commands ###
