# codeql[py/unused-global-variable]
"""Add timestamps to data_entries table

Revision ID: 65234a80a387
Revises: 4bb12eac487e
Create Date: 2026-02-20 16:16:54.790828

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "65234a80a387"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "4bb12eac487e"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_foreign_key(
        None,
        "data_entries",
        "carbon_report_modules",
        ["carbon_report_module_id"],
        ["id"],
    )
    op.create_foreign_key(
        None,
        "data_entry_emissions",
        "factors",
        ["primary_factor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "data_entry_emissions",
        "data_entries",
        ["data_entry_id"],
        ["id"],
        ondelete="CASCADE",
    )

    # Add created_at and updated_at columns to data_entries table
    op.add_column(
        "data_entries",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column(
        "data_entries",
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )

    # Create a trigger function to automatically update updated_at column
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = CURRENT_TIMESTAMP;
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)

    # Create a trigger to automatically update updated_at column on update
    op.execute("""
        CREATE TRIGGER update_data_entries_updated_at 
        BEFORE UPDATE ON data_entries 
        FOR EACH ROW 
        EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the trigger and function for updating updated_at
    op.execute("DROP TRIGGER IF EXISTS update_data_entries_updated_at ON data_entries")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column")

    # Remove the created_at and updated_at columns
    op.drop_column("data_entries", "updated_at")
    op.drop_column("data_entries", "created_at")

    op.drop_constraint(None, "data_entry_emissions", type_="foreignkey")
    op.drop_constraint(None, "data_entry_emissions", type_="foreignkey")

    op.drop_constraint(None, "data_entries", type_="foreignkey")

    # ### end Alembic commands ###
