# codeql[py/unused-global-variable]
"""add new enum for location

Revision ID: 54da9e258bf6
Revises: update_locations_table
Create Date: 2026-02-11 09:53:45.575278

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "54da9e258bf6"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "update_locations_table"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(
        op.f("ix_professional_travel_emissions_computed_at"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_is_current"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_plane_impact_factor_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_professional_travel_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_index(
        op.f("ix_professional_travel_emissions_train_impact_factor_id"),
        table_name="professional_travel_emissions",
    )
    op.drop_table("professional_travel_emissions")
    op.drop_index(
        op.f("ix_train_impact_factors_countrycode"), table_name="train_impact_factors"
    )
    op.drop_index(
        op.f("ix_train_impact_factors_created_by"), table_name="train_impact_factors"
    )
    op.drop_index(
        op.f("ix_train_impact_factors_updated_by"), table_name="train_impact_factors"
    )
    op.drop_table("train_impact_factors")
    op.drop_index(
        op.f("ix_plane_impact_factors_category"), table_name="plane_impact_factors"
    )
    op.drop_index(
        op.f("ix_plane_impact_factors_created_by"), table_name="plane_impact_factors"
    )
    op.drop_index(
        op.f("ix_plane_impact_factors_factor_type"), table_name="plane_impact_factors"
    )
    op.drop_index(
        op.f("ix_plane_impact_factors_updated_by"), table_name="plane_impact_factors"
    )
    op.drop_table("plane_impact_factors")
    op.drop_index(
        op.f("ix_professional_travels_created_by"), table_name="professional_travels"
    )
    op.drop_index(
        op.f("ix_professional_travels_destination_location_id"),
        table_name="professional_travels",
    )
    op.drop_index(
        op.f("ix_professional_travels_origin_location_id"),
        table_name="professional_travels",
    )
    op.drop_index(
        op.f("ix_professional_travels_unit_id"), table_name="professional_travels"
    )
    op.drop_index(
        op.f("ix_professional_travels_updated_by"), table_name="professional_travels"
    )
    op.drop_index(
        op.f("ix_professional_travels_year"), table_name="professional_travels"
    )
    op.drop_table("professional_travels")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "professional_travels",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "traveler_name", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column(
            "origin_location_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "destination_location_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("departure_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column("is_round_trip", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "transport_mode", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("class", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("number_of_trips", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("unit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('professional_travels_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("traveler_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "provider",
            postgresql.ENUM("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "provider_source",
            postgresql.ENUM("api", "csv", "manual", name="ingestion_method_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
            name="professional_travels_destination_location_id_fkey",
        ),
        sa.ForeignKeyConstraint(
            ["origin_location_id"],
            ["locations.id"],
            name="professional_travels_origin_location_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="professional_travels_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_professional_travels_year"),
        "professional_travels",
        ["year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_updated_by"),
        "professional_travels",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_unit_id"),
        "professional_travels",
        ["unit_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_origin_location_id"),
        "professional_travels",
        ["origin_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_destination_location_id"),
        "professional_travels",
        ["destination_location_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travels_created_by"),
        "professional_travels",
        ["created_by"],
        unique=False,
    )
    op.create_table(
        "professional_travel_emissions",
        sa.Column(
            "professional_travel_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "distance_km",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "kg_co2eq",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "plane_impact_factor_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "train_impact_factor_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column("formula_version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "calculation_inputs",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["plane_impact_factor_id"],
            ["plane_impact_factors.id"],
            name=op.f("professional_travel_emissions_plane_impact_factor_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["professional_travel_id"],
            ["professional_travels.id"],
            name=op.f("professional_travel_emissions_professional_travel_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["train_impact_factor_id"],
            ["train_impact_factors.id"],
            name=op.f("professional_travel_emissions_train_impact_factor_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("professional_travel_emissions_pkey")),
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_train_impact_factor_id"),
        "professional_travel_emissions",
        ["train_impact_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_professional_travel_id"),
        "professional_travel_emissions",
        ["professional_travel_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_plane_impact_factor_id"),
        "professional_travel_emissions",
        ["plane_impact_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_is_current"),
        "professional_travel_emissions",
        ["is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_id"),
        "professional_travel_emissions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_professional_travel_emissions_computed_at"),
        "professional_travel_emissions",
        ["computed_at"],
        unique=False,
    )
    op.create_table(
        "plane_impact_factors",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "factor_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "category", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "impact_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "rfi_adjustment",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "min_distance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "max_distance",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "valid_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valid_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("plane_impact_factors_pkey")),
    )
    op.create_index(
        op.f("ix_plane_impact_factors_updated_by"),
        "plane_impact_factors",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plane_impact_factors_factor_type"),
        "plane_impact_factors",
        ["factor_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plane_impact_factors_created_by"),
        "plane_impact_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plane_impact_factors_category"),
        "plane_impact_factors",
        ["category"],
        unique=False,
    )
    op.create_table(
        "train_impact_factors",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "countrycode", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "impact_score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valid_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valid_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("train_impact_factors_pkey")),
    )
    op.create_index(
        op.f("ix_train_impact_factors_updated_by"),
        "train_impact_factors",
        ["updated_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_train_impact_factors_created_by"),
        "train_impact_factors",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_train_impact_factors_countrycode"),
        "train_impact_factors",
        ["countrycode"],
        unique=False,
    )
    # ### end Alembic commands ###
