# codeql[py/unused-global-variable]
"""narrow emission recalc dedup index to unscoped children

Revision ID: 3f254df7a368
Revises: 95fe938000d4
Create Date: 2026-08-30 14:15:01.841982

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "3f254df7a368"  # noqa: F841
down_revision: str | Sequence[str] | None = "95fe938000d4"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_emission_recalc_active"),
        table_name="data_ingestion_jobs",
        postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL))",
    )
    op.create_index(
        "uq_emission_recalc_active_unscoped",
        "data_ingestion_jobs",
        ["module_type_id", "data_entry_type_id", "year"],
        unique=True,
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL AND meta -> 'config' -> 'carbon_report_module_ids' IS NULL"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_emission_recalc_active_unscoped",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL AND meta -> 'config' -> 'carbon_report_module_ids' IS NULL"
        ),
    )
    op.create_index(
        op.f("uq_emission_recalc_active"),
        "data_ingestion_jobs",
        ["module_type_id", "data_entry_type_id", "year"],
        unique=True,
        postgresql_where="(((job_type)::text = 'emission_recalc'::text) AND (state = ANY (ARRAY['NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum])) AND (module_type_id IS NOT NULL) AND (data_entry_type_id IS NOT NULL) AND (year IS NOT NULL))",
    )
    # ### end Alembic commands ###
