"""new data ingestion table

Revision ID: a22aeac3c279
Revises: 5737a979a0e6
Create Date: 2026-01-20 10:48:50.947098

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a22aeac3c279"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "5737a979a0e6"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_ingestion_jobs",
        sa.Column(
            "entity_type",
            sa.Enum(
                "ALL_USERS",
                "ALL_UNITS",
                "MODULE_PER_YEAR",
                "MODULE_UNIT_SPECIFIC",
                name="entity_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("module_type_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "target_type",
            sa.Enum("DATA_ENTRIES", "FACTORS", name="target_type_enum"),
            nullable=True,
        ),
        sa.Column(
            "ingestion_method",
            sa.Enum("api", "csv", name="ingestion_method_enum"),
            nullable=False,
        ),
        sa.Column(
            "provider", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED",
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                name="ingestion_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("status_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_ingestion_jobs")
    # ### end Alembic commands ###
