"""add reporting indexes

Revision ID: 8f5a2b1d4c3e
Revises: ca66012820ff
Create Date: 2026-02-23 11:20:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8f5a2b1d4c3e"
down_revision = "ca66012820ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_carbon_reports_year", "carbon_reports", ["year"], unique=False)
    op.create_index(
        "idx_carbon_report_modules_report",
        "carbon_report_modules",
        ["carbon_report_id"],
        unique=False,
    )
    op.create_index(
        "idx_data_entries_module",
        "data_entries",
        ["carbon_report_module_id"],
        unique=False,
    )
    op.create_index(
        "idx_data_entry_emissions_entry",
        "data_entry_emissions",
        ["data_entry_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_data_entry_emissions_entry", table_name="data_entry_emissions")
    op.drop_index("idx_data_entries_module", table_name="data_entries")
    op.drop_index(
        "idx_carbon_report_modules_report", table_name="carbon_report_modules"
    )
    op.drop_index("idx_carbon_reports_year", table_name="carbon_reports")
    # ### end Alembic commands ###
