# codeql[py/unused-global-variable]
"""add default for status

Revision ID: 6c749d29f53b
Revises: 3c29031f09fc
Create Date: 2026-02-05 04:23:36.167532

"""

from typing import Sequence, Union

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "6c749d29f53b"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "3c29031f09fc"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
