"""empty message

Revision ID: 8b18929d56c9
Revises: 4f065a9509f7
Create Date: 2026-01-22 15:16:35.768175

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b18929d56c9"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "61c5855d3f1c"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # Check if columns exist before adding them (handles auto-created columns)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col["name"] for col in inspector.get_columns("locations")]

    if "airport_size" not in columns:
        op.add_column(
            "locations",
            sa.Column(
                "airport_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True
            ),
        )
    if "continent" not in columns:
        op.add_column(
            "locations",
            sa.Column(
                "continent", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
            ),
        )
    if "countrycode" not in columns:
        op.add_column(
            "locations",
            sa.Column(
                "countrycode", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
            ),
        )
    if "municipality" not in columns:
        op.add_column(
            "locations",
            sa.Column(
                "municipality",
                sqlmodel.sql.sqltypes.AutoString(length=255),
                nullable=True,
            ),
        )
    if "keywords" not in columns:
        op.add_column(
            "locations",
            sa.Column(
                "keywords", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
            ),
        )
    op.alter_column(
        "locations",
        "iata_code",
        existing_type=sa.VARCHAR(length=10),
        type_=sqlmodel.sql.sqltypes.AutoString(length=3),
        existing_nullable=True,
    )
    # Create indexes if they don't exist
    indexes = [idx["name"] for idx in inspector.get_indexes("locations")]
    if "ix_locations_continent" not in indexes:
        op.create_index(
            op.f("ix_locations_continent"), "locations", ["continent"], unique=False
        )
    if "ix_locations_countrycode" not in indexes:
        op.create_index(
            op.f("ix_locations_countrycode"), "locations", ["countrycode"], unique=False
        )
    if "ix_locations_municipality" not in indexes:
        op.create_index(
            op.f("ix_locations_municipality"),
            "locations",
            ["municipality"],
            unique=False,
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_municipality"), table_name="locations")
    op.drop_index(op.f("ix_locations_countrycode"), table_name="locations")
    op.drop_index(op.f("ix_locations_continent"), table_name="locations")
    op.alter_column(
        "locations",
        "iata_code",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=3),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.drop_column("locations", "keywords")
    op.drop_column("locations", "municipality")
    op.drop_column("locations", "countrycode")
    op.drop_column("locations", "continent")
    op.drop_column("locations", "airport_size")
    # ### end Alembic commands ###
