# codeql[py/unused-global-variable]
"""add natural key to locations

Revision ID: 8f29ed82872b
Revises: 1e56d303cc85
Create Date: 2026-05-12 11:16:49.653716

The autogenerated draft also proposed dropping five partial / GIN
indexes that back dedup, factor ``ON CONFLICT`` upserts, and trigram
location search.  Those drops were autogen-noise (alembic cannot
represent partial ``WHERE`` predicates or ``gin_trgm_ops`` via SQLModel
metadata) and have been removed.
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "8f29ed82872b"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "1e56d303cc85"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "locations",
        sa.Column(
            "natural_key",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=False,
        ),
    )
    op.create_index(
        "uq_location_natural_key", "locations", ["natural_key"], unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index("uq_location_natural_key", table_name="locations")
    op.drop_column("locations", "natural_key")
