# codeql[py/unused-global-variable]
"""data_entries.data must not be NULL (NOT VALID check)

Revision ID: c1f2a3b4d5e6
Revises: 1a9837dd65a3
Create Date: 2026-09-10 15:00:00.000000

"""

from collections.abc import Sequence

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "c1f2a3b4d5e6"  # noqa: F841
down_revision: str | Sequence[str] | None = "1a9837dd65a3"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema.

    #2527 C1 made the Simulator Plan prefill copy entries with a server-side
    ``INSERT ... SELECT``. The Python shape it replaced raised on a NULL
    source ``data`` (``{**None}`` is a TypeError), so the job failed loudly.
    SQL propagates instead — ``NULL || jsonb_build_object(...)`` is NULL — so
    the row would copy as NULL and only fail later, per entry, inside a
    recalc that catches and continues. The job would report success while
    those entries priced nothing: the silent-wrong-totals failure the
    guardrails name first, and the same shape as #2546.

    Hand-written rather than autogenerated, deliberately: Alembic emits a
    plain ``CREATE ... CHECK``, and a plain check **validates the whole
    table** under ACCESS EXCLUSIVE. ``data_entries`` carries millions of rows
    on dev, so that is a write outage. ``NOT VALID`` takes a brief lock, no
    scan, and still binds every INSERT and UPDATE from here on — which is all
    that is needed to stop the copy above from writing a NULL.

    Existing NULL rows, if any, are deliberately **left alone and left
    visible**. Rewriting them to ``{}`` would be a silent repair of data
    nobody has looked at, and this is not the change that should decide what
    they mean. Find them with::

        SELECT id, carbon_report_module_id, data_entry_type_id
        FROM data_entries WHERE data IS NULL;

    When that returns nothing, the constraint can be promoted in its own
    migration with ``VALIDATE CONSTRAINT`` — which takes only a SHARE UPDATE
    EXCLUSIVE lock and does not block reads or writes.
    """
    op.execute(
        "ALTER TABLE data_entries "
        "ADD CONSTRAINT ck_data_entries_data_not_null "
        "CHECK (data IS NOT NULL) NOT VALID"
    )
    # Two more holes the NULL check alone does not cover:
    #
    # * SQLAlchemy's JSON type defaults to ``none_as_null=False``, so an ORM
    #   write of ``data=None`` stores the JSON scalar ``null`` — which is not
    #   SQL NULL and passes the check above. ``json_typeof`` rejects it, along
    #   with arrays and scalars.
    # * ``{}`` prices nothing for exactly the same reason a NULL does, and no
    #   handler can produce it: all 26 ``validate_create`` DTOs reject an empty
    #   payload, and every ``DataEntry(...)`` in the app passes real keys.
    #
    # ``data IS NOT NULL`` is repeated deliberately: a CHECK passes when its
    # predicate evaluates to NULL, so without it a SQL NULL would satisfy this
    # constraint too.
    op.execute(
        "ALTER TABLE data_entries "
        "ADD CONSTRAINT ck_data_entries_data_is_non_empty_object "
        "CHECK (data IS NOT NULL "
        "AND json_typeof(data) = 'object' "
        "AND data::jsonb <> '{}'::jsonb) NOT VALID"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "ALTER TABLE data_entries "
        "DROP CONSTRAINT ck_data_entries_data_is_non_empty_object"
    )
    op.execute("ALTER TABLE data_entries DROP CONSTRAINT ck_data_entries_data_not_null")
