# codeql[py/unused-global-variable]
"""add status to data_entries

Revision ID: 3c29031f09fc
Revises: 5f4b6d37b6f5
Create Date: 2026-02-04 10:31:13.317674

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "3c29031f09fc"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "5f4b6d37b6f5"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_entries",
        sa.Column(
            "status",
            sa.Enum("PENDING", "VALIDATED", "REJECTED", name="dataentrystatusenum"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_entries", "status")
    # ### end Alembic commands ###
