# codeql[py/unused-global-variable]
"""explorer sandbox drops year and creator uniqueness

Revision ID: 095d98bc390c
Revises: 4e24903124ff
Create Date: 2026-09-03 12:05:26.958837

"""

from collections.abc import Sequence

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "095d98bc390c"  # noqa: F841
down_revision: str | Sequence[str] | None = "4e24903124ff"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema.

    Drops the Explore-per-creator uniqueness only (#2656): "start
    exploration" now always creates a new sandbox, so it's no longer unique
    per (unit_id, created_by). No data migration needed — a grandfathered
    project with several reports (one per year it was opened under, from
    before this change) self-collapses the next time its owner starts a
    new exploration: create_explore always makes a fresh project, and the
    background cleanup then deletes every older project for that
    (unit, created_by), reports included.

    ``ix_classification_translations_label_trgm`` is autogenerate drift
    (a pg_trgm index not tracked in SQLModel metadata) unrelated to this
    change — pruned per the standing rule.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_carbon_projects_unit_explore_creator"),
        table_name="carbon_projects",
        postgresql_where="(carbon_report_type = 'Simulator_Explore'::carbon_report_type_enum)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uq_carbon_projects_unit_explore_creator"),
        "carbon_projects",
        ["unit_id", "created_by"],
        unique=True,
        postgresql_where="(carbon_report_type = 'Simulator_Explore'::carbon_report_type_enum)",
    )
    # ### end Alembic commands ###
