# codeql[py/unused-global-variable]
"""

Revision ID: 8d5a01072a3a
Revises: 01b45209983b
Create Date: 2026-03-20 14:48:17.779909

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8d5a01072a3a"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "01b45209983b"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "carbon_reports",
        "last_updated",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment=(
            "Timestamp of last update (epoch seconds) - used for concurrency control "
            "and freshness checks - updated automatically on data changes in any child "
            "module - can be null if never updated since creation "
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "carbon_reports",
        "completion_progress",
        existing_type=sa.VARCHAR(length=20),
        comment=None,
        existing_comment=(
            "String representation of completion progress (e.g., '5/7')"
            "modules are completed vs total modules - updated automatically when child "
            "module status changes "
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "carbon_reports",
        "overall_status",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment=(
            "Overall status inferred from child modules: 0=NOT_STARTED  "
            "1=IN_PROGRESS (some but not all modules completed), 2=VALIDATED"
            "validated)"
        ),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "carbon_reports",
        "stats",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=None,
        existing_comment=(
            "Optional JSON field to store pre-calculated statistics for the report - "
            "aggregates stats from all child CarbonReportModule records "
            "totals, by_emission_type, computed_at, entry_count"
            "perf by avoid on-the-fly calculations"
        ),
        existing_nullable=True,
    )
    op.drop_column("data_entry_emissions", "formula_version")
    op.drop_column("data_entry_emissions", "scope")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_entry_emissions",
        sa.Column("formula_version", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "data_entry_emissions",
        sa.Column("scope", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "carbon_reports",
        "stats",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment=(
            "Optional JSON field to store pre-calculated statistics for the report - "
            "aggregates stats from all child CarbonReportModule records "
            "totals, by_emission_type, computed_at, entry_count"
            "perf by avoid on-the-fly calculations"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "carbon_reports",
        "overall_status",
        existing_type=sa.INTEGER(),
        comment=(
            "Overall status inferred from child modules: 0=NOT_STARTED"
            "1=IN_PROGRESS (some but not all modules completed), 2=VALIDATED"
            "validated)"
        ),
        existing_nullable=False,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "carbon_reports",
        "completion_progress",
        existing_type=sa.VARCHAR(length=20),
        comment=(
            "String representation of completion progress (e.g., '5/7')"
            "modules are completed vs total modules - updated automatically when child "
            "module status changes"
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "carbon_reports",
        "last_updated",
        existing_type=sa.INTEGER(),
        comment=(
            "Timestamp of last update (epoch seconds) - used for concurrency control "
            "and freshness checks - updated automatically on data changes in any child "
            "module - can be null if never updated since creation"
        ),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
