# codeql[py/unused-global-variable]
"""

Revision ID: 1c4130713868
Revises: b1e2f3a4d5c6
Create Date: 2026-03-02 15:59:34.572551

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c4130713868"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "b1e2f3a4d5c6"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "locations_plane",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("airport_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "continent", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "country_code", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "iata_code", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True
        ),
        sa.Column(
            "municipality", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "keywords", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_locations_plane_continent"),
        "locations_plane",
        ["continent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_plane_country_code"),
        "locations_plane",
        ["country_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_plane_iata_code"),
        "locations_plane",
        ["iata_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_plane_municipality"),
        "locations_plane",
        ["municipality"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_plane_name"), "locations_plane", ["name"], unique=False
    )
    op.create_table(
        "locations_train",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("airport_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "continent", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "country_code", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "iata_code", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True
        ),
        sa.Column(
            "municipality", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "keywords", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_locations_train_continent"),
        "locations_train",
        ["continent"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_train_country_code"),
        "locations_train",
        ["country_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_train_iata_code"),
        "locations_train",
        ["iata_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_train_municipality"),
        "locations_train",
        ["municipality"],
        unique=False,
    )
    op.create_index(
        op.f("ix_locations_train_name"), "locations_train", ["name"], unique=False
    )
    op.drop_index(op.f("ix_locations_continent"), table_name="locations")
    op.drop_index(op.f("ix_locations_country_code"), table_name="locations")
    op.drop_index(op.f("ix_locations_iata_code"), table_name="locations")
    op.drop_index(op.f("ix_locations_municipality"), table_name="locations")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_index(op.f("ix_locations_transport_mode"), table_name="locations")
    op.drop_table("locations")
    op.create_index(
        "idx_crm_report_type_status",
        "carbon_report_modules",
        ["carbon_report_id", "module_type_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_crm_report_type_status", table_name="carbon_report_modules")
    op.create_table(
        "locations",
        sa.Column(
            "transport_mode",
            postgresql.ENUM("plane", "train", name="transportmodeenum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("airport_size", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "latitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "longitude",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "continent", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
        sa.Column(
            "iata_code", sa.VARCHAR(length=3), autoincrement=False, nullable=True
        ),
        sa.Column(
            "municipality", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "keywords", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "country_code", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("locations_pkey")),
    )
    op.create_index(
        op.f("ix_locations_transport_mode"),
        "locations",
        ["transport_mode"],
        unique=False,
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=False)
    op.create_index(
        op.f("ix_locations_municipality"), "locations", ["municipality"], unique=False
    )
    op.create_index(
        op.f("ix_locations_iata_code"), "locations", ["iata_code"], unique=False
    )
    op.create_index(
        op.f("ix_locations_country_code"), "locations", ["country_code"], unique=False
    )
    op.create_index(
        op.f("ix_locations_continent"), "locations", ["continent"], unique=False
    )
    op.drop_index(op.f("ix_locations_train_name"), table_name="locations_train")
    op.drop_index(op.f("ix_locations_train_municipality"), table_name="locations_train")
    op.drop_index(op.f("ix_locations_train_iata_code"), table_name="locations_train")
    op.drop_index(op.f("ix_locations_train_country_code"), table_name="locations_train")
    op.drop_index(op.f("ix_locations_train_continent"), table_name="locations_train")
    op.drop_table("locations_train")
    op.drop_index(op.f("ix_locations_plane_name"), table_name="locations_plane")
    op.drop_index(op.f("ix_locations_plane_municipality"), table_name="locations_plane")
    op.drop_index(op.f("ix_locations_plane_iata_code"), table_name="locations_plane")
    op.drop_index(op.f("ix_locations_plane_country_code"), table_name="locations_plane")
    op.drop_index(op.f("ix_locations_plane_continent"), table_name="locations_plane")
    op.drop_table("locations_plane")
    # ### end Alembic commands ###
