# codeql[py/unused-global-variable]
"""connector connections and datasources

Revision ID: 89c3079e388d
Revises: 954eac6c95da
Create Date: 2026-07-06 21:38:42.748421

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "89c3079e388d"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "954eac6c95da"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "connector_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "connector",
            sa.Enum("EPFL_TABLEAU", name="connector_type_enum"),
            nullable=False,
        ),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("server_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "site_content_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("secret_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "secret_value_encrypted", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("connector"),
    )
    op.create_index(
        op.f("ix_connector_connections_id"),
        "connector_connections",
        ["id"],
        unique=False,
    )
    op.create_table(
        "connector_datasources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.Integer(), nullable=False),
        sa.Column("module_type_id", sa.Integer(), nullable=False),
        sa.Column("data_entry_type_id", sa.Integer(), nullable=True),
        sa.Column("connector_luid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connector_connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_connector_datasources_connection_id"),
        "connector_datasources",
        ["connection_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_datasources_id"),
        "connector_datasources",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_connector_datasources_module_type_id"),
        "connector_datasources",
        ["module_type_id"],
        unique=False,
    )
    # Partial unique index: only one active datasource per module target
    # (module_type_id, data_entry_type_id). Postgres treats each NULL as
    # distinct, so a plain column index would not catch duplicates when
    # data_entry_type_id is NULL (the common case) — coalesce it into the
    # expression instead. Postgres-only (partial index); not created under
    # SQLite test fixtures.
    op.create_index(
        "uq_active_datasource_per_module",
        "connector_datasources",
        ["module_type_id", sa.text("COALESCE(data_entry_type_id, 0)")],
        unique=True,
        postgresql_where=sa.text("is_active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_active_datasource_per_module",
        table_name="connector_datasources",
    )
    op.drop_index(
        op.f("ix_connector_datasources_module_type_id"),
        table_name="connector_datasources",
    )
    op.drop_index(
        op.f("ix_connector_datasources_id"), table_name="connector_datasources"
    )
    op.drop_index(
        op.f("ix_connector_datasources_connection_id"),
        table_name="connector_datasources",
    )
    op.drop_table("connector_datasources")
    op.drop_index(
        op.f("ix_connector_connections_id"), table_name="connector_connections"
    )
    op.drop_table("connector_connections")
    # Drop the enum type explicitly: SQLAlchemy only auto-drops it when the
    # last column referencing it is dropped via op.drop_column, not when the
    # whole table is dropped with op.drop_table — leaving it orphaned and
    # breaking a clean downgrade -> upgrade round-trip.
    sa.Enum(name="connector_type_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
