# codeql[py/unused-global-variable]
"""remove useless type table

Revision ID: f1916906dd42
Revises: 455dff14eee3
Create Date: 2026-01-27 09:05:03.939494

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f1916906dd42"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "455dff14eee3"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_equipment_emissions_computed_at"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        table_name="equipment_emissions",
    )
    op.drop_index(
        op.f("ix_equipment_emissions_equipment_id"), table_name="equipment_emissions"
    )
    op.drop_index(op.f("ix_equipment_emissions_id"), table_name="equipment_emissions")
    op.drop_index(
        op.f("ix_equipment_emissions_is_current"), table_name="equipment_emissions"
    )
    op.drop_index(
        op.f("ix_equipment_emissions_power_factor_id"), table_name="equipment_emissions"
    )
    op.drop_table("equipment_emissions")
    op.drop_index(op.f("ix_data_entry_types_id"), table_name="data_entry_types")
    op.drop_index(
        op.f("ix_data_entry_types_module_type_id"), table_name="data_entry_types"
    )
    op.drop_index(op.f("ix_data_entry_types_name"), table_name="data_entry_types")
    op.drop_constraint(
        op.f("data_entries_data_entry_type_id_fkey"), "data_entries", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("factors_data_entry_type_id_fkey"), "factors", type_="foreignkey"
    )
    op.drop_table("data_entry_types")
    op.drop_index(op.f("ix_emission_factors_created_by"), table_name="emission_factors")
    op.drop_index(
        op.f("ix_emission_factors_factor_name"), table_name="emission_factors"
    )
    op.drop_index(op.f("ix_emission_factors_id"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_region"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_version"), table_name="emission_factors")
    op.drop_table("emission_factors")
    op.drop_index(op.f("ix_equipment_category"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_cost_center"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_created_by"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_equipment_class"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_name"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_power_factor_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_status"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_submodule"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_unit_id"), table_name="equipment")
    op.drop_index(op.f("ix_equipment_updated_by"), table_name="equipment")
    op.drop_table("equipment")
    op.drop_index(op.f("ix_power_factors_created_by"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_equipment_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_id"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_category"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_sub_class"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_submodule"), table_name="power_factors")
    op.drop_index(op.f("ix_power_factors_version"), table_name="power_factors")
    op.drop_table("power_factors")

    op.alter_column(
        "locations",
        "countrycode",
        existing_type=sa.VARCHAR(length=10),
        type_=sqlmodel.sql.sqltypes.AutoString(length=2),
        existing_nullable=True,
    )
    op.drop_index(
        op.f("idx_locations_keywords_de"),
        table_name="locations",
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_keywords_fr"),
        table_name="locations",
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_keywords_it"),
        table_name="locations",
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_municipality_de"),
        table_name="locations",
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_municipality_fr"),
        table_name="locations",
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.drop_index(
        op.f("idx_locations_municipality_it"),
        table_name="locations",
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.drop_index(op.f("idx_locations_name_de"), table_name="locations")
    op.drop_index(op.f("idx_locations_name_fr"), table_name="locations")
    op.drop_index(op.f("idx_locations_name_it"), table_name="locations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_locations_name_it"), "locations", ["name"], unique=False)
    op.create_index(op.f("idx_locations_name_fr"), "locations", ["name"], unique=False)
    op.create_index(op.f("idx_locations_name_de"), "locations", ["name"], unique=False)
    op.create_index(
        op.f("idx_locations_municipality_it"),
        "locations",
        ["municipality"],
        unique=False,
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_municipality_fr"),
        "locations",
        ["municipality"],
        unique=False,
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_municipality_de"),
        "locations",
        ["municipality"],
        unique=False,
        postgresql_where="(municipality IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_keywords_it"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_keywords_fr"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.create_index(
        op.f("idx_locations_keywords_de"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_where="(keywords IS NOT NULL)",
    )
    op.alter_column(
        "locations",
        "countrycode",
        existing_type=sqlmodel.sql.sqltypes.AutoString(length=2),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.create_foreign_key(
        op.f("factors_data_entry_type_id_fkey"),
        "factors",
        "data_entry_types",
        ["data_entry_type_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("data_entries_data_entry_type_id_fkey"),
        "data_entries",
        "data_entry_types",
        ["data_entry_type_id"],
        ["id"],
    )
    op.create_table(
        "power_factors",
        sa.Column("submodule", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sub_category", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("equipment_class", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sub_class", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "active_power_w",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "standby_power_w",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "valid_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valid_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "power_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('power_factors_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="power_factors_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_power_factors_version"), "power_factors", ["version"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_submodule"), "power_factors", ["submodule"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_sub_class"), "power_factors", ["sub_class"], unique=False
    )
    op.create_index(
        op.f("ix_power_factors_sub_category"),
        "power_factors",
        ["sub_category"],
        unique=False,
    )
    op.create_index(op.f("ix_power_factors_id"), "power_factors", ["id"], unique=False)
    op.create_index(
        op.f("ix_power_factors_equipment_class"),
        "power_factors",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_power_factors_created_by"),
        "power_factors",
        ["created_by"],
        unique=False,
    )
    op.create_table(
        "equipment",
        sa.Column("cost_center", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "cost_center_description", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("submodule", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("equipment_class", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("sub_class", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "service_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "active_usage_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "passive_usage_pct",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("power_factor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("unit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "equipment_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('equipment_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
            name="equipment_power_factor_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="equipment_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_equipment_updated_by"), "equipment", ["updated_by"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_unit_id"), "equipment", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_submodule"), "equipment", ["submodule"], unique=False
    )
    op.create_index(op.f("ix_equipment_status"), "equipment", ["status"], unique=False)
    op.create_index(
        op.f("ix_equipment_power_factor_id"),
        "equipment",
        ["power_factor_id"],
        unique=False,
    )
    op.create_index(op.f("ix_equipment_name"), "equipment", ["name"], unique=False)
    op.create_index(op.f("ix_equipment_id"), "equipment", ["id"], unique=False)
    op.create_index(
        op.f("ix_equipment_equipment_class"),
        "equipment",
        ["equipment_class"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_created_by"), "equipment", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_cost_center"), "equipment", ["cost_center"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_category"), "equipment", ["category"], unique=False
    )
    op.create_table(
        "emission_factors",
        sa.Column("factor_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "value",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "valid_from",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "valid_to",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("region", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("source", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "factor_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('emission_factors_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="emission_factors_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_emission_factors_version"),
        "emission_factors",
        ["version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_region"), "emission_factors", ["region"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_id"), "emission_factors", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_emission_factors_factor_name"),
        "emission_factors",
        ["factor_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_created_by"),
        "emission_factors",
        ["created_by"],
        unique=False,
    )
    op.create_table(
        "data_entry_types",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("module_type_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
            name=op.f("data_entry_types_module_type_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("data_entry_types_pkey")),
    )
    op.create_index(
        op.f("ix_data_entry_types_name"), "data_entry_types", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_data_entry_types_module_type_id"),
        "data_entry_types",
        ["module_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_types_id"), "data_entry_types", ["id"], unique=False
    )
    op.create_table(
        "equipment_emissions",
        sa.Column("equipment_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "annual_kwh",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "kg_co2eq",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "emission_factor_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("power_factor_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("formula_version", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "calculation_inputs",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["emission_factor_id"],
            ["emission_factors.id"],
            name=op.f("equipment_emissions_emission_factor_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"],
            ["equipment.id"],
            name=op.f("equipment_emissions_equipment_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["power_factor_id"],
            ["power_factors.id"],
            name=op.f("equipment_emissions_power_factor_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("equipment_emissions_pkey")),
    )
    op.create_index(
        op.f("ix_equipment_emissions_power_factor_id"),
        "equipment_emissions",
        ["power_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_is_current"),
        "equipment_emissions",
        ["is_current"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_id"), "equipment_emissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_equipment_emissions_equipment_id"),
        "equipment_emissions",
        ["equipment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_emission_factor_id"),
        "equipment_emissions",
        ["emission_factor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_equipment_emissions_computed_at"),
        "equipment_emissions",
        ["computed_at"],
        unique=False,
    )
    # ### end Alembic commands ###
