# codeql[py/unused-global-variable]
"""change to country_code instead of countrycode

Revision ID: e56b52f2d555
Revises: 8871b1a43bfa
Create Date: 2026-02-11 10:28:18.056963

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "e56b52f2d555"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "8871b1a43bfa"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "country_code", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
    )
    op.drop_index(op.f("ix_locations_countrycode"), table_name="locations")
    op.create_index(
        op.f("ix_locations_country_code"), "locations", ["country_code"], unique=False
    )
    op.drop_column("locations", "countrycode")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column(
            "countrycode", sa.VARCHAR(length=2), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_locations_country_code"), table_name="locations")
    op.create_index(
        op.f("ix_locations_countrycode"), "locations", ["countrycode"], unique=False
    )
    op.drop_column("locations", "country_code")
    # ### end Alembic commands ###
