# codeql[py/unused-global-variable]
"""add roles_empty_since for two-strikes deprovisioning (#2539)

Revision ID: 4e24903124ff
Revises: 7bff78de3264
Create Date: 2026-09-02 05:58:20.282154

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "4e24903124ff"  # noqa: F841
down_revision: str | Sequence[str] | None = "7bff78de3264"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # False-positive drop_index on ix_classification_translations_label_trgm
    # pruned — unrelated pre-existing model/DB drift, not part of #2539.
    op.add_column(
        "users",
        sa.Column("roles_empty_since", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "roles_empty_since")
    # ### end Alembic commands ###
