# codeql[py/unused-global-variable]
"""denormalize module key onto data entry emissions

Revision ID: 1a9837dd65a3
Revises: 95fe938000d4
Create Date: 2026-08-30 14:14:40.479942

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "1a9837dd65a3"  # noqa: F841
down_revision: str | Sequence[str] | None = "95fe938000d4"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema.

    Adjusted from the autogenerated form (#2527): autogenerate emits both
    columns as ``nullable=False``, which cannot be added to a populated
    table. Add nullable, backfill from the parent entry, then tighten — one
    migration, because the deploy runs migrations as a gated Job and the DB
    is dropped for this change, so no old pod ever inserts against the
    tightened schema. The index is created last: building it before the
    backfill would index a column about to be fully rewritten.

    The backfill is required, not cosmetic — the DB persists across deploys.
    Any emission whose parent entry is missing would fail SET NOT NULL
    loudly; the FK cascade on data_entry_id means that cannot happen.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_entry_emissions",
        sa.Column("carbon_report_module_id", sa.Integer(), nullable=True),
    )
    op.add_column(
        "data_entry_emissions",
        sa.Column("data_entry_type_id", sa.Integer(), nullable=True),
    )
    op.execute(
        """
        UPDATE data_entry_emissions dee
        SET carbon_report_module_id = de.carbon_report_module_id,
            data_entry_type_id      = de.data_entry_type_id
        FROM data_entries de
        WHERE de.id = dee.data_entry_id
        """
    )
    op.alter_column(
        "data_entry_emissions",
        "carbon_report_module_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.alter_column(
        "data_entry_emissions",
        "data_entry_type_id",
        existing_type=sa.Integer(),
        nullable=False,
    )
    op.create_index(
        "ix_dee_module_type_entry",
        "data_entry_emissions",
        ["carbon_report_module_id", "data_entry_type_id", "data_entry_id"],
        unique=False,
        postgresql_include=[
            "kg_co2eq",
            "emission_type_id",
            "primary_factor_id",
            "scope",
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_dee_module_type_entry",
        table_name="data_entry_emissions",
        postgresql_include=[
            "kg_co2eq",
            "emission_type_id",
            "primary_factor_id",
            "scope",
        ],
    )
    op.drop_column("data_entry_emissions", "data_entry_type_id")
    op.drop_column("data_entry_emissions", "carbon_report_module_id")
    # ### end Alembic commands ###
