"""

Revision ID: 2c84b48e5c19
Revises: seed_module_variant_types
Create Date: 2026-01-06 16:56:19.485330

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c84b48e5c19"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "seed_module_variant_types"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # First convert status strings to integers using raw SQL
    # Map: 'not started' -> 0, 'in progress' -> 1, 'validated' -> 2
    op.execute("""
        ALTER TABLE inventory_module
        ALTER COLUMN status TYPE INTEGER
        USING CASE
            WHEN status IN ('not started', 'not_started', 'default') THEN 0
            WHEN status IN ('in progress', 'in_progress') THEN 1
            WHEN status IN ('validated', 'complete', 'completed') THEN 2
            ELSE 0
        END
    """)

    # Add module_type_id column (nullable first to allow data migration)
    op.add_column(
        "inventory_module", sa.Column("module_type_id", sa.Integer(), nullable=True)
    )

    # Migrate module name to module_type_id
    op.execute("""
        UPDATE inventory_module SET module_type_id = CASE module
            WHEN 'my-lab' THEN 1
            WHEN 'professional-travel' THEN 2
            WHEN 'infrastructure' THEN 3
            WHEN 'equipment-electric-consumption' THEN 4
            WHEN 'purchase' THEN 5
            WHEN 'internal-services' THEN 6
            WHEN 'external-cloud' THEN 7
            ELSE 1
        END
    """)

    # Make module_type_id non-nullable
    op.alter_column(
        "inventory_module", "module_type_id", existing_type=sa.Integer(), nullable=False
    )

    # Add index and foreign key
    op.create_index(
        op.f("ix_inventory_module_module_type_id"),
        "inventory_module",
        ["module_type_id"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_inventory_module_module_type_id",
        "inventory_module",
        "module_types",
        ["module_type_id"],
        ["id"],
    )

    # Drop old module column
    op.drop_column("inventory_module", "module")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "inventory_module",
        sa.Column("module", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "inventory_module", type_="foreignkey")
    op.drop_index(
        op.f("ix_inventory_module_module_type_id"), table_name="inventory_module"
    )
    op.alter_column(
        "inventory_module",
        "status",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("inventory_module", "module_type_id")
    # ### end Alembic commands ###
