# codeql[py/unused-global-variable]
"""seed types

Revision ID: 61c5855d3f1c
Revises: c825ea9cacc7
Create Date: 2026-01-22 13:50:11.404489

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

# revision identifiers, used by Alembic.
revision: str = "61c5855d3f1c"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "c825ea9cacc7"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Seed module_types and variant_types reference data."""
    # ==========================================================================
    # MODULE_TYPES
    # Matching frontend MODULES constant and ModuleTypeId enum
    # ==========================================================================
    op.execute("""
        INSERT INTO module_types (id, name) VALUES
        (1, 'headcount'),
        (2, 'professional-travel'),
        (3, 'infrastructure'),
        (4, 'equipment-electric-consumption'),
        (5, 'purchase'),
        (6, 'internal-services'),
        (7, 'external-cloud'),
        (99, 'global')
        ON CONFLICT (id) DO NOTHING;
    """)

    # ==========================================================================
    # DATA_ENTRY_TYPES
    # Subcategories within each module type
    # ==========================================================================
    op.execute(
        """
        INSERT INTO data_entry_types (id, name, module_type_id) VALUES
        -- MyLab (module_type_id=1) - Headcount variants
        (1, 'member', 1),
        (2, 'student', 1),
        
        -- Equipment (module_type_id=4) - Equipment variants
        (9, 'scientific', 4),
        (10, 'it', 4),
        (11, 'admin', 4),
        
        -- Professional Travel (module_type_id=2) - Travel variants
        (20, 'flight', 2),
        (21, 'train', 2),
        (22, 'car', 2),
        
        -- Infrastructure (module_type_id=3) - Building variants
        (30, 'building', 3),
        
        -- Global/special types for factors
        (100, 'energy_mix', 99)
        ON CONFLICT (id) DO NOTHING;
        """
    )

    # ==========================================================================
    # EMISSION_TYPES
    # Categories for emission calculations
    # Note: 'energy' is a generic conversion type used by emission factors
    # ==========================================================================
    op.execute(
        """
        INSERT INTO emission_types (id, code) VALUES
        (1, 'energy'),
        (2, 'equipment'),
        (3, 'food'),
        (4, 'waste'),
        (5, 'transport'),
        (6, 'grey_energy'),
        (7, 'flight'),
        (8, 'train'),
        (9, 'car')
        """
    )
    # Reset sequences to avoid conflicts with future inserts
    op.execute(
        "SELECT setval('module_types_id_seq', "
        "(SELECT COALESCE(MAX(id), 0) FROM module_types));"
    )
    op.execute(
        "SELECT setval('data_entry_types_id_seq', "
        "(SELECT COALESCE(MAX(id), 0) FROM data_entry_types));"
    )

    op.execute(
        "SELECT setval('emission_types_id_seq', "
        "(SELECT COALESCE(MAX(id), 0) FROM emission_types));"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Remove seeded reference data (only if no FK references exist)."""
    # Delete data_entry_types first (depends on module_types)
    op.execute("""
        DELETE FROM data_entry_types
        WHERE id BETWEEN 1 AND 100
        AND NOT EXISTS (
            SELECT 1 FROM modules WHERE data_entry_type_id = data_entry_types.id
        );
    })""")
    # Delete module_types (only if no references)
    op.execute("""
        DELETE FROM module_types
        WHERE id BETWEEN 1 AND 8
        AND NOT EXISTS (
            SELECT 1 FROM inventory_module WHERE module_type_id = module_types.id
        )
        AND NOT EXISTS (
            SELECT 1 FROM modules WHERE module_type_id = module_types.id
        );
    """)
    # Delete emission_types (only if no references)
    op.execute(
        """
        DELETE FROM emission_types
        WHERE id BETWEEN 1 AND 9
        AND NOT EXISTS (
            SELECT 1 FROM factors WHERE emission_type_id = emission_types.id
        )
        AND NOT EXISTS (
            SELECT 1
            FROM data_entry_emissions
            WHERE emission_type_id = emission_types.id
        );
        """
    )

    # ### end Alembic commands ###
