# codeql[py/unused-global-variable]
"""Add constraint for DataEntryEmission

Revision ID: 23bf7767c44c
Revises: 0320873b1d9d
Create Date: 2026-01-30 16:05:31.642955

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "23bf7767c44c"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "0320873b1d9d"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        None,
        "data_entry_emissions",
        "data_entries",
        ["data_entry_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "data_entry_emissions", type_="foreignkey")
    # ### end Alembic commands ###
