# codeql[py/unused-global-variable]
"""add pod_ip to pods table

Revision ID: a62060da49c0
Revises: ff4f9bac0339
Create Date: 2026-08-21 21:07:39.637371

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "a62060da49c0"  # noqa: F841
down_revision: str | Sequence[str] | None = "ff4f9bac0339"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pods",
        sa.Column("pod_ip", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pods", "pod_ip")
    # ### end Alembic commands ###
