"""add new table logic

Revision ID: ae23fed428b5
Revises: faf90f7d3803
Create Date: 2026-01-06 15:06:22.678822

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae23fed428b5"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "faf90f7d3803"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "module_types",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_module_types_id"), "module_types", ["id"], unique=False)
    op.create_index(op.f("ix_module_types_name"), "module_types", ["name"], unique=True)
    op.create_table(
        "variant_types",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("module_type_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_variant_types_id"), "variant_types", ["id"], unique=False)
    op.create_index(
        op.f("ix_variant_types_module_type_id"),
        "variant_types",
        ["module_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_variant_types_name"), "variant_types", ["name"], unique=False
    )
    op.create_table(
        "modules",
        sa.Column("module_type_id", sa.Integer(), nullable=False),
        sa.Column("variant_type_id", sa.Integer(), nullable=True),
        sa.Column("inventory_module_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inventory_module_id"],
            ["inventory_module.id"],
        ),
        sa.ForeignKeyConstraint(
            ["module_type_id"],
            ["module_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variant_type_id"],
            ["variant_types.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_modules_id"), "modules", ["id"], unique=False)
    op.create_index(
        op.f("ix_modules_inventory_module_id"),
        "modules",
        ["inventory_module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_modules_module_type_id"), "modules", ["module_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_modules_variant_type_id"), "modules", ["variant_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_module_inventory_id"),
        "inventory_module",
        ["inventory_id"],
        unique=False,
    )
    op.add_column(
        "units", sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    op.create_index(op.f("ix_units_code"), "units", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_units_code"), table_name="units")
    op.drop_column("units", "code")
    op.drop_index(
        op.f("ix_inventory_module_inventory_id"), table_name="inventory_module"
    )
    op.drop_index(op.f("ix_modules_variant_type_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_module_type_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_inventory_module_id"), table_name="modules")
    op.drop_index(op.f("ix_modules_id"), table_name="modules")
    op.drop_table("modules")
    op.drop_index(op.f("ix_variant_types_name"), table_name="variant_types")
    op.drop_index(op.f("ix_variant_types_module_type_id"), table_name="variant_types")
    op.drop_index(op.f("ix_variant_types_id"), table_name="variant_types")
    op.drop_table("variant_types")
    op.drop_index(op.f("ix_module_types_name"), table_name="module_types")
    op.drop_index(op.f("ix_module_types_id"), table_name="module_types")
    op.drop_table("module_types")
    # ### end Alembic commands ###
