# codeql[py/unused-global-variable]
"""

Revision ID: dd2ce8461139
Revises:
Create Date: 2026-06-15 13:07:57.987606

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "dd2ce8461139"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = None  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Required by the gin_trgm_ops index on locations.keywords.
    # Autogenerate cannot emit this; see alembic/CUSTOM_DB_OBJECTS.md.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table(
        "audit_documents",
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("data_snapshot", sa.JSON(), nullable=True),
        sa.Column("data_diff", sa.JSON(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "CREATE",
                "READ",
                "UPDATE",
                "DELETE",
                "ROLLBACK",
                "TRANSFER",
                name="audit_change_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("change_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("changed_by", sa.Integer(), nullable=True),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("handler_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("handled_ids", sa.JSON(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("route_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("route_payload", sa.JSON(), nullable=True),
        sa.Column("previous_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "sync_status",
            sa.Enum(
                "PENDING",
                "SYNCING",
                "SYNCED",
                "FAILED",
                "SKIPPED",
                "RETRY_QUEUED",
                name="sync_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("sync_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "audit_document_one_current_idx",
        "audit_documents",
        ["entity_id", "entity_type"],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
    )
    op.create_index(
        op.f("ix_audit_documents_entity_id"),
        "audit_documents",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_documents_entity_type"),
        "audit_documents",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_documents_id"), "audit_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_documents_version"), "audit_documents", ["version"], unique=False
    )
    op.create_table(
        "building_rooms",
        sa.Column(
            "building_location", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("building_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("room_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("room_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("room_surface_square_meter", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_building_rooms_building_location"),
        "building_rooms",
        ["building_location"],
        unique=False,
    )
    op.create_index(
        op.f("ix_building_rooms_building_name"),
        "building_rooms",
        ["building_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_building_rooms_id"), "building_rooms", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_building_rooms_room_name"),
        "building_rooms",
        ["room_name"],
        unique=False,
    )
    op.create_table(
        "locations",
        sa.Column(
            "transport_mode",
            sa.Enum("plane", "train", name="transportmodeenum"),
            nullable=False,
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("airport_size", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "continent", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "country_code", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True
        ),
        sa.Column(
            "iata_code", sqlmodel.sql.sqltypes.AutoString(length=3), nullable=True
        ),
        sa.Column(
            "municipality", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column(
            "keywords", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "natural_key", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_locations_continent"), "locations", ["continent"], unique=False
    )
    op.create_index(
        op.f("ix_locations_country_code"), "locations", ["country_code"], unique=False
    )
    op.create_index(
        op.f("ix_locations_iata_code"), "locations", ["iata_code"], unique=False
    )
    op.create_index(
        "ix_locations_keywords",
        "locations",
        ["keywords"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"keywords": "gin_trgm_ops"},
    )
    op.create_index(
        op.f("ix_locations_municipality"), "locations", ["municipality"], unique=False
    )
    op.create_index(op.f("ix_locations_name"), "locations", ["name"], unique=False)
    op.create_index(
        op.f("ix_locations_transport_mode"),
        "locations",
        ["transport_mode"],
        unique=False,
    )
    op.create_index(
        "uq_location_natural_key", "locations", ["natural_key"], unique=True
    )
    op.create_table(
        "pipelines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=100), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="NOT_STARTED", nullable=False
        ),
        sa.Column("entity_type", sa.Integer(), nullable=True),
        sa.Column("ingestion_method", sa.Integer(), nullable=True),
        sa.Column("module_type_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("expected_recalc", sa.Integer(), nullable=True),
        sa.Column("job_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pipelines_module_year",
        "pipelines",
        ["module_type_id", "year"],
        unique=False,
    )
    op.create_index("ix_pipelines_status", "pipelines", ["status"], unique=False)
    op.create_table(
        "pods",
        sa.Column(
            "pod_id", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False
        ),
        sa.Column(
            "git_sha", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column(
            "app_version", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("pod_id"),
    )
    op.create_table(
        "units",
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column(
            "institutional_code", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("label_fr", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("label_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column(
            "parent_institutional_code",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "parent_institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "path_institutional_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "path_institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("path_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("unit_type_id", sa.Integer(), nullable=True),
        sa.Column("unit_type_label", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "principal_user_institutional_id",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_units_id"), "units", ["id"], unique=False)
    op.create_index(
        op.f("ix_units_institutional_code"),
        "units",
        ["institutional_code"],
        unique=True,
    )
    op.create_index(
        op.f("ix_units_institutional_id"), "units", ["institutional_id"], unique=True
    )
    op.create_index(op.f("ix_units_level"), "units", ["level"], unique=False)
    op.create_index(op.f("ix_units_name"), "units", ["name"], unique=False)
    op.create_index(
        op.f("ix_units_parent_institutional_code"),
        "units",
        ["parent_institutional_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_units_path_institutional_code"),
        "units",
        ["path_institutional_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_units_principal_user_institutional_id"),
        "units",
        ["principal_user_institutional_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("roles_raw", sa.JSON(), nullable=True),
        sa.Column("last_login", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("function", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_roles_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(
        op.f("ix_users_institutional_id"), "users", ["institutional_id"], unique=True
    )
    op.create_table(
        "year_configuration",
        sa.Column("is_started", sa.Boolean(), nullable=False),
        sa.Column("configuration_completed", sa.DateTime(timezone=True), nullable=True),
        sa.Column("config", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("year", "provider"),
    )
    op.create_table(
        "auth_exchange_code",
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(
        op.f("ix_auth_exchange_code_user_id"),
        "auth_exchange_code",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "carbon_projects",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column(
            "carbon_report_type",
            sa.Enum(
                "Calculator",
                "Simulator_Explore",
                "Simulator_Plan",
                name="carbon_report_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("start_year", sa.Integer(), nullable=True),
        sa.Column("end_year", sa.Integer(), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_viewable_by_unit_members", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "unit_id", "carbon_report_type", name="uq_carbon_projects_unit_type"
        ),
    )
    op.create_index(
        op.f("ix_carbon_projects_end_year"),
        "carbon_projects",
        ["end_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_projects_id"), "carbon_projects", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_carbon_projects_name"), "carbon_projects", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_carbon_projects_start_year"),
        "carbon_projects",
        ["start_year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_projects_unit_id"), "carbon_projects", ["unit_id"], unique=False
    )
    op.create_table(
        "data_ingestion_jobs",
        sa.Column(
            "entity_type",
            sa.Enum(
                "MODULE_PER_YEAR",
                "MODULE_UNIT_SPECIFIC",
                "GLOBAL_PER_YEAR",
                name="entity_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("module_type_id", sa.Integer(), nullable=True),
        sa.Column("data_entry_type_id", sa.Integer(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column(
            "target_type",
            sa.Enum(
                "DATA_ENTRIES",
                "FACTORS",
                "REDUCTION_OBJECTIVES",
                "REFERENCE_DATA",
                name="target_type_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "ingestion_method",
            sa.Enum("api", "csv", "manual", "computed", name="ingestion_method_enum"),
            nullable=False,
        ),
        sa.Column(
            "provider",
            sa.Enum("ACCRED", "DEFAULT", "TEST", name="user_provider_enum"),
            nullable=False,
        ),
        sa.Column(
            "state",
            sa.Enum(
                "NOT_STARTED",
                "QUEUED",
                "RUNNING",
                "FINISHED",
                name="ingestion_state_enum",
            ),
            nullable=True,
        ),
        sa.Column(
            "result",
            sa.Enum("SUCCESS", "WARNING", "ERROR", name="ingestion_result_enum"),
            nullable=True,
        ),
        sa.Column("status_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("locked_by", sa.String(length=255), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pipeline_id", sa.UUID(), nullable=True),
        sa.Column("job_type", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["pipelines.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_data_ingestion_jobs_is_current_unique",
        "data_ingestion_jobs",
        [
            "module_type_id",
            "data_entry_type_id",
            "target_type",
            "ingestion_method",
            "year",
        ],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
    )
    op.create_index(
        "ix_data_ingestion_jobs_pending",
        "data_ingestion_jobs",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text(
            "state = 'NOT_STARTED'::ingestion_state_enum AND locked_by IS NULL"
        ),
    )
    op.create_index(
        op.f("ix_data_ingestion_jobs_pipeline_id"),
        "data_ingestion_jobs",
        ["pipeline_id"],
        unique=False,
    )
    op.create_index(
        "uq_aggregation_active",
        "data_ingestion_jobs",
        ["module_type_id", "year"],
        unique=True,
        postgresql_where=sa.text(
            "job_type = 'aggregation' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum)"
        ),
    )
    op.create_index(
        "uq_emission_recalc_active",
        "data_ingestion_jobs",
        ["module_type_id", "data_entry_type_id", "year"],
        unique=True,
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL"
        ),
    )
    op.create_table(
        "unit_users",
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CO2_USER_STD",
                "CO2_USER_PRINCIPAL",
                "CO2_BACKOFFICE_METIER",
                "CO2_SUPERADMIN",
                name="role_name_enum",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("unit_id", "user_id"),
    )
    op.create_index(op.f("ix_unit_users_role"), "unit_users", ["role"], unique=False)
    op.create_table(
        "carbon_reports",
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("reference_year", sa.Integer(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=False),
        sa.Column("carbon_project_id", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.Integer(), nullable=True),
        sa.Column(
            "completion_progress", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("overall_status", sa.Integer(), nullable=False),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carbon_project_id"],
            ["carbon_projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "carbon_project_id", "year", name="uq_carbon_reports_project_year"
        ),
    )
    op.create_index(
        op.f("ix_carbon_reports_carbon_project_id"),
        "carbon_reports",
        ["carbon_project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_reports_unit_id"), "carbon_reports", ["unit_id"], unique=False
    )
    op.create_table(
        "factors",
        sa.Column("emission_type_id", sa.Integer(), nullable=False),
        sa.Column("data_entry_type_id", sa.Integer(), nullable=False),
        sa.Column(
            "classification",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("values", sa.JSON(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_seen_job_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["last_seen_job_id"], ["data_ingestion_jobs.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_factors_data_entry_type_id"),
        "factors",
        ["data_entry_type_id"],
        unique=False,
    )
    op.create_index(
        "ix_factors_data_entry_type_year",
        "factors",
        ["data_entry_type_id", "year"],
        unique=False,
    )
    op.create_index(
        op.f("ix_factors_emission_type_id"),
        "factors",
        ["emission_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_factors_id"), "factors", ["id"], unique=False)
    op.create_index(
        op.f("ix_factors_last_seen_job_id"),
        "factors",
        ["last_seen_job_id"],
        unique=False,
    )
    op.create_index(op.f("ix_factors_year"), "factors", ["year"], unique=False)
    op.create_index(
        "uq_factor_identity",
        "factors",
        [
            "data_entry_type_id",
            "year",
            "emission_type_id",
            sa.literal_column("(classification::text)"),
        ],
        unique=True,
        postgresql_where=sa.text("year IS NOT NULL"),
    )
    op.create_index(
        "uq_factor_identity_no_year",
        "factors",
        [
            "data_entry_type_id",
            "emission_type_id",
            sa.literal_column("(classification::text)"),
        ],
        unique=True,
        postgresql_where=sa.text("year IS NULL"),
    )
    op.create_table(
        "carbon_report_modules",
        sa.Column("module_type_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("carbon_report_id", sa.Integer(), nullable=False),
        sa.Column("last_updated", sa.Integer(), nullable=True),
        sa.Column("stats", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carbon_report_id"],
            ["carbon_reports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "carbon_report_id", "module_type_id", name="uq_carbon_report_module"
        ),
    )
    op.create_index(
        "idx_crm_report_type_status",
        "carbon_report_modules",
        ["carbon_report_id", "module_type_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_report_modules_carbon_report_id"),
        "carbon_report_modules",
        ["carbon_report_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_carbon_report_modules_module_type_id"),
        "carbon_report_modules",
        ["module_type_id"],
        unique=False,
    )
    op.create_table(
        "data_entries",
        sa.Column("data_entry_type_id", sa.Integer(), nullable=False),
        sa.Column("carbon_report_module_id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "VALIDATED", "REJECTED", name="dataentrystatusenum"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("unit_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["carbon_report_module_id"],
            ["carbon_report_modules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_entries_carbon_report_module_id"),
        "data_entries",
        ["carbon_report_module_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entries_created_by_id"),
        "data_entries",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entries_data_entry_type_id"),
        "data_entries",
        ["data_entry_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_data_entries_id"), "data_entries", ["id"], unique=False)
    op.create_index(
        op.f("ix_data_entries_source"), "data_entries", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_data_entries_unit_id"), "data_entries", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_data_entries_year"), "data_entries", ["year"], unique=False
    )
    op.create_table(
        "data_entry_emissions",
        sa.Column("data_entry_id", sa.Integer(), nullable=False),
        sa.Column("emission_type_id", sa.Integer(), nullable=False),
        sa.Column("primary_factor_id", sa.Integer(), nullable=True),
        sa.Column("kg_co2eq", sa.Float(), nullable=False),
        sa.Column(
            "additional_value",
            sa.Float(),
            nullable=True,
            comment="Polymorphic physical quantity tied to this emission row. Unit is inferred from emission_type_id (e.g. km for commuting and travel, kg for food and waste).",
        ),
        sa.Column("scope", sa.Integer(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=True),
        sa.Column("computed_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_entry_id"], ["data_entries.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["primary_factor_id"], ["factors.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_entry_emissions_computed_at"),
        "data_entry_emissions",
        ["computed_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_emissions_data_entry_id"),
        "data_entry_emissions",
        ["data_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_emissions_emission_type_id"),
        "data_entry_emissions",
        ["emission_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_entry_emissions_id"), "data_entry_emissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_data_entry_emissions_primary_factor_id"),
        "data_entry_emissions",
        ["primary_factor_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_data_entry_emissions_primary_factor_id"),
        table_name="data_entry_emissions",
    )
    op.drop_index(op.f("ix_data_entry_emissions_id"), table_name="data_entry_emissions")
    op.drop_index(
        op.f("ix_data_entry_emissions_emission_type_id"),
        table_name="data_entry_emissions",
    )
    op.drop_index(
        op.f("ix_data_entry_emissions_data_entry_id"), table_name="data_entry_emissions"
    )
    op.drop_index(
        op.f("ix_data_entry_emissions_computed_at"), table_name="data_entry_emissions"
    )
    op.drop_table("data_entry_emissions")
    op.drop_index(op.f("ix_data_entries_year"), table_name="data_entries")
    op.drop_index(op.f("ix_data_entries_unit_id"), table_name="data_entries")
    op.drop_index(op.f("ix_data_entries_source"), table_name="data_entries")
    op.drop_index(op.f("ix_data_entries_id"), table_name="data_entries")
    op.drop_index(op.f("ix_data_entries_data_entry_type_id"), table_name="data_entries")
    op.drop_index(op.f("ix_data_entries_created_by_id"), table_name="data_entries")
    op.drop_index(
        op.f("ix_data_entries_carbon_report_module_id"), table_name="data_entries"
    )
    op.drop_table("data_entries")
    op.drop_index(
        op.f("ix_carbon_report_modules_module_type_id"),
        table_name="carbon_report_modules",
    )
    op.drop_index(
        op.f("ix_carbon_report_modules_carbon_report_id"),
        table_name="carbon_report_modules",
    )
    op.drop_index("idx_crm_report_type_status", table_name="carbon_report_modules")
    op.drop_table("carbon_report_modules")
    op.drop_index(
        "uq_factor_identity_no_year",
        table_name="factors",
        postgresql_where=sa.text("year IS NULL"),
    )
    op.drop_index(
        "uq_factor_identity",
        table_name="factors",
        postgresql_where=sa.text("year IS NOT NULL"),
    )
    op.drop_index(op.f("ix_factors_year"), table_name="factors")
    op.drop_index(op.f("ix_factors_last_seen_job_id"), table_name="factors")
    op.drop_index(op.f("ix_factors_id"), table_name="factors")
    op.drop_index(op.f("ix_factors_emission_type_id"), table_name="factors")
    op.drop_index("ix_factors_data_entry_type_year", table_name="factors")
    op.drop_index(op.f("ix_factors_data_entry_type_id"), table_name="factors")
    op.drop_table("factors")
    op.drop_index(op.f("ix_carbon_reports_unit_id"), table_name="carbon_reports")
    op.drop_index(
        op.f("ix_carbon_reports_carbon_project_id"), table_name="carbon_reports"
    )
    op.drop_table("carbon_reports")
    op.drop_index(op.f("ix_unit_users_role"), table_name="unit_users")
    op.drop_table("unit_users")
    op.drop_index(
        "uq_emission_recalc_active",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text(
            "job_type = 'emission_recalc' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum) AND module_type_id IS NOT NULL AND data_entry_type_id IS NOT NULL AND year IS NOT NULL"
        ),
    )
    op.drop_index(
        "uq_aggregation_active",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text(
            "job_type = 'aggregation' AND state IN ('NOT_STARTED'::ingestion_state_enum, 'QUEUED'::ingestion_state_enum, 'RUNNING'::ingestion_state_enum)"
        ),
    )
    op.drop_index(
        op.f("ix_data_ingestion_jobs_pipeline_id"), table_name="data_ingestion_jobs"
    )
    op.drop_index(
        "ix_data_ingestion_jobs_pending",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text(
            "state = 'NOT_STARTED'::ingestion_state_enum AND locked_by IS NULL"
        ),
    )
    op.drop_index(
        "ix_data_ingestion_jobs_is_current_unique",
        table_name="data_ingestion_jobs",
        postgresql_where=sa.text("is_current = true"),
    )
    op.drop_table("data_ingestion_jobs")
    op.drop_index(op.f("ix_carbon_projects_unit_id"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_start_year"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_name"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_id"), table_name="carbon_projects")
    op.drop_index(op.f("ix_carbon_projects_end_year"), table_name="carbon_projects")
    op.drop_table("carbon_projects")
    op.drop_index(
        op.f("ix_auth_exchange_code_user_id"), table_name="auth_exchange_code"
    )
    op.drop_table("auth_exchange_code")
    op.drop_table("year_configuration")
    op.drop_index(op.f("ix_users_institutional_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_units_principal_user_institutional_id"), table_name="units")
    op.drop_index(op.f("ix_units_path_institutional_code"), table_name="units")
    op.drop_index(op.f("ix_units_parent_institutional_code"), table_name="units")
    op.drop_index(op.f("ix_units_name"), table_name="units")
    op.drop_index(op.f("ix_units_level"), table_name="units")
    op.drop_index(op.f("ix_units_institutional_id"), table_name="units")
    op.drop_index(op.f("ix_units_institutional_code"), table_name="units")
    op.drop_index(op.f("ix_units_id"), table_name="units")
    op.drop_table("units")
    op.drop_table("pods")
    op.drop_index("ix_pipelines_status", table_name="pipelines")
    op.drop_index("ix_pipelines_module_year", table_name="pipelines")
    op.drop_table("pipelines")
    op.drop_index("uq_location_natural_key", table_name="locations")
    op.drop_index(op.f("ix_locations_transport_mode"), table_name="locations")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_index(op.f("ix_locations_municipality"), table_name="locations")
    op.drop_index(
        "ix_locations_keywords",
        table_name="locations",
        postgresql_using="gin",
        postgresql_ops={"keywords": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_locations_iata_code"), table_name="locations")
    op.drop_index(op.f("ix_locations_country_code"), table_name="locations")
    op.drop_index(op.f("ix_locations_continent"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_building_rooms_room_name"), table_name="building_rooms")
    op.drop_index(op.f("ix_building_rooms_id"), table_name="building_rooms")
    op.drop_index(op.f("ix_building_rooms_building_name"), table_name="building_rooms")
    op.drop_index(
        op.f("ix_building_rooms_building_location"), table_name="building_rooms"
    )
    op.drop_table("building_rooms")
    op.drop_index(op.f("ix_audit_documents_version"), table_name="audit_documents")
    op.drop_index(op.f("ix_audit_documents_id"), table_name="audit_documents")
    op.drop_index(op.f("ix_audit_documents_entity_type"), table_name="audit_documents")
    op.drop_index(op.f("ix_audit_documents_entity_id"), table_name="audit_documents")
    op.drop_index(
        "audit_document_one_current_idx",
        table_name="audit_documents",
        postgresql_where=sa.text("is_current = true"),
    )
    op.drop_table("audit_documents")
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
