# codeql[py/unused-global-variable]
"""new schema for unit add parent_cf

Revision ID: 91ea7e3ff1ee
Revises: 98f3d3379ecf
Create Date: 2026-02-25 14:47:40.025507

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "91ea7e3ff1ee"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "98f3d3379ecf"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "units",
        sa.Column(
            "parent_institutional_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("units", "parent_institutional_id")
    # ### end Alembic commands ###
