# codeql[py/unused-global-variable]
"""add unique index for audit to avoid race

Revision ID: bb5495fde09c
Revises: 77d68705722a
Create Date: 2026-03-02 20:44:29.314154

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "bb5495fde09c"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "77d68705722a"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "audit_document_one_current_idx",
        "audit_documents",
        ["entity_id", "entity_type"],
        unique=True,
        postgresql_where=sa.text("is_current = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "audit_document_one_current_idx",
        table_name="audit_documents",
        postgresql_where=sa.text("is_current = true"),
    )
    # ### end Alembic commands ###
