"""remove resource

Revision ID: 54db21d2f140
Revises: a22aeac3c279
Create Date: 2026-01-20 17:41:42.223659

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54db21d2f140"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "a22aeac3c279"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_resources_created_by"), table_name="resources")
    op.drop_index(op.f("ix_resources_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_name"), table_name="resources")
    op.drop_index(op.f("ix_resources_unit_id"), table_name="resources")
    op.drop_index(op.f("ix_resources_updated_by"), table_name="resources")
    op.drop_table("resources")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "resources",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("visibility", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "resource_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("unit_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("resources_created_by_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("resources_updated_by_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("resources_pkey")),
    )
    op.create_index(
        op.f("ix_resources_updated_by"), "resources", ["updated_by"], unique=False
    )
    op.create_index(
        op.f("ix_resources_unit_id"), "resources", ["unit_id"], unique=False
    )
    op.create_index(op.f("ix_resources_name"), "resources", ["name"], unique=False)
    op.create_index(op.f("ix_resources_id"), "resources", ["id"], unique=False)
    op.create_index(
        op.f("ix_resources_created_by"), "resources", ["created_by"], unique=False
    )
    # ### end Alembic commands ###
