# codeql[py/unused-global-variable]
"""add last_roles_sync_at to users table

Revision ID: 451937f20b2d
Revises: 4226efc73854
Create Date: 2026-04-28 14:40:08.094924

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "451937f20b2d"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "4226efc73854"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("last_roles_sync_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_roles_sync_at")
    # ### end Alembic commands ###
