# codeql[py/unused-global-variable]
"""add classification_translations table

Revision ID: 42aecc9a8a5b
Revises: 95fe938000d4
Create Date: 2026-08-31 18:05:10.098979

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "42aecc9a8a5b"  # noqa: F841
down_revision: str | Sequence[str] | None = "95fe938000d4"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification_translations",
        sa.Column(
            "field_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "value", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("lang", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column(
            "label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.PrimaryKeyConstraint("field_name", "value", "lang"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classification_translations")
    # ### end Alembic commands ###
