# codeql[py/unused-global-variable]
"""search locations

Revision ID: 3f8147b5e516
Revises: e528e0d649cd
Create Date: 2026-05-04 09:52:21.768618

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "3f8147b5e516"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "e528e0d649cd"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add pg_trgm extension if not exists
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        f"CREATE INDEX {op.f('ix_locations_keywords')} ON locations "
        f"USING gin (keywords gin_trgm_ops)"
    )
    # Drop other indexes and recreate them with trigram for better search performance
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.execute(
        f"CREATE INDEX {op.f('ix_locations_name')} ON locations "
        f"USING gin (name gin_trgm_ops)"
    )
    op.drop_index(op.f("ix_locations_iata_code"), table_name="locations")
    op.execute(
        f"CREATE INDEX {op.f('ix_locations_iata_code')} ON locations "
        f"USING gin (iata_code gin_trgm_ops)"
    )
    op.drop_index(op.f("ix_locations_municipality"), table_name="locations")
    op.execute(
        f"CREATE INDEX {op.f('ix_locations_municipality')} ON locations "
        f"USING gin (municipality gin_trgm_ops)"
    )
    # Remove obsolete collation-based indexes from the previous search strategy.
    op.execute("DROP INDEX IF EXISTS idx_locations_name_fr")
    op.execute("DROP INDEX IF EXISTS idx_locations_name_de")
    op.execute("DROP INDEX IF EXISTS idx_locations_name_it")
    op.execute("DROP INDEX IF EXISTS idx_locations_keywords_fr")
    op.execute("DROP INDEX IF EXISTS idx_locations_keywords_de")
    op.execute("DROP INDEX IF EXISTS idx_locations_keywords_it")
    # Reindex
    op.execute("REINDEX TABLE locations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_locations_keywords"), table_name="locations")
    op.drop_index(op.f("ix_locations_name"), table_name="locations")
    op.drop_index(op.f("ix_locations_iata_code"), table_name="locations")
    op.drop_index(op.f("ix_locations_municipality"), table_name="locations")
    # Recreate original indexes without pg_trgm_ops
    op.execute(f"CREATE INDEX {op.f('ix_locations_name')} ON locations (name)")
    op.execute(
        f"CREATE INDEX {op.f('ix_locations_iata_code')} ON locations (iata_code)"
    )
    op.execute(
        f"CREATE INDEX {op.f('ix_locations_municipality')} ON locations (municipality)"
    )
    # Drop pg_trgm extension if not needed by other parts of the application
    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # Reindex
    op.execute("REINDEX TABLE locations")
    # ### end Alembic commands ###
