"""Rewrite schema for unit and users

Revision ID: fc5cfc45f96e
Revises: 54db21d2f140
Create Date: 2026-01-20 21:06:53.323554
"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers
revision: str = "fc5cfc45f96e"
down_revision: Union[str, Sequence[str], None] = "54db21d2f140"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 1. CREATE POSTGRES ENUM TYPES ---
    user_provider_enum = postgresql.ENUM(
        "ACCRED", "DEFAULT", "TEST", name="user_provider_enum"
    )
    role_name_enum = postgresql.ENUM(
        "CO2_USER_STD",
        "CO2_USER_PRINCIPAL",
        "CO2_BACKOFFICE_METIER",
        "CO2_SUPERADMIN",
        name="role_name_enum",
    )

    user_provider_enum.create(op.get_bind(), checkfirst=True)
    role_name_enum.create(op.get_bind(), checkfirst=True)

    # --- 2. DROP ALL CONSTRAINTS ---
    # We use a try/except or just ensure downgrade works
    # to prevent "UndefinedObject" errors
    op.drop_constraint("unit_users_unit_id_fkey", "unit_users", type_="foreignkey")
    op.drop_constraint("unit_users_user_id_fkey", "unit_users", type_="foreignkey")
    op.drop_constraint(
        "emission_factors_created_by_fkey", "emission_factors", type_="foreignkey"
    )
    op.drop_constraint(
        "power_factors_created_by_fkey", "power_factors", type_="foreignkey"
    )
    op.drop_constraint("equipment_created_by_fkey", "equipment", type_="foreignkey")
    op.drop_constraint("equipment_updated_by_fkey", "equipment", type_="foreignkey")

    # --- 3. UPDATE PRIMARY TABLES & IDENTITY ---
    # Units
    op.add_column("units", sa.Column("provider_code", sa.String(), nullable=False))
    op.add_column(
        "units", sa.Column("principal_user_provider_code", sa.String(), nullable=True)
    )
    op.add_column("units", sa.Column("cost_centers", sa.JSON(), nullable=True))
    op.alter_column("units", "id", type_=sa.Integer(), postgresql_using="id::integer")
    op.execute("ALTER TABLE units ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.alter_column(
        "units",
        "provider",
        type_=user_provider_enum,
        postgresql_using="provider::user_provider_enum",
    )

    # Users
    op.add_column("users", sa.Column("provider_code", sa.String(), nullable=False))
    op.add_column("users", sa.Column("function", sa.String(), nullable=True))
    op.alter_column("users", "id", type_=sa.Integer(), postgresql_using="id::integer")
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")
    op.alter_column(
        "users",
        "provider",
        type_=user_provider_enum,
        postgresql_using="provider::user_provider_enum",
    )

    # Sync sequences so next IDs don't collide
    op.execute(
        "SELECT setval(pg_get_serial_sequence('units', 'id'), "
        "coalesce(max(id), 1), max(id) IS NOT NULL) FROM units"
    )
    op.execute(
        "SELECT setval(pg_get_serial_sequence('users', 'id'), "
        "coalesce(max(id), 1), max(id) IS NOT NULL) FROM users"
    )

    # --- 4. UPDATE REFERENCING TABLES ---
    op.alter_column(
        "unit_users", "unit_id", type_=sa.Integer(), postgresql_using="unit_id::integer"
    )
    op.alter_column(
        "unit_users", "user_id", type_=sa.Integer(), postgresql_using="user_id::integer"
    )
    op.alter_column(
        "unit_users",
        "role",
        type_=role_name_enum,
        postgresql_using="role::role_name_enum",
    )

    op.alter_column(
        "emission_factors",
        "created_by",
        type_=sa.Integer(),
        postgresql_using="created_by::integer",
    )
    op.alter_column(
        "power_factors",
        "created_by",
        type_=sa.Integer(),
        postgresql_using="created_by::integer",
    )
    op.alter_column(
        "equipment",
        "created_by",
        type_=sa.Integer(),
        postgresql_using="created_by::integer",
    )
    op.alter_column(
        "equipment",
        "updated_by",
        type_=sa.Integer(),
        postgresql_using="updated_by::integer",
    )

    # --- 5. CLEANUP COLUMNS ---
    for col in [
        "updated_at",
        "code",
        "created_at",
        "principal_user_email",
        "principal_user_function",
        "principal_user_id",
        "updated_by",
        "visibility",
        "principal_user_name",
        "created_by",
        "cf",
    ]:
        op.drop_column("units", col)
    for col in ["updated_at", "created_at", "is_active", "updated_by", "created_by"]:
        op.drop_column("users", col)

    # --- 6. RECREATE CONSTRAINTS & INDEXES ---
    op.create_index(
        op.f("ix_units_provider_code"), "units", ["provider_code"], unique=True
    )
    op.create_index(
        op.f("ix_users_provider_code"), "users", ["provider_code"], unique=True
    )

    op.create_foreign_key(
        "unit_users_unit_id_fkey", "unit_users", "units", ["unit_id"], ["id"]
    )
    op.create_foreign_key(
        "unit_users_user_id_fkey", "unit_users", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "emission_factors_created_by_fkey",
        "emission_factors",
        "users",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        "power_factors_created_by_fkey",
        "power_factors",
        "users",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        "equipment_created_by_fkey", "equipment", "users", ["created_by"], ["id"]
    )
    op.create_foreign_key(
        "equipment_updated_by_fkey", "equipment", "users", ["updated_by"], ["id"]
    )


def downgrade() -> None:
    # --- 1. DROP UPGRADE CONSTRAINTS ---
    op.drop_constraint("unit_users_unit_id_fkey", "unit_users", type_="foreignkey")
    op.drop_constraint("unit_users_user_id_fkey", "unit_users", type_="foreignkey")
    op.drop_constraint(
        "emission_factors_created_by_fkey", "emission_factors", type_="foreignkey"
    )
    op.drop_constraint(
        "power_factors_created_by_fkey", "power_factors", type_="foreignkey"
    )
    op.drop_constraint("equipment_created_by_fkey", "equipment", type_="foreignkey")
    op.drop_constraint("equipment_updated_by_fkey", "equipment", type_="foreignkey")

    # --- 2. REVERT IDs TO VARCHAR & REMOVE IDENTITY ---
    op.execute("ALTER TABLE units ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.alter_column("units", "id", type_=sa.VARCHAR(), postgresql_using="id::text")

    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")
    op.alter_column("users", "id", type_=sa.VARCHAR(), postgresql_using="id::text")

    # --- 3. REVERT ALL OTHER TYPES ---
    op.alter_column(
        "unit_users", "unit_id", type_=sa.VARCHAR(), postgresql_using="unit_id::text"
    )
    op.alter_column(
        "unit_users", "user_id", type_=sa.VARCHAR(), postgresql_using="user_id::text"
    )
    op.alter_column(
        "unit_users", "role", type_=sa.VARCHAR(), postgresql_using="role::text"
    )
    op.alter_column(
        "emission_factors",
        "created_by",
        type_=sa.VARCHAR(),
        postgresql_using="created_by::text",
    )
    op.alter_column(
        "power_factors",
        "created_by",
        type_=sa.VARCHAR(),
        postgresql_using="created_by::text",
    )
    op.alter_column(
        "equipment",
        "created_by",
        type_=sa.VARCHAR(),
        postgresql_using="created_by::text",
    )
    op.alter_column(
        "equipment",
        "updated_by",
        type_=sa.VARCHAR(),
        postgresql_using="updated_by::text",
    )
    op.alter_column(
        "units", "provider", type_=sa.VARCHAR(), postgresql_using="provider::text"
    )
    op.alter_column(
        "users", "provider", type_=sa.VARCHAR(), postgresql_using="provider::text"
    )

    # --- 4. RESTORE OLD COLUMNS ---
    # Using server_default for non-nullable columns
    # to allow downgrade with existing data
    op.add_column(
        "units",
        sa.Column("visibility", sa.VARCHAR(), nullable=False, server_default="DEFAULT"),
    )
    for col in [
        "updated_at",
        "code",
        "created_at",
        "principal_user_email",
        "principal_user_function",
        "principal_user_id",
        "updated_by",
        "principal_user_name",
        "created_by",
        "cf",
    ]:
        op.add_column(
            "units",
            sa.Column(
                col,
                sa.VARCHAR()
                if "at" not in col
                else postgresql.TIMESTAMP(timezone=True),
            ),
        )

    op.add_column(
        "users",
        sa.Column("is_active", sa.BOOLEAN(), nullable=False, server_default="true"),
    )
    for col in ["updated_at", "created_at", "updated_by", "created_by"]:
        op.add_column(
            "users",
            sa.Column(
                col,
                sa.VARCHAR()
                if "at" not in col
                else postgresql.TIMESTAMP(timezone=True),
            ),
        )

    # --- 5. CLEANUP NEW STUFF ---
    op.drop_column("units", "cost_centers")
    op.drop_column("units", "principal_user_provider_code")
    op.drop_column("units", "provider_code")
    op.drop_column("users", "function")
    op.drop_column("users", "provider_code")

    # --- 6. RECREATE ORIGINAL CONSTRAINTS (THIS IS THE FIX) ---
    op.create_foreign_key(
        "unit_users_unit_id_fkey", "unit_users", "units", ["unit_id"], ["id"]
    )
    op.create_foreign_key(
        "unit_users_user_id_fkey", "unit_users", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "emission_factors_created_by_fkey",
        "emission_factors",
        "users",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        "power_factors_created_by_fkey",
        "power_factors",
        "users",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        "equipment_created_by_fkey", "equipment", "users", ["created_by"], ["id"]
    )
    op.create_foreign_key(
        "equipment_updated_by_fkey", "equipment", "users", ["updated_by"], ["id"]
    )

    # --- 7. CLEANUP ENUMS ---
    op.execute("DROP TYPE IF EXISTS user_provider_enum")
    op.execute("DROP TYPE IF EXISTS role_name_enum")
