# codeql[py/unused-global-variable]
"""pods runs_jobs flag

Revision ID: 9da4a65ef1e3
Revises: 7e026b9941cd
Create Date: 2026-09-17 21:40:33.935355

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "9da4a65ef1e3"  # noqa: F841
down_revision: str | Sequence[str] | None = "7e026b9941cd"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Pruned false positives: the trgm index drop on
    # classification_translations, and the drop/create of
    # uq_emission_recalc_active_scoped (autogenerate re-renders the
    # expression index on every run; the live index is already correct).
    op.add_column(
        "pods",
        sa.Column(
            "runs_jobs", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pods", "runs_jobs")
    # ### end Alembic commands ###
