# codeql[py/unused-global-variable]
"""add unique constraint

Revision ID: 4bb12eac487e
Revises: d24e845955cc
Create Date: 2026-02-20 14:12:28.792743

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "4bb12eac487e"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "d24e845955cc"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #     -- ===============================
    # -- CARBON REPORTS
    # -- ===============================

    op.execute(
        "ALTER TABLE carbon_reports ADD CONSTRAINT carbon_reports_year_unit_unique "
        "UNIQUE (year, unit_id);"
    )

    # -- ===============================
    # -- CARBON REPORT MODULES
    # -- ===============================

    op.execute(
        "ALTER TABLE carbon_report_modules ADD CONSTRAINT carbon_report_modules_unique "
        "UNIQUE (carbon_report_id, module_type_id);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #     -- ===============================
    # -- CARBON REPORTS
    # -- ===============================
    op.execute(
        "ALTER TABLE carbon_reports DROP CONSTRAINT carbon_reports_year_unit_unique;"
    )

    # -- ===============================
    # -- CARBON REPORT MODULES
    # -- ===============================
    op.execute(
        "ALTER TABLE carbon_report_modules DROP CONSTRAINT "
        "carbon_report_modules_unique;"
    )
    # ### end Alembic commands ###
