# codeql[py/unused-global-variable]
"""add unique constraint for carbon_report

Revision ID: 2d69661d72fe
Revises: 8f5a2b1d4c3e
Create Date: 2026-02-23 14:22:32.284827

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "2d69661d72fe"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "8f5a2b1d4c3e"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "carbon_report_modules", sa.Column("last_updated", sa.Integer(), nullable=True)
    )
    op.add_column("carbon_report_modules", sa.Column("stats", sa.JSON(), nullable=True))
    op.drop_index(
        op.f("idx_carbon_report_modules_report"), table_name="carbon_report_modules"
    )
    op.drop_index(op.f("idx_carbon_reports_year"), table_name="carbon_reports")
    op.create_unique_constraint(
        "uq_carbon_reports_unit_year", "carbon_reports", ["unit_id", "year"]
    )
    op.drop_index(op.f("idx_data_entries_module"), table_name="data_entries")
    op.drop_index(
        op.f("idx_data_entry_emissions_entry"), table_name="data_entry_emissions"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("idx_data_entry_emissions_entry"),
        "data_entry_emissions",
        ["data_entry_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_data_entries_module"),
        "data_entries",
        ["carbon_report_module_id"],
        unique=False,
    )
    op.drop_constraint("uq_carbon_reports_unit_year", "carbon_reports", type_="unique")
    op.create_index(
        op.f("idx_carbon_reports_year"), "carbon_reports", ["year"], unique=False
    )
    op.create_index(
        op.f("idx_carbon_report_modules_report"),
        "carbon_report_modules",
        ["carbon_report_id"],
        unique=False,
    )
    op.drop_column("carbon_report_modules", "stats")
    op.drop_column("carbon_report_modules", "last_updated")
    # ### end Alembic commands ###
