# codeql[py/unused-global-variable]
"""add sync_status fields to audit_documents

Revision ID: 36eb78f7b21f
Revises: c7d9a1b2e3f4
Create Date: 2026-02-16 17:12:02.854811

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "36eb78f7b21f"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "c7d9a1b2e3f4"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely drop indexes and tables if they exist
    bind = op.get_bind()

    # Check if audit table exists and drop its indexes
    if bind.dialect.has_table(bind, "audit"):
        op.drop_index(op.f("ix_audit_entity_id"), table_name="audit", if_exists=True)
        op.drop_index(op.f("ix_audit_entity_type"), table_name="audit", if_exists=True)
        op.drop_index(op.f("ix_audit_id"), table_name="audit", if_exists=True)
        op.drop_index(op.f("ix_audit_version"), table_name="audit", if_exists=True)
        op.drop_table("audit")

    # Check if audit_documents table exists and drop its indexes
    if bind.dialect.has_table(bind, "audit_documents"):
        op.drop_index(
            op.f("ix_audit_documents_change_type"),
            table_name="audit_documents",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_audit_documents_changed_at"),
            table_name="audit_documents",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_audit_documents_changed_by"),
            table_name="audit_documents",
            if_exists=True,
        )
        op.drop_index(
            op.f("ix_audit_documents_composite"),
            table_name="audit_documents",
            if_exists=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    # Check if audit_documents table exists before creating indexes
    if bind.dialect.has_table(bind, "audit_documents"):
        op.create_index(
            op.f("ix_audit_documents_composite"),
            "audit_documents",
            ["entity_type", "entity_id", "changed_at"],
            unique=False,
        )
        op.create_index(
            op.f("ix_audit_documents_changed_by"),
            "audit_documents",
            ["changed_by"],
            unique=False,
        )
        op.create_index(
            op.f("ix_audit_documents_changed_at"),
            "audit_documents",
            ["changed_at"],
            unique=False,
        )
        op.create_index(
            op.f("ix_audit_documents_change_type"),
            "audit_documents",
            ["change_type"],
            unique=False,
        )

    # Check if audit table exists before creating it
    if not bind.dialect.has_table(bind, "audit"):
        op.create_table(
            "audit",
            sa.Column("entity_type", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.Column("entity_id", sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column("version", sa.INTEGER(), autoincrement=False, nullable=False),
            sa.Column("is_current", sa.BOOLEAN(), autoincrement=False, nullable=False),
            sa.Column(
                "data_snapshot",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "data_diff",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column("change_type", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.Column(
                "change_reason", sa.VARCHAR(), autoincrement=False, nullable=True
            ),
            sa.Column("changed_by", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.Column(
                "changed_at",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            ),
            sa.Column("handler_id", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.Column(
                "handled_it",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column("ip_address", sa.VARCHAR(), autoincrement=False, nullable=False),
            sa.Column("route_path", sa.VARCHAR(), autoincrement=False, nullable=True),
            sa.Column(
                "route_payload",
                postgresql.JSON(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            ),
            sa.Column(
                "previous_hash", sa.VARCHAR(), autoincrement=False, nullable=True
            ),
            sa.Column(
                "current_hash", sa.VARCHAR(), autoincrement=False, nullable=False
            ),
            sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
            sa.PrimaryKeyConstraint("id", name=op.f("audit_pkey")),
        )

        # Create indexes for the audit table
        op.create_index(op.f("ix_audit_version"), "audit", ["version"], unique=False)
        op.create_index(op.f("ix_audit_id"), "audit", ["id"], unique=False)
        op.create_index(
            op.f("ix_audit_entity_type"), "audit", ["entity_type"], unique=False
        )
        op.create_index(
            op.f("ix_audit_entity_id"), "audit", ["entity_id"], unique=False
        )
    # ### end Alembic commands ###
