# codeql[py/unused-global-variable]
"""add natural key to locations

Revision ID: 8f29ed82872b
Revises: 1e56d303cc85
Create Date: 2026-05-12 11:16:49.653716

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "8f29ed82872b"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "1e56d303cc85"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841

_AGG_WHERE = (
    "(((job_type)::text = 'aggregation'::text)"
    " AND (state = ANY (ARRAY["
    "'NOT_STARTED'::ingestion_state_enum,"
    " 'QUEUED'::ingestion_state_enum,"
    " 'RUNNING'::ingestion_state_enum])))"
)

_RECALC_WHERE = (
    "(((job_type)::text = 'emission_recalc'::text)"
    " AND (state = ANY (ARRAY["
    "'NOT_STARTED'::ingestion_state_enum,"
    " 'QUEUED'::ingestion_state_enum,"
    " 'RUNNING'::ingestion_state_enum]))"
    " AND (module_type_id IS NOT NULL)"
    " AND (data_entry_type_id IS NOT NULL)"
    " AND (year IS NOT NULL))"
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_aggregation_active"),
        table_name="data_ingestion_jobs",
        postgresql_where=_AGG_WHERE,
    )
    op.drop_index(
        op.f("uq_emission_recalc_active"),
        table_name="data_ingestion_jobs",
        postgresql_where=_RECALC_WHERE,
    )
    op.drop_index(
        op.f("uq_factor_identity"),
        table_name="factors",
        postgresql_where="(year IS NOT NULL)",
    )
    op.drop_index(
        op.f("uq_factor_identity_no_year"),
        table_name="factors",
        postgresql_where="(year IS NULL)",
    )
    op.add_column(
        "locations",
        sa.Column(
            "natural_key",
            sqlmodel.sql.sqltypes.AutoString(length=500),
            nullable=False,
        ),
    )
    op.drop_index(
        op.f("ix_locations_keywords"),
        table_name="locations",
        postgresql_ops={"keywords": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.create_index(
        "uq_location_natural_key", "locations", ["natural_key"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_location_natural_key", table_name="locations")
    op.create_index(
        op.f("ix_locations_keywords"),
        "locations",
        ["keywords"],
        unique=False,
        postgresql_ops={"keywords": "gin_trgm_ops"},
        postgresql_using="gin",
    )
    op.drop_column("locations", "natural_key")
    op.create_index(
        op.f("uq_factor_identity_no_year"),
        "factors",
        [
            "data_entry_type_id",
            "emission_type_id",
            sa.literal_column("(classification::text)"),
        ],
        unique=True,
        postgresql_where="(year IS NULL)",
    )
    op.create_index(
        op.f("uq_factor_identity"),
        "factors",
        [
            "data_entry_type_id",
            "year",
            "emission_type_id",
            sa.literal_column("(classification::text)"),
        ],
        unique=True,
        postgresql_where="(year IS NOT NULL)",
    )
    op.create_index(
        op.f("uq_emission_recalc_active"),
        "data_ingestion_jobs",
        ["module_type_id", "data_entry_type_id", "year"],
        unique=True,
        postgresql_where=_RECALC_WHERE,
    )
    op.create_index(
        op.f("uq_aggregation_active"),
        "data_ingestion_jobs",
        ["module_type_id", "year"],
        unique=True,
        postgresql_where=_AGG_WHERE,
    )
    # ### end Alembic commands ###
