# codeql[py/unused-global-variable]
"""drop plan name unique index

Revision ID: 6e32aa42f6f4
Revises: ef0ef41fc242
Create Date: 2026-08-28 11:16:35.719790

"""

from collections.abc import Sequence

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "6e32aa42f6f4"  # noqa: F841
down_revision: str | Sequence[str] | None = "ef0ef41fc242"  # noqa: F841
branch_labels: str | Sequence[str] | None = None  # noqa: F841
depends_on: str | Sequence[str] | None = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_carbon_projects_unit_plan_name"),
        table_name="carbon_projects",
        postgresql_where="(carbon_report_type = 'Simulator_Plan'::carbon_report_type_enum)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("uq_carbon_projects_unit_plan_name"),
        "carbon_projects",
        ["unit_id", "name"],
        unique=True,
        postgresql_where="(carbon_report_type = 'Simulator_Plan'::carbon_report_type_enum)",
    )
    # ### end Alembic commands ###
