# codeql[py/unused-global-variable]
"""add source tracking to data_entries

Revision ID: 2026031801
Revises: 0367f025e8d8
Create Date: 2026-03-18 14:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "2026031801"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "0367f025e8d8"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """
    Upgrade schema.

    Adds source tracking columns to data_entries table:
    - source: Integer (nullable) - DataEntrySourceEnum value
    - created_by_id: Integer (nullable) - user.id or data_ingestion_job.id
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # Add source column (nullable to allow backfill strategy)
    op.add_column(
        "data_entries",
        sa.Column("source", sa.Integer(), nullable=True),
    )

    # Add created_by_id column
    op.add_column(
        "data_entries",
        sa.Column("created_by_id", sa.Integer(), nullable=True),
    )

    # Create indexes for query performance
    op.create_index(
        op.f("ix_data_entries_source"),
        "data_entries",
        ["source"],
        unique=False,
    )

    op.create_index(
        op.f("ix_data_entries_created_by_id"),
        "data_entries",
        ["created_by_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.

    Removes source tracking columns from data_entries table.
    """
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes first
    op.drop_index(
        op.f("ix_data_entries_source"),
        table_name="data_entries",
    )

    op.drop_index(
        op.f("ix_data_entries_created_by_id"),
        table_name="data_entries",
    )

    # Drop columns
    op.drop_column("data_entries", "created_by_id")
    op.drop_column("data_entries", "source")

    # ### end Alembic commands ###
