# codeql[py/unused-global-variable]
"""add denormalized year and unit_id to data_entries

Revision ID: aee05b6840c0
Revises: a200b8491d76
Create Date: 2026-06-12 16:12:25.668999

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "aee05b6840c0"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "a200b8491d76"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_entries", sa.Column("year", sa.Integer(), nullable=True))
    op.add_column("data_entries", sa.Column("unit_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_data_entries_unit_id"), "data_entries", ["unit_id"], unique=False
    )
    op.create_index(
        op.f("ix_data_entries_year"), "data_entries", ["year"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_data_entries_year"), table_name="data_entries")
    op.drop_index(op.f("ix_data_entries_unit_id"), table_name="data_entries")
    op.drop_column("data_entries", "unit_id")
    op.drop_column("data_entries", "year")
    # ### end Alembic commands ###
