"""initial revision

Revision ID: 84a925e8d8e8
Revises: 
Create Date: 2026-01-12 17:09:24.722521

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '84a925e8d8e8' # noqa: F841
down_revision: Union[str, Sequence[str], None] = None # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None # noqa: F841
depends_on: Union[str, Sequence[str], None] = None # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit',
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('data_snapshot', sa.JSON(), nullable=True),
    sa.Column('data_diff', sa.JSON(), nullable=True),
    sa.Column('change_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('previous_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entity_id'), 'audit', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entity_type'), 'audit', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_id'), 'audit', ['id'], unique=False)
    op.create_index(op.f('ix_audit_version'), 'audit', ['version'], unique=False)
    op.create_table('emission_types',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emission_types_code'), 'emission_types', ['code'], unique=True)
    op.create_index(op.f('ix_emission_types_id'), 'emission_types', ['id'], unique=False)
    op.create_table('module_types',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_types_id'), 'module_types', ['id'], unique=False)
    op.create_index(op.f('ix_module_types_name'), 'module_types', ['name'], unique=True)
    op.create_table('users',
    sa.Column('roles_raw', sa.JSON(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_code'), 'users', ['code'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('data_entry_types',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('module_type_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_type_id'], ['module_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_entry_types_id'), 'data_entry_types', ['id'], unique=False)
    op.create_index(op.f('ix_data_entry_types_module_type_id'), 'data_entry_types', ['module_type_id'], unique=False)
    op.create_index(op.f('ix_data_entry_types_name'), 'data_entry_types', ['name'], unique=False)
    op.create_table('units',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('principal_user_provider_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_centers', sa.JSON(), nullable=True),
    sa.Column('affiliations', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['principal_user_provider_code'], ['users.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_units_code'), 'units', ['code'], unique=True)
    op.create_index(op.f('ix_units_id'), 'units', ['id'], unique=False)
    op.create_index(op.f('ix_units_name'), 'units', ['name'], unique=False)
    op.create_index(op.f('ix_units_principal_user_provider_code'), 'units', ['principal_user_provider_code'], unique=False)
    op.create_table('carbon_reports',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_reports_unit_id'), 'carbon_reports', ['unit_id'], unique=False)
    op.create_table('factors',
    sa.Column('emission_type_id', sa.Integer(), nullable=False),
    sa.Column('is_conversion', sa.Boolean(), nullable=False),
    sa.Column('data_entry_type_id', sa.Integer(), nullable=True),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_entry_type_id'], ['data_entry_types.id'], ),
    sa.ForeignKeyConstraint(['emission_type_id'], ['emission_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factors_data_entry_type_id'), 'factors', ['data_entry_type_id'], unique=False)
    op.create_index(op.f('ix_factors_emission_type_id'), 'factors', ['emission_type_id'], unique=False)
    op.create_index(op.f('ix_factors_id'), 'factors', ['id'], unique=False)
    op.create_index(op.f('ix_factors_is_conversion'), 'factors', ['is_conversion'], unique=False)
    op.create_table('unit_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_users_role'), 'unit_users', ['role'], unique=False)
    op.create_index(op.f('ix_unit_users_unit_id'), 'unit_users', ['unit_id'], unique=False)
    op.create_index(op.f('ix_unit_users_user_id'), 'unit_users', ['user_id'], unique=False)
    op.create_table('carbon_report_modules',
    sa.Column('module_type_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('carbon_report_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carbon_report_id'], ['carbon_reports.id'], ),
    sa.ForeignKeyConstraint(['module_type_id'], ['module_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_report_modules_carbon_report_id'), 'carbon_report_modules', ['carbon_report_id'], unique=False)
    op.create_index(op.f('ix_carbon_report_modules_module_type_id'), 'carbon_report_modules', ['module_type_id'], unique=False)
    op.create_table('data_entries',
    sa.Column('data_entry_type_id', sa.Integer(), nullable=True),
    sa.Column('carbon_report_module_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['carbon_report_module_id'], ['carbon_report_modules.id'], ),
    sa.ForeignKeyConstraint(['data_entry_type_id'], ['data_entry_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_entries_carbon_report_module_id'), 'data_entries', ['carbon_report_module_id'], unique=False)
    op.create_index(op.f('ix_data_entries_data_entry_type_id'), 'data_entries', ['data_entry_type_id'], unique=False)
    op.create_index(op.f('ix_data_entries_id'), 'data_entries', ['id'], unique=False)
    op.create_table('data_entry_emissions',
    sa.Column('data_entry_id', sa.Integer(), nullable=False),
    sa.Column('emission_type_id', sa.Integer(), nullable=False),
    sa.Column('primary_factor_id', sa.Integer(), nullable=True),
    sa.Column('subcategory', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kg_co2eq', sa.Float(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('formula_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_entry_id'], ['data_entries.id'], ),
    sa.ForeignKeyConstraint(['emission_type_id'], ['emission_types.id'], ),
    sa.ForeignKeyConstraint(['primary_factor_id'], ['factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_entry_emissions_computed_at'), 'data_entry_emissions', ['computed_at'], unique=False)
    op.create_index(op.f('ix_data_entry_emissions_data_entry_id'), 'data_entry_emissions', ['data_entry_id'], unique=False)
    op.create_index(op.f('ix_data_entry_emissions_emission_type_id'), 'data_entry_emissions', ['emission_type_id'], unique=False)
    op.create_index(op.f('ix_data_entry_emissions_id'), 'data_entry_emissions', ['id'], unique=False)
    op.create_index(op.f('ix_data_entry_emissions_primary_factor_id'), 'data_entry_emissions', ['primary_factor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_entry_emissions_primary_factor_id'), table_name='data_entry_emissions')
    op.drop_index(op.f('ix_data_entry_emissions_id'), table_name='data_entry_emissions')
    op.drop_index(op.f('ix_data_entry_emissions_emission_type_id'), table_name='data_entry_emissions')
    op.drop_index(op.f('ix_data_entry_emissions_data_entry_id'), table_name='data_entry_emissions')
    op.drop_index(op.f('ix_data_entry_emissions_computed_at'), table_name='data_entry_emissions')
    op.drop_table('data_entry_emissions')
    op.drop_index(op.f('ix_data_entries_id'), table_name='data_entries')
    op.drop_index(op.f('ix_data_entries_data_entry_type_id'), table_name='data_entries')
    op.drop_index(op.f('ix_data_entries_carbon_report_module_id'), table_name='data_entries')
    op.drop_table('data_entries')
    op.drop_index(op.f('ix_carbon_report_modules_module_type_id'), table_name='carbon_report_modules')
    op.drop_index(op.f('ix_carbon_report_modules_carbon_report_id'), table_name='carbon_report_modules')
    op.drop_table('carbon_report_modules')
    op.drop_index(op.f('ix_unit_users_user_id'), table_name='unit_users')
    op.drop_index(op.f('ix_unit_users_unit_id'), table_name='unit_users')
    op.drop_index(op.f('ix_unit_users_role'), table_name='unit_users')
    op.drop_table('unit_users')
    op.drop_index(op.f('ix_factors_is_conversion'), table_name='factors')
    op.drop_index(op.f('ix_factors_id'), table_name='factors')
    op.drop_index(op.f('ix_factors_emission_type_id'), table_name='factors')
    op.drop_index(op.f('ix_factors_data_entry_type_id'), table_name='factors')
    op.drop_table('factors')
    op.drop_index(op.f('ix_carbon_reports_unit_id'), table_name='carbon_reports')
    op.drop_table('carbon_reports')
    op.drop_index(op.f('ix_units_principal_user_provider_code'), table_name='units')
    op.drop_index(op.f('ix_units_name'), table_name='units')
    op.drop_index(op.f('ix_units_id'), table_name='units')
    op.drop_index(op.f('ix_units_code'), table_name='units')
    op.drop_table('units')
    op.drop_index(op.f('ix_data_entry_types_name'), table_name='data_entry_types')
    op.drop_index(op.f('ix_data_entry_types_module_type_id'), table_name='data_entry_types')
    op.drop_index(op.f('ix_data_entry_types_id'), table_name='data_entry_types')
    op.drop_table('data_entry_types')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_code'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_module_types_name'), table_name='module_types')
    op.drop_index(op.f('ix_module_types_id'), table_name='module_types')
    op.drop_table('module_types')
    op.drop_index(op.f('ix_emission_types_id'), table_name='emission_types')
    op.drop_index(op.f('ix_emission_types_code'), table_name='emission_types')
    op.drop_table('emission_types')
    op.drop_index(op.f('ix_audit_version'), table_name='audit')
    op.drop_index(op.f('ix_audit_id'), table_name='audit')
    op.drop_index(op.f('ix_audit_entity_type'), table_name='audit')
    op.drop_index(op.f('ix_audit_entity_id'), table_name='audit')
    op.drop_table('audit')
    # ### end Alembic commands ###
