# codeql[py/unused-global-variable]
"""add new year-configuration

Revision ID: 78a9e8951a27
Revises: a1b2c3d4e5f7
Create Date: 2026-04-01 09:04:40.726336

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "78a9e8951a27"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f7"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_year_configuration_year"), table_name="year_configuration")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_year_configuration_year"), "year_configuration", ["year"], unique=True
    )
    # ### end Alembic commands ###
