# codeql[py/unused-global-variable]
"""drop constraint for principal_user_provider_code

Revision ID: 68212d566ed9
Revises: 7e0dc4acb886
Create Date: 2026-02-25 11:25:58.883500

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "68212d566ed9"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "7e0dc4acb886"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("units_principal_user_provider_code_fkey"), "units", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("units_principal_user_provider_code_fkey"),
        "units",
        "users",
        ["principal_user_provider_code"],
        ["provider_code"],
    )
    # ### end Alembic commands ###
