# codeql[py/unused-global-variable]
"""create/drop-constraint

Revision ID: aaaea3d89dc4
Revises: 94965a1ded3e
Create Date: 2026-02-25 10:02:57.571619

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "aaaea3d89dc4"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "94965a1ded3e"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("carbon_report_modules_unique"), "carbon_report_modules", type_="unique"
    )
    op.drop_index(
        op.f("idx_crm_report_type_status"), table_name="carbon_report_modules"
    )
    op.create_unique_constraint(
        "uq_carbon_report_module",
        "carbon_report_modules",
        ["carbon_report_id", "module_type_id"],
    )
    # replaced by uq_carbon_report
    op.drop_constraint(
        op.f("carbon_reports_year_unit_unique"), "carbon_reports", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("carbon_reports_year_unit_unique"),
        "carbon_reports",
        ["year", "unit_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint(
        "uq_carbon_report_module", "carbon_report_modules", type_="unique"
    )
    op.create_index(
        op.f("idx_crm_report_type_status"),
        "carbon_report_modules",
        ["carbon_report_id", "module_type_id", "status"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("carbon_report_modules_unique"),
        "carbon_report_modules",
        ["carbon_report_id", "module_type_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
