# codeql[py/unused-global-variable]
"""Add data_entry_type to data-ingestion

Revision ID: 2cc51f3595ce
Revises: 23bf7767c44c
Create Date: 2026-02-02 17:05:36.874320

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "2cc51f3595ce"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "23bf7767c44c"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_entries", "data_entry_type_id", existing_type=sa.Integer(), nullable=False
    )
    op.add_column(
        "data_ingestion_jobs",
        sa.Column("data_entry_type_id", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_ingestion_jobs", "data_entry_type_id")
    op.alter_column(
        "data_entries", "data_entry_type_id", existing_type=sa.Integer(), nullable=True
    )
    # ### end Alembic commands ###
