# codeql[py/unused-global-variable]
"""Add on cascade

Revision ID: 0c6d17aa4ac0
Revises: b65a2c4e120f
Create Date: 2026-01-28 16:06:33.760647

"""

from typing import Sequence, Union

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "0c6d17aa4ac0"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "b65a2c4e120f"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("data_entry_emissions_primary_factor_id_fkey"),
        "data_entry_emissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("data_entry_emissions_data_entry_id_fkey"),
        "data_entry_emissions",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "data_entry_emissions",
        "factors",
        ["primary_factor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "data_entry_emissions", type_="foreignkey")
    op.create_foreign_key(
        op.f("data_entry_emissions_data_entry_id_fkey"),
        "data_entry_emissions",
        "data_entries",
        ["data_entry_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("data_entry_emissions_primary_factor_id_fkey"),
        "data_entry_emissions",
        "factors",
        ["primary_factor_id"],
        ["id"],
    )
    # ### end Alembic commands ###
