# codeql[py/unused-global-variable]
"""Add new audit table

Revision ID: eeee4be3b6e1
Revises: e56b52f2d555
Create Date: 2026-02-12 15:44:57.377138

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

__all__ = [
    "revision",
    "down_revision",
    "branch_labels",
    "depends_on",
]


# revision identifiers, used by Alembic.
revision: str = "eeee4be3b6e1"  # noqa: F841
down_revision: Union[str, Sequence[str], None] = "e56b52f2d555"  # noqa: F841
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_documents",
        sa.Column("entity_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("data_snapshot", sa.JSON(), nullable=True),
        sa.Column("data_diff", sa.JSON(), nullable=True),
        sa.Column("change_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("change_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("changed_by", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("changed_at", sa.DateTime(), nullable=False),
        sa.Column("handler_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("handled_it", sa.JSON(), nullable=True),
        sa.Column("ip_address", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("route_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("route_payload", sa.JSON(), nullable=True),
        sa.Column("previous_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("current_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_documents_entity_id"),
        "audit_documents",
        ["entity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_documents_entity_type"),
        "audit_documents",
        ["entity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_documents_id"), "audit_documents", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_documents_version"), "audit_documents", ["version"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_documents_version"), table_name="audit_documents")
    op.drop_index(op.f("ix_audit_documents_id"), table_name="audit_documents")
    op.drop_index(op.f("ix_audit_documents_entity_type"), table_name="audit_documents")
    op.drop_index(op.f("ix_audit_documents_entity_id"), table_name="audit_documents")
    op.drop_table("audit_documents")
    # ### end Alembic commands ###
