"""Generate frontend module-lookup constants from their backend sources.

Usage: ``make gen-module-constants`` (writes
``frontend/src/types/module-lookups.gen.ts``).

Mirrors ``generate_emission_taxonomy_ts.py``. The hand-mirrored versions of
these value lists had already drifted from their backend source at least
once (#2391: `enumSubmodule` was missing `building_embodied_energy`) — this
generates them instead of hand-copying.
"""

from app.models.data_entry import DataEntryTypeEnum
from app.modules.buildings.data_entries import VALID_ROOM_TYPES
from app.modules.headcount.data_entries import SIUS_CODE_VALUES
from app.modules.professional_travel.emissions import (
    PLANE_CABIN_MAP,
    TRAIN_CLASS_MAP,
)
from app.utils.currencies import SUPPORTED_CURRENCIES

HEADER = "// AUTO-GENERATED by backend `make gen-module-constants` — do not edit."


def _print_data_entry_type_ids() -> None:
    print(HEADER)
    print("// Source: backend/app/models/data_entry.py (DataEntryTypeEnum).")
    print("export const DATA_ENTRY_TYPE_IDS = {")
    # `.__members__.values()` (not `for member in DataEntryTypeEnum`) — CodeQL's
    # non-iterable-in-for-loop check doesn't model EnumMeta.__iter__ on an
    # `int`-mixed Enum subclass, and flags a false positive otherwise.
    for member in DataEntryTypeEnum.__members__.values():
        print(f"  {member.name}: {member.value},")
    print("} as const;")
    print()


def _print_string_array(var_name: str, source_comment: str, values: list[str]) -> None:
    print(HEADER)
    print(f"// Source: {source_comment}")
    print(f"export const {var_name} = [")
    for value in values:
        print(f"  '{value}',")
    print("] as const;")
    print()


def main() -> None:
    _print_data_entry_type_ids()
    _print_string_array(
        "CURRENCY_CODES",
        "backend/app/utils/currencies.py (SUPPORTED_CURRENCIES).",
        sorted(SUPPORTED_CURRENCIES),
    )
    _print_string_array(
        "ROOM_TYPES",
        "backend/app/modules/buildings/data_entries.py (VALID_ROOM_TYPES).",
        [room_type for room_type in VALID_ROOM_TYPES if room_type],
    )
    _print_string_array(
        "PLANE_CABIN_CLASSES",
        "backend/app/modules/professional_travel/emissions.py (PLANE_CABIN_MAP).",
        list(PLANE_CABIN_MAP),
    )
    _print_string_array(
        "TRAIN_CABIN_CLASSES",
        "backend/app/modules/professional_travel/emissions.py (TRAIN_CLASS_MAP).",
        list(TRAIN_CLASS_MAP),
    )
    _print_string_array(
        "SIUS_CODES",
        "backend/app/modules/headcount/data_entries.py (SIUS_CODE_VALUES, "
        "excludes the OTHER_SIUS_CODE display-only sentinel).",
        sorted(SIUS_CODE_VALUES),
    )


if __name__ == "__main__":
    main()
