"""Generate the frontend emission-taxonomy constant from the backend enum.

Usage: ``make gen-emission-taxonomy`` (writes
``frontend/src/types/emission-taxonomy.gen.ts``).

The stats payloads key emission values by numeric emission_type_id; the
frontend needs the enum names for i18n keys, chart colors and parent
grouping. This mirror is generated, never hand-edited.
"""

from app.modules.emissions.taxonomy import EmissionType


def main() -> None:
    print("// AUTO-GENERATED by backend `make gen-emission-taxonomy` — do not edit.")
    print("// Source: backend/app/modules/emissions/taxonomy.py (EmissionType).")
    print("export const EMISSION_TYPE_NAMES: Record<number, string> = {")
    for node in EmissionType:
        print(f"  {node.value}: '{node.name}',")
    print("};")


if __name__ == "__main__":
    main()
