import { ModuleConfig, ModuleField } from 'src/constant/moduleConfig';
import { SUBMODULE_BUILDINGS_TYPES, MODULES } from 'src/constant/modules';
import type { BuildingsSubType, Module } from 'src/constant/modules';
import { formatTonnesCO2 } from 'src/utils/number';
import type { AllSubmoduleTypes } from 'src/constant/modules';

const roomFields: ModuleField[] = [
  {
    id: 'building_name',
    treeLevel: 0,
    labelKey: `${MODULES.Buildings}.inputs.building_name`,
    type: 'select',
    required: true,
    sortable: true,
    editableInline: false,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/3',
    icon: 'o_apartment',
  },
  {
    id: 'room_name',
    treeLevel: 1,
    labelKey: `${MODULES.Buildings}.inputs.room_name`,
    type: 'select',
    required: true,
    sortable: true,
    editableInline: false,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/3',
    icon: 'o_meeting_room',
  },
  {
    id: 'room_type',
    labelKey: `${MODULES.Buildings}.inputs.room_type`,
    type: 'select',
    sortable: true,
    editableInline: true,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/3',
    icon: 'o_category',
    disableUntilField: 'room_name',
    options: [
      { value: '', label: '-' },
      { value: 'Office', label: 'Office' },
      { value: 'Miscels', label: 'Miscellaneous' },
      {
        value: 'Laboratories',
        label: 'Laboratories',
      },
      { value: 'Archives', label: 'Archives' },
      { value: 'Libraries', label: 'Libraries' },
      {
        value: 'Auditoriums',
        label: 'Auditoriums',
      },
    ],
  },
  {
    id: 'room_surface_square_meter',
    labelKey: `${MODULES.Buildings}.inputs.room_surface_square_meter`,
    type: 'number',
    sortable: true,
    editableInline: false,
    readOnly: true,
    disable: true,
    unit: 'm²',
    ratio: '1/2',
    icon: 'o_straighten',
  },
  {
    id: 'heating_kwh',
    labelKey: `${MODULES.Buildings}.inputs.heating_kwh`,
    type: 'number',
    readOnly: true,
    sortable: true,
    hideIn: { form: true },
    unit: 'kWh',
    tooltip: `${MODULES.Buildings}.tooltips.heating`,
  },
  {
    id: 'cooling_kwh',
    labelKey: `${MODULES.Buildings}.inputs.cooling_kwh`,
    type: 'number',
    readOnly: true,
    sortable: true,
    hideIn: { form: true },
    unit: 'kWh',
    tooltip: `${MODULES.Buildings}.tooltips.cooling`,
  },
  {
    id: 'ventilation_kwh',
    labelKey: `${MODULES.Buildings}.inputs.ventilation_kwh`,
    type: 'number',
    readOnly: true,
    sortable: true,
    hideIn: { form: true },
    unit: 'kWh',
    tooltip: `${MODULES.Buildings}.tooltips.ventilation`,
  },
  {
    id: 'lighting_kwh',
    labelKey: `${MODULES.Buildings}.inputs.lighting_kwh`,
    type: 'number',
    readOnly: true,
    sortable: true,
    hideIn: { form: true },
    unit: 'kWh',
    tooltip: `${MODULES.Buildings}.tooltips.lighting`,
  },
  {
    id: 'kg_co2eq',
    labelKey: 'results_units_kg',
    type: 'number',
    readOnly: true,
    hideIn: { form: true },
    sortable: true,
  },
];

const energyCombustionFields: ModuleField[] = [
  {
    id: 'heating_type',
    treeLevel: 0,
    labelKey: `${MODULES.Buildings}.inputs.heating_type`,
    type: 'select',
    required: true,
    sortable: true,
    editableInline: true,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/2',
    icon: 'o_local_fire_department',
    hideIn: { form: false },
  },
  {
    id: 'unit',
    labelKey: `${MODULES.Buildings}.inputs.unit`,
    type: 'text',
    readOnly: true,
    sortable: false,
    align: 'left',
    hideIn: { form: true },
  },
  {
    id: 'quantity',
    labelKey: `${MODULES.Buildings}.inputs.quantity`,
    type: 'number',
    required: true,
    editableInline: true,
    sortable: true,
    min: 0.001,
    step: 0.001,
    ratio: '1/2',
    hideIn: { form: false },
  },
  {
    id: 'kg_co2eq',
    labelKey: 'results_units_kg',
    type: 'number',
    readOnly: true,
    hideIn: { form: true },
    sortable: true,
  },
];

export const buildings: ModuleConfig = {
  id: 'module_buildings_001',
  type: MODULES.Buildings as Module,
  hasDescription: true,
  hasDescriptionSubtext: true,
  hasTooltip: true,
  description:
    'Estimate building-related carbon footprint from energy consumption and combustion',
  hasSubmodules: true,
  formStructure: 'perSubmodule',
  numberFormatOptions: {
    minimumFractionDigits: 0,
    maximumFractionDigits: 1,
  },
  submodules: [
    {
      id: SUBMODULE_BUILDINGS_TYPES.Building,
      type: SUBMODULE_BUILDINGS_TYPES.Building as AllSubmoduleTypes,
      tableNameKey: `${MODULES.Buildings}.rooms_table_title`,
      moduleFields: roomFields,
      hasTableAction: true,
      addButtonLabelKey: `${MODULES.Buildings}.add_room_button`,
    },
    {
      id: SUBMODULE_BUILDINGS_TYPES.EnergyCombustion,
      type: SUBMODULE_BUILDINGS_TYPES.EnergyCombustion as BuildingsSubType,
      tableNameKey: `${MODULES.Buildings}.combustion_table_title`,
      moduleFields: energyCombustionFields,
      hasTableAction: true,
      addButtonLabelKey: `${MODULES.Buildings}.add_combustion_button`,
    },
  ],
  totalFormatter: formatTonnesCO2,
};
