import { ModuleConfig, ModuleField } from 'src/constant/moduleConfig';
import { SUBMODULE_BUILDINGS_TYPES, MODULES } from 'src/constant/modules';
import type { BuildingsSubType, Module } from 'src/constant/modules';
import { formatTonnesCO2 } from 'src/utils/number';
import type { AllSubmoduleTypes } from 'src/constant/modules';
import {
  outlinedApartment,
  outlinedMeetingRoom,
  outlinedCategory,
  outlinedStraighten,
  outlinedImageAspectRatio,
  outlinedThermostat,
  outlinedAcUnit,
  outlinedAir,
  outlinedLightMode,
  outlinedLocalFireDepartment,
} from '@quasar/extras/material-icons-outlined';

const roomFields: ModuleField[] = [
  {
    id: 'building_name',
    optionsId: 'kind',
    labelKey: `${MODULES.Buildings}.inputs.building_name`,
    type: 'select',
    required: true,
    sortable: true,
    editableInline: false,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/3',
    icon: outlinedApartment,
    columnSize: 'sm',
    tooltip: 'module-buildings-submodule-building-table-building_name',
  },
  {
    id: 'room_name',
    optionsId: 'subkind',
    labelKey: `${MODULES.Buildings}.inputs.room_name`,
    type: 'select',
    required: true,
    sortable: true,
    editableInline: false,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/3',
    icon: outlinedMeetingRoom,
    columnSize: 'md',
    tooltip: 'module-buildings-submodule-building-table-room_name',
  },
  {
    id: 'room_type',
    labelKey: `${MODULES.Buildings}.inputs.room_type`,
    type: 'select',
    sortable: true,
    editableInline: true,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/3',
    icon: outlinedCategory,
    columnSize: 'md',
    disableUntilField: 'room_name',
    // IMPORTANT: these values are backend emission-factor lookup keys.
    // Do not translate or rename without matching backend seed/data updates.
    // See: https://github.com/EPFL-ENAC/co2-calculator/issues/173
    optionLabelsAreKeys: true,
    tooltip: 'module-buildings-submodule-building-table-room_type',
    options: [
      { value: 'laboratories', label: 'buildings-room-type-laboratories' },
      { value: 'office', label: 'buildings-room-type-office' },
      { value: 'archives', label: 'buildings-room-type-archives' },
      { value: 'libraries', label: 'buildings-room-type-libraries' },
      { value: 'auditoriums', label: 'buildings-room-type-auditoriums' },
      { value: 'miscellaneous', label: 'buildings-room-type-miscellaneous' },
    ],
  },
  {
    id: 'room_surface_square_meter',
    labelKey: `${MODULES.Buildings}.inputs.room_surface_square_meter`,
    type: 'number',
    sortable: true,
    editableInline: false,
    readOnlyWhenFilled: true,
    unit: 'm²',
    ratio: '1/6',
    disableUntilField: 'room_name',
    icon: outlinedStraighten,
    tooltip:
      'module-buildings-submodule-building-table-room_surface_square_meter',
  },
  {
    id: 'room_allocation_ratio',
    labelKey: `${MODULES.Buildings}.inputs.room_allocation_ratio`,
    type: 'number',
    sortable: true,
    editableInline: false,
    readOnlyWhenFilled: true,
    default: 1,
    ratio: '1/6',
    disableUntilField: 'room_name',
    icon: outlinedImageAspectRatio,
    tooltip: 'module-buildings-submodule-building-table-room_allocation_ratio',
    columnSize: 'md',
  },
  {
    id: 'heating_kwh_per_square_meter',
    labelKey: `${MODULES.Buildings}.inputs.heating_kwh_per_square_meter`,
    type: 'number',
    readOnlyWhenFilled: true,
    sortable: false,
    unit: 'kWh/m²',
    ratio: '1/6',
    disableUntilField: 'room_name',
    icon: outlinedThermostat,
    tooltip:
      'module-buildings-submodule-building-table-heating_kwh_per_square_meter',
    maxColumnWidth: 120,
  },
  {
    id: 'cooling_kwh_per_square_meter',
    labelKey: `${MODULES.Buildings}.inputs.cooling_kwh_per_square_meter`,
    type: 'number',
    readOnlyWhenFilled: true,
    sortable: false,
    unit: 'kWh/m²',
    ratio: '1/6',
    disableUntilField: 'room_name',
    icon: outlinedAcUnit,
    tooltip:
      'module-buildings-submodule-building-table-cooling_kwh_per_square_meter',
    maxColumnWidth: 120,
  },
  {
    id: 'ventilation_kwh_per_square_meter',
    labelKey: `${MODULES.Buildings}.inputs.ventilation_kwh_per_square_meter`,
    type: 'number',
    readOnlyWhenFilled: true,
    sortable: false,
    unit: 'kWh/m²',
    ratio: '1/6',
    disableUntilField: 'room_name',
    icon: outlinedAir,
    tooltip:
      'module-buildings-submodule-building-table-ventilation_kwh_per_square_meter',
    maxColumnWidth: 120,
  },
  {
    id: 'lighting_kwh_per_square_meter',
    labelKey: `${MODULES.Buildings}.inputs.lighting_kwh_per_square_meter`,
    type: 'number',
    readOnlyWhenFilled: true,
    sortable: false,
    unit: 'kWh/m²',
    ratio: '1/6',
    disableUntilField: 'room_name',
    icon: outlinedLightMode,
    tooltip:
      'module-buildings-submodule-building-table-lighting_kwh_per_square_meter',
    maxColumnWidth: 120,
  },
  {
    id: 'kg_co2eq',
    labelKey: 'results_units_kg',
    type: 'number',
    readOnly: true,
    hideIn: { form: true },
    sortable: true,
    tooltip: 'module-buildings-submodule-building-table-kg_co2eq',
  },
];

const energyCombustionFields: ModuleField[] = [
  {
    id: 'name',
    optionsId: 'kind',
    labelKey: `${MODULES.Buildings}.inputs.name`,
    type: 'select',
    required: true,
    sortable: true,
    editableInline: true,
    inputTypeName: 'QSelect',
    align: 'left',
    ratio: '1/3',
    icon: outlinedLocalFireDepartment,
    hideIn: { form: false },
    columnSize: 'lg',
    tooltip: 'module-buildings-submodule-energy_combustion-table-name',
    optionOrder: [
      'natural_gas',
      'heating_oil',
      'biomethane',
      'propane',
      'pellets',
      'forest_chips',
      'wood_logs',
    ],
  },
  {
    id: 'unit',
    labelKey: `${MODULES.Buildings}.inputs.unit`,
    type: 'text',
    readOnlyWhenFilled: true,
    sortable: false,
    align: 'left',
    ratio: '1/3',
    hideIn: { form: false },
    tooltip: 'module-buildings-submodule-energy_combustion-table-unit',
  },
  {
    id: 'quantity',
    labelKey: `${MODULES.Buildings}.inputs.quantity`,
    type: 'number',
    required: true,
    editableInline: true,
    sortable: true,
    min: 0.001,
    step: 0.001,
    ratio: '1/3',
    hideIn: { form: false },
    tooltip: 'module-buildings-submodule-energy_combustion-table-quantity',
  },
  {
    id: 'kg_co2eq',
    labelKey: 'results_units_kg',
    type: 'number',
    readOnly: true,
    hideIn: { form: true },
    sortable: true,
    tooltip: 'module-buildings-submodule-energy_combustion-table-kg_co2eq',
  },
];

export const buildings: ModuleConfig = {
  id: 'module_buildings_001',
  type: MODULES.Buildings as Module,
  hasDescription: true,
  hasDescriptionSubtext: true,
  description:
    'Estimate building-related carbon footprint from energy consumption and combustion',
  hasSubmodules: true,
  formStructure: 'perSubmodule',
  numberFormatOptions: {
    minimumFractionDigits: 0,
    maximumFractionDigits: 1,
  },
  submodules: [
    {
      id: SUBMODULE_BUILDINGS_TYPES.EnergyCombustion,
      type: SUBMODULE_BUILDINGS_TYPES.EnergyCombustion as BuildingsSubType,
      tableNameKey: `${MODULES.Buildings}.combustion_table_title`,
      moduleFields: energyCombustionFields,
      hasTableAction: true,
      addButtonLabelKey: `${MODULES.Buildings}.add_combustion_button`,
    },
    {
      id: SUBMODULE_BUILDINGS_TYPES.Building,
      type: SUBMODULE_BUILDINGS_TYPES.Building as AllSubmoduleTypes,
      tableNameKey: `${MODULES.Buildings}.rooms_table_title`,
      moduleFields: roomFields,
      hasTableAction: true,
      notifyInfoOnAddKey: `${MODULES.Buildings}-rooms-form-add-info`,
      addButtonLabelKey: `${MODULES.Buildings}.add_room_button`,
    },
  ],
  totalFormatter: formatTonnesCO2,
};
