import { ModuleConfig } from 'src/constant/moduleConfig';

export const equipmentElectricConsumption: ModuleConfig = {
  id: 'module_elec_001',
  type: 'equipment-electric-consumption',
  name: 'Equipment Electric Consumption',
  description:
    'List lab equipment with wattage to calculate electricity-related CO2',
  hasSubmodules: true,
  formStructure: 'perSubmodule',
  submodules: [
    {
      id: 'sub_scientific',
      name: 'Scientific Equipment',
      count: 4,
      tableColumns: [
        { key: 'name', label: 'Name', type: 'text', sortable: true },
        { key: 'class', label: 'Class', type: 'select', sortable: true },
        {
          key: 'sub_class',
          label: 'Sub-class',
          type: 'select',
          sortable: true,
        },
        {
          key: 'act_usage',
          label: 'Act. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'pas_usage',
          label: 'Pas. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'act_power',
          label: 'Act. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        {
          key: 'pas_power',
          label: 'Pas. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        { key: 'kg_co2eq', label: 'kg CO2-eq', type: 'number', sortable: true },
      ],
      formInputs: [
        {
          id: 'sci_name',
          label: 'Equipment Name',
          type: 'text',
          required: true,
          placeholder: 'e.g., Agitator, Centrifuge',
        },
        {
          id: 'sci_class',
          label: 'Class',
          type: 'select',
          required: true,
          options: [
            { value: 'agitator', label: 'Agitator' },
            { value: 'centrifuge', label: 'Centrifuge' },
          ],
        },
        {
          id: 'sci_power',
          label: 'Power (Watts)',
          type: 'number',
          required: true,
          min: 0,
        },
      ],
    },
    {
      id: 'sub_it',
      name: 'IT Equipment',
      count: 4,
      tableColumns: [
        { key: 'name', label: 'Name', type: 'text', sortable: true },
        { key: 'class', label: 'Class', type: 'select', sortable: true },
        {
          key: 'sub_class',
          label: 'Sub-class',
          type: 'select',
          sortable: true,
        },
        {
          key: 'act_usage',
          label: 'Act. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'pas_usage',
          label: 'Pas. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'act_power',
          label: 'Act. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        {
          key: 'pas_power',
          label: 'Pas. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        { key: 'kg_co2eq', label: 'kg CO2-eq', type: 'number', sortable: true },
      ],
      formInputs: [
        {
          id: 'it_name',
          label: 'Equipment Name',
          type: 'text',
          required: true,
        },
        {
          id: 'it_quantity',
          label: 'Quantity',
          type: 'number',
          required: true,
          min: 1,
        },
        {
          id: 'it_power',
          label: 'Power per Unit (Watts)',
          type: 'number',
          required: true,
          min: 0,
        },
      ],
    },
    {
      id: 'sub_other',
      name: 'Other',
      count: 4,
      tableColumns: [
        { key: 'name', label: 'Name', type: 'text', sortable: true },
        { key: 'class', label: 'Class', type: 'select', sortable: true },
        {
          key: 'sub_class',
          label: 'Sub-class',
          type: 'select',
          sortable: true,
        },
        {
          key: 'act_usage',
          label: 'Act. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'pas_usage',
          label: 'Pas. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'act_power',
          label: 'Act. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        {
          key: 'pas_power',
          label: 'Pas. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        { key: 'kg_co2eq', label: 'kg CO2-eq', type: 'number', sortable: true },
      ],
      formInputs: [
        {
          id: 'other_name',
          label: 'Equipment Name',
          type: 'text',
          required: true,
        },
        {
          id: 'other_power',
          label: 'Power (Watts)',
          type: 'number',
          required: true,
          min: 0,
        },
      ],
    },
  ],
};
