import { ModuleConfig } from 'src/constant/moduleConfig';

export const equipmentElectricConsumption: ModuleConfig = {
  id: 'module_elec_001',
  type: 'equipment-electric-consumption',
  name: 'Equipment Electric Consumption',
  description:
    'List lab equipment with wattage to calculate electricity-related CO2',
  hasSubmodules: true,
  isCollapsible: true,

  formStructure: 'perSubmodule',
  submodules: [
    {
      id: 'sub_scientific',
      name: 'Scientific Equipment',
      count: 4,
      tableColumns: [
        {
          key: 'name',
          label: 'Name',
          type: 'text',
          sortable: true,
          align: 'left',
        },
        {
          key: 'class',
          label: 'Class',
          type: 'select',
          sortable: true,
          align: 'left',
        },
        {
          key: 'sub_class',
          label: 'Sub-class',
          type: 'select',
          sortable: true,
          align: 'left',
        },
        {
          key: 'act_usage',
          label: 'Act. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
          align: 'right',
        },
        {
          key: 'pas_usage',
          label: 'Pas. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
          align: 'right',
        },
        {
          key: 'act_power',
          label: 'Act. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
          align: 'right',
        },
        {
          key: 'pas_power',
          label: 'Pas. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
          align: 'right',
        },
        {
          key: 'kg_co2eq',
          label: 'kg CO2-eq',
          type: 'number',
          sortable: true,
          align: 'right',
        },
      ],
      formInputs: [
        {
          id: 'sci_name',
          label: 'Equipment Name',
          type: 'text',
          required: true,
          ratio: '1/1',
          placeholder: 'e.g., Agitator, Centrifuge',
        },
        {
          id: 'sci_class',
          label: 'Class',
          icon: 'o_category',
          type: 'select',
          required: true,
          ratio: '1/3',
          options: [
            { value: 'agitator', label: 'Agitator' },
            { value: 'centrifuge', label: 'Centrifuge' },
          ],
        },
        {
          id: 'sci_sub_class',
          label: 'Sub-class',
          icon: 'o_category',
          type: 'select',
          required: true,
          min: 0,
          ratio: '1/3',
          options: [
            { value: '500', label: '500' },
            { value: '800', label: '800' },
            { value: '300', label: '300' },
          ],
        },
        {
          id: 'sci_quantity',
          label: 'Quantity',
          icon: 'o_shopping_cart',
          type: 'number',
          required: true,
          min: 0,
          ratio: '1/3',
        },
        {
          id: 'sci_act_usage',
          label: 'Active Usage',
          icon: 'o_donut_large',
          type: 'select',
          required: true,
          min: 0,
          ratio: '4/12',
          options: [
            { value: '500', label: '500' },
            { value: '800', label: '800' },
            { value: '300', label: '300' },
          ],
        },
        {
          id: 'sci_act_power',
          label: 'h/week',
          type: 'number',
          required: true,
          min: 0,
          ratio: '2/12',
        },
        {
          id: 'sci_act_usage',
          label: 'Active Power',
          icon: 'o_electric_bolt',
          type: 'number',
          required: true,
          min: 0,
          ratio: '4/12',
        },
        {
          id: 'sci_pas_usage',
          label: 'Passive Usage',
          icon: 'o_donut_large',
          type: 'select',
          required: true,
          min: 0,
          ratio: '4/12',
          options: [
            { value: '500', label: '500' },
            { value: '800', label: '800' },
            { value: '300', label: '300' },
          ],
        },
        {
          id: 'sci_pas_power',
          label: 'h/week',
          type: 'number',
          required: true,
          min: 0,
          ratio: '2/12',
        },
        {
          id: 'sci_act_usage',
          label: 'Passive Power',
          icon: 'o_electric_bolt',
          type: 'number',
          required: true,
          min: 0,
          ratio: '4/12',
        },
      ],
    },
    {
      id: 'sub_it',
      name: 'IT Equipment',
      count: 4,
      tableColumns: [
        { key: 'name', label: 'Name', type: 'text', sortable: true },
        { key: 'class', label: 'Class', type: 'select', sortable: true },
        {
          key: 'sub_class',
          label: 'Sub-class',
          type: 'select',
          sortable: true,
        },
        {
          key: 'act_usage',
          label: 'Act. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'pas_usage',
          label: 'Pas. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'act_power',
          label: 'Act. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        {
          key: 'pas_power',
          label: 'Pas. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        { key: 'kg_co2eq', label: 'kg CO2-eq', type: 'number', sortable: true },
      ],
      formInputs: [
        {
          id: 'it_name',
          label: 'Equipment Name',
          type: 'text',
          required: true,
        },
        {
          id: 'it_quantity',
          label: 'Quantity',
          type: 'number',
          required: true,
          min: 1,
          ratio: '1/3',
        },
        {
          id: 'it_power',
          label: 'Power per Unit (Watts)',
          type: 'number',
          required: true,
          min: 0,
          ratio: '2/3',
        },
      ],
    },
    {
      id: 'sub_other',
      name: 'Other',
      count: 4,
      tableColumns: [
        { key: 'name', label: 'Name', type: 'text', sortable: true },
        { key: 'class', label: 'Class', type: 'select', sortable: true },
        {
          key: 'sub_class',
          label: 'Sub-class',
          type: 'select',
          sortable: true,
        },
        {
          key: 'act_usage',
          label: 'Act. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'pas_usage',
          label: 'Pas. Usage',
          type: 'number',
          unit: '%',
          sortable: true,
        },
        {
          key: 'act_power',
          label: 'Act. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        {
          key: 'pas_power',
          label: 'Pas. Power',
          type: 'number',
          unit: 'W',
          sortable: true,
        },
        { key: 'kg_co2eq', label: 'kg CO2-eq', type: 'number', sortable: true },
      ],
      formInputs: [
        {
          id: 'other_name',
          label: 'Equipment Name',
          type: 'text',
          required: true,
        },
        {
          id: 'other_power',
          label: 'Power (Watts)',
          type: 'number',
          required: true,
          min: 0,
          ratio: '1/2',
        },
      ],
    },
  ],
};
