import { ModuleConfig, ModuleField } from 'src/constant/moduleConfig';
import { formatTonnesCO2 } from 'src/utils/number';
import {
  SUBMODULE_PURCHASE_TYPES,
  MODULES,
  MODULES_THRESHOLD_TYPES,
} from 'src/constant/modules';
import type { PurchaseSubType } from 'src/constant/modules';
import type { Module } from 'src/constant/modules';

const purchaseFields: ModuleField[] = [
  {
    id: 'name',
    labelKey: `${MODULES.Purchase}.inputs.name`,
    type: 'text',
    required: true,
    placeholder: 'Enter value',
    sortable: true,
    align: 'left',
    ratio: '1/2',
  },
  {
    id: 'supplier',
    labelKey: `${MODULES.Purchase}.inputs.supplier`,
    type: 'text',
    required: true,
    placeholder: 'Enter value',
    sortable: true,
    align: 'left',
    ratio: '1/2',
  },
  {
    id: 'purchase_institutional_code',
    labelKey: `${MODULES.Purchase}.inputs.purchase_institutional_code`,
    optionsId: 'kind',
    type: 'select',
    required: true,
    sortable: true,
    align: 'left',
    hint: `${MODULES.Purchase}.inputs.purchase_institutional_code-hint`,
    inputTypeName: 'QSelect',
    readOnly: false,
    editableInline: true,
    ratio: '1/3',
    icon: 'o_category',
  },
  {
    id: 'quantity',
    labelKey: `${MODULES.Purchase}.inputs.quantity`,
    type: 'number',
    editableInline: true,
    min: 0,
    step: 0.01,
    ratio: '1/3',
    hideIn: { form: false },
    sortable: true,
  },
  {
    id: 'total_spent_amount',
    labelKey: `${MODULES.Purchase}.inputs.total_spent_amount`,
    type: 'number',
    hint: `${MODULES.Purchase}.inputs.total_spent_amount-hint`,
    editableInline: true,
    min: 0,
    step: 0.01,
    ratio: '1/3',
    hideIn: { form: false },
    sortable: true,
  },
  {
    id: 'kg_co2eq',
    labelKey: 'results_units_kg',
    type: 'number',
    hideIn: { form: true },
    sortable: true,
  },
];

const additionalPurchaseFields: ModuleField[] = [
  {
    id: 'name',
    labelKey: `${MODULES.Purchase}.inputs.name`,
    type: 'text',
    editableInline: false,
    required: true,
    placeholder: 'Enter value',
    sortable: true,
    align: 'left',
    ratio: '1/4',
    hideIn: { form: true },
  },
  {
    id: 'annual_consumption',
    labelKey: `${MODULES.Purchase}.inputs.annual_consumption`,
    type: 'number',
    editableInline: true,
    min: 0,
    step: 1,
    ratio: '1/4',
    hideIn: { form: true },
    sortable: true,
  },
  {
    id: 'unit',
    labelKey: `${MODULES.Purchase}.inputs.unit`,
    type: 'text',
    editableInline: false,
    ratio: '1/4',
    hideIn: { form: true },
    placeholder: 'Enter value',
    sortable: true,
  },
  {
    id: 'kg_co2eq',
    labelKey: 'results_units_kg',
    type: 'number',
    hideIn: { form: true },
    sortable: true,
  },
];

export const purchase: ModuleConfig = {
  id: 'module_purchase_001',
  type: MODULES.Purchase as Module,
  hasDescription: true,
  hasDescriptionSubtext: true,
  hasTooltip: false,
  description:
    'Track purchases of scientific and IT equipment, and their associated emissions.',
  hasSubmodules: true,
  formStructure: 'perSubmodule',
  threshold: {
    type: MODULES_THRESHOLD_TYPES[0],
    value: 500, // kg CO₂-eq; implicit coloring only
  },
  numberFormatOptions: {
    minimumFractionDigits: 1,
    maximumFractionDigits: 1,
  },
  totalFormatter: formatTonnesCO2,
  submodules: [
    {
      id: SUBMODULE_PURCHASE_TYPES.ScientificEquipmentPurchases,
      type: SUBMODULE_PURCHASE_TYPES.ScientificEquipmentPurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.ScientificEquipmentPurchases}-table-title`,
      moduleFields: purchaseFields,
      hasFormTooltip: false,
    },
    {
      id: SUBMODULE_PURCHASE_TYPES.ITEquipmentPurchases,
      type: SUBMODULE_PURCHASE_TYPES.ITEquipmentPurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.ITEquipmentPurchases}-table-title`,
      moduleFields: purchaseFields,
      hasFormTooltip: false,
    },
    {
      id: SUBMODULE_PURCHASE_TYPES.ConsumablePurchases,
      type: SUBMODULE_PURCHASE_TYPES.ConsumablePurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.ConsumablePurchases}-table-title`,
      moduleFields: purchaseFields,
      hasFormTooltip: false,
    },
    {
      id: SUBMODULE_PURCHASE_TYPES.BioProductPurchases,
      type: SUBMODULE_PURCHASE_TYPES.BioProductPurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.BioProductPurchases}-table-title`,
      moduleFields: purchaseFields,
      hasFormTooltip: false,
    },
    {
      id: SUBMODULE_PURCHASE_TYPES.ServicePurchases,
      type: SUBMODULE_PURCHASE_TYPES.ServicePurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.ServicePurchases}-table-title`,
      moduleFields: purchaseFields,
      hasFormTooltip: false,
    },
    {
      id: SUBMODULE_PURCHASE_TYPES.VehiclePurchases,
      type: SUBMODULE_PURCHASE_TYPES.VehiclePurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.VehiclePurchases}-table-title`,
      moduleFields: purchaseFields,
      hasFormTooltip: false,
    },
    {
      id: SUBMODULE_PURCHASE_TYPES.OtherPurchases,
      type: SUBMODULE_PURCHASE_TYPES.OtherPurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.OtherPurchases}-table-title`,
      moduleFields: purchaseFields,
      hasFormTooltip: false,
    },
    {
      id: SUBMODULE_PURCHASE_TYPES.AdditionalPurchases,
      type: SUBMODULE_PURCHASE_TYPES.AdditionalPurchases as PurchaseSubType,
      tableNameKey: `${MODULES.Purchase}.${SUBMODULE_PURCHASE_TYPES.AdditionalPurchases}-table-title`,
      moduleFields: additionalPurchaseFields,
      hasFormTooltip: true,
    },
  ],
};
